/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemoteManagement.framework/RemoteManagement
 */

@interface RMDeclarationKey : NSObject <NSCopying> {
    NSString * _declarationIdentifier;
    NSString * _declarationServerToken;
    NSString * _key;
    NSString * _keyWithoutServerToken;
    NSString * _storeIdentifier;
    NSString * _subscriberIdentifier;
}

@property (nonatomic, readonly, copy) NSString *declarationIdentifier;
@property (nonatomic, readonly, copy) NSString *declarationServerToken;
@property (nonatomic, readonly, copy) NSString *key;
@property (nonatomic, readonly, copy) NSString *keyWithoutServerToken;
@property (nonatomic, readonly, copy) NSString *storeIdentifier;
@property (nonatomic, readonly, copy) NSString *subscriberIdentifier;

+ (id)newDeclarationKey:(id)arg1;
+ (id)newDeclarationKeyWithSubscriberIdentifier:(id)arg1 store:(id)arg2 declaration:(id)arg3;
+ (id)newDeclarationKeyWithSubscriberIdentifier:(id)arg1 storeIdentifier:(id)arg2 declarationIdentifier:(id)arg3 declarationServerToken:(id)arg4;
+ (void)synchronizeOldKeys:(id)arg1 newKeys:(id)arg2 returningUnchangedKeys:(id*)arg3 returningNewAddKeys:(id*)arg4 returningNewChangeKeys:(id*)arg5 returningOldReplaceKeys:(id*)arg6 returningOldRemoveKeys:(id*)arg7;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)declarationIdentifier;
- (id)declarationServerToken;
- (id)description;
- (unsigned long long)hash;
- (id)initWithDeclarationKey:(id)arg1;
- (id)initWithSubscriberIdentifier:(id)arg1 store:(id)arg2 declaration:(id)arg3;
- (id)initWithSubscriberIdentifier:(id)arg1 storeIdentifier:(id)arg2 declarationIdentifier:(id)arg3 declarationServerToken:(id)arg4;
- (bool)isEqual:(id)arg1;
- (bool)isValid;
- (id)key;
- (id)keyWithoutServerToken;
- (id)storeIdentifier;
- (id)subscriberIdentifier;

@end
