/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface _TtCC6HomeUI38ShortcutsAccessoryPickerViewController6Filter : _TtCs12_SwiftObject {
    void block;
}

@end
