/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HomeUI.SimpleAccessoryRepresentableObjectSelectionController : _TtCs12_SwiftObject {
    void _selectedAccessoryRepresentableObjects;
    void selectedAccessoryRepresentableObjectDictionary;
}

@end
