/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HomeUI.AccessoryEventItemSelectionController : NSObject {
    void allowsDeselecting;
    void eventBuilderItem;
    void flow;
    void selectedItems;
    void selectionCompleteFuture;
    void stepIdentifier;
    void triggerBuilder;
}

- (void).cxx_destruct;
- (id)init;

@end
