/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUFontUtilities : NSObject

+ (id)_excessiveLineHeightCharacterSet;
+ (id)fontDescriptorWithMonospacedDigitsForFontDescriptor:(id)arg1;
+ (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })languageAwareOutsetsForString:(id)arg1 withFont:(id)arg2;
+ (id)preferredFontForTextStyle:(id)arg1 traits:(unsigned int)arg2;
+ (id)staticPreferredFontForTextStyle:(id)arg1;
+ (id)staticPreferredFontForTextStyle:(id)arg1 traits:(unsigned int)arg2;

@end
