/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LiftUI.framework/LiftUI
 */

@interface LiftUI.AnyWeakRemoteLoader : _TtCs12_SwiftObject {
    void innerRemoteLoader;
}

@end
