/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CDMFoundation.framework/CDMFoundation
 */

@interface CDMPSCService : CDMDAGBaseService {
    SNLPPommesServerClassifier * _pscOrchestrator;
}

+ (id)_emptyResponse;
+ (id)assetFolderNames;
+ (id)trialFactorName;

- (void).cxx_destruct;
- (id)assetsPathURLForModelBundle:(id)arg1;
- (id)doInference:(id)arg1 error:(id*)arg2;
- (id)getSNLPPommesServerClassifierPath:(id)arg1 error:(id*)arg2;
- (id)handle:(id)arg1;
- (id)handleRequestCommandTypeNames;
- (bool)isAssetRequired;
- (bool)isEnabled;
- (id)setup:(id)arg1;

@end
