/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FocusSettingsUI.framework/FocusSettingsUI
 */

@interface FocusSettingsUI.AppIconCache : _TtCs12_SwiftObject {
    void activeRequests;
    void failedRequests;
    void icons;
    void maxConcurrentRequests;
    void pendingRequests;
    void placeholders;
    void queue;
    void useAppInfoService;
}

@end
