/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NotesAnalytics.framework/NotesAnalytics
 */

@interface ICNACollabOwnedRootFolderAcceptanceRatioHistogram : ICNAHistogramBase

- (void)setup;

@end
