/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKAppleCardOfferExperiment : PKAppleCardApplyExperiment

- (id)namespaceName;

@end
