/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPassAuxiliaryRegistrationRequirement : NSObject <NSCopying, NSSecureCoding> {
    NSString * _identifier;
    long long  _registrationBackoffCounter;
}

@property (nonatomic, retain) NSString *identifier;
@property (nonatomic) long long registrationBackoffCounter;
@property (nonatomic, readonly) unsigned long long role;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_copyInto:(id)arg1;
- (id)_mutableDictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)identifier;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToPassAuxiliaryRegistrationRequirement:(id)arg1;
- (long long)registrationBackoffCounter;
- (unsigned long long)role;
- (void)setIdentifier:(id)arg1;
- (void)setRegistrationBackoffCounter:(long long)arg1;

@end
