/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContextualUnderstanding.framework/ContextualUnderstanding
 */

@interface ContextualUnderstanding.SoundAnalyzer : NSObject {
    void _soundAnalysisInProgress;
    void soundClassifier;
}

- (void).cxx_destruct;
- (id)init;

@end
