/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NetworkServiceProxy.framework/NetworkServiceProxy
 */

@interface NSPPrivacyProxyNetworkRegistration : NSObject <NSPPrivacyProxyConfigAgentDelegate> {
    NSData * _configurationData;
    NSData * _configurationHash;
    <NSPPrivacyProxyNetworkRegistrationDelegate> * _delegate;
    NSPPrivacyProxyConfigAgent * _proxyConfigAgent;
    NWNetworkAgentRegistration * _proxyConfigAgentRegistration;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)reportErrorForAgent:(id)arg1 error:(int)arg2 withOptions:(id)arg3;

@end
