/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface SFReaderThemeButton : UIButton

- (bool)canBecomeFocused;
- (id)focusEffect;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;

@end
