/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMMomentShareUtilities : NSObject

+ (id)photoShareURLFromPluginBundleID:(id)arg1 contentString:(id)arg2 payload:(id)arg3;

@end
