/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSettingsIntents.framework/SiriSettingsIntents
 */

@interface _TtCC19SiriSettingsIntents23SettingsNativeApiClient18SettingsFlashlight : _TtCs12_SwiftObject {
    void flashlight;
}

@end
