/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSettingsIntents.framework/SiriSettingsIntents
 */

@interface SiriSettingsIntents.SetAXIncreaseContrastHandler : _TtCs12_SwiftObject {
    void enableTelemetryForSignpost;
    void nativeApiClient;
}

@end
