/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProximityControl.framework/ProximityControl
 */

@interface PCMediaTransferContext : NSObject <NSSecureCoding>

+ (bool)supportsSecureCoding;

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
