/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PreviewsShellKit.framework/PreviewsShellKit
 */

@interface PSKScene : NSObject {
    FBScene * _scene;
}

@property (nonatomic, readonly) FBScene *scene;
@property (nonatomic, readonly) NSString *sceneIdentifier;
@property (nonatomic, readonly) PSKSceneSettings *sceneSettings;

- (void).cxx_destruct;
- (id)initWithScene:(id)arg1;
- (id)scene;
- (id)sceneIdentifier;
- (id)sceneSettings;
- (void)updateSceneSettings:(id)arg1 with:(id)arg2;

@end
