/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TipsCore.framework/TipsCore
 */

@interface TPSAnalyticsEventTipTimeSpent : TPSAnalyticsEvent {
    NSString * _collectionID;
    NSString * _correlationID;
    bool  _notificationModelControl;
    double  _timeSpent;
    NSString * _tipID;
    NSNumber * _trialDeploymentID;
    NSString * _trialExperimentID;
    NSString * _trialRampID;
    NSString * _trialTreatmentID;
}

@property (nonatomic, retain) NSString *collectionID;
@property (nonatomic, retain) NSString *correlationID;
@property (getter=isNotificationModelControl, nonatomic) bool notificationModelControl;
@property (nonatomic) double timeSpent;
@property (nonatomic, retain) NSString *tipID;
@property (nonatomic, retain) NSNumber *trialDeploymentID;
@property (nonatomic, retain) NSString *trialExperimentID;
@property (nonatomic, retain) NSString *trialRampID;
@property (nonatomic, retain) NSString *trialTreatmentID;

+ (id)eventWithTipID:(id)arg1 collectionID:(id)arg2 correlationID:(id)arg3;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_initWithTipID:(id)arg1 collectionID:(id)arg2 correlationID:(id)arg3;
- (id)collectionID;
- (id)correlationID;
- (void)encodeWithCoder:(id)arg1;
- (id)eventName;
- (id)initWithCoder:(id)arg1;
- (bool)isNotificationModelControl;
- (id)mutableAnalyticsEventRepresentation;
- (void)setCollectionID:(id)arg1;
- (void)setCorrelationID:(id)arg1;
- (void)setDataProvider:(id)arg1;
- (void)setNotificationModelControl:(bool)arg1;
- (void)setTimeSpent:(double)arg1;
- (void)setTipID:(id)arg1;
- (void)setTrialDeploymentID:(id)arg1;
- (void)setTrialExperimentID:(id)arg1;
- (void)setTrialRampID:(id)arg1;
- (void)setTrialTreatmentID:(id)arg1;
- (double)timeSpent;
- (id)tipID;
- (id)trialDeploymentID;
- (id)trialExperimentID;
- (id)trialRampID;
- (id)trialTreatmentID;

@end
