/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TipsCore.framework/TipsCore
 */

@interface TPSFeatureFlags : NSObject

+ (bool)allowModelControlledNotifications;
+ (bool)allowNotificationsPFLPlugin;
+ (bool)allowNotificationsPFLPluginTesting;
+ (bool)allowReplayButton;
+ (bool)allowSavedTips;
+ (bool)allowTipsSearch;

@end
