/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaControls.framework/MediaControls
 */

@interface MRUVolumeBackgroundView : UIView {
    MRUVolumeNowPlayingView * _nowPlayingView;
    MRUOutputDeviceAssetView * _primaryAssetView;
    MediaControlsBluetoothListeningModeButton * _primaryListeningModeButton;
    MRUOutputDeviceAssetView * _secondaryAssetView;
    MediaControlsBluetoothListeningModeButton * _secondaryListeningModeButton;
    bool  _showNowPlayingView;
    bool  _showPrimaryListeningModeButton;
    bool  _showSecondaryAssetView;
    bool  _showSecondaryListeningModeButton;
    bool  _showSpatialAudioModeButton;
    MediaControlsExpandableButton * _spatialAudioModeButton;
    MRUVisualStylingProvider * _stylingProvider;
}

@property (nonatomic, readonly) bool hasExpandedButtons;
@property (nonatomic, retain) MRUVolumeNowPlayingView *nowPlayingView;
@property (nonatomic, retain) MRUOutputDeviceAssetView *primaryAssetView;
@property (nonatomic, retain) MediaControlsBluetoothListeningModeButton *primaryListeningModeButton;
@property (nonatomic, retain) MRUOutputDeviceAssetView *secondaryAssetView;
@property (nonatomic, retain) MediaControlsBluetoothListeningModeButton *secondaryListeningModeButton;
@property (nonatomic) bool showNowPlayingView;
@property (nonatomic) bool showPrimaryListeningModeButton;
@property (nonatomic) bool showSecondaryAssetView;
@property (nonatomic) bool showSecondaryListeningModeButton;
@property (nonatomic) bool showSpatialAudioModeButton;
@property (nonatomic, retain) MediaControlsExpandableButton *spatialAudioModeButton;
@property (nonatomic, retain) MRUVisualStylingProvider *stylingProvider;

- (void).cxx_destruct;
- (void)collapseExpandableButtons;
- (void)expandButton:(id)arg1;
- (bool)hasExpandedButtons;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (void)layoutSubviewsHorizontal;
- (void)layoutSubviewsVertical;
- (id)nowPlayingView;
- (id)primaryAssetView;
- (id)primaryListeningModeButton;
- (id)secondaryAssetView;
- (id)secondaryListeningModeButton;
- (void)setNowPlayingView:(id)arg1;
- (void)setPrimaryAssetView:(id)arg1;
- (void)setPrimaryListeningModeButton:(id)arg1;
- (void)setSecondaryAssetView:(id)arg1;
- (void)setSecondaryListeningModeButton:(id)arg1;
- (void)setShowNowPlayingView:(bool)arg1;
- (void)setShowPrimaryListeningModeButton:(bool)arg1;
- (void)setShowSecondaryAssetView:(bool)arg1;
- (void)setShowSecondaryListeningModeButton:(bool)arg1;
- (void)setShowSpatialAudioModeButton:(bool)arg1;
- (void)setSpatialAudioModeButton:(id)arg1;
- (void)setStylingProvider:(id)arg1;
- (bool)showNowPlayingView;
- (bool)showPrimaryListeningModeButton;
- (bool)showSecondaryAssetView;
- (bool)showSecondaryListeningModeButton;
- (bool)showSpatialAudioModeButton;
- (id)spatialAudioModeButton;
- (id)stylingProvider;
- (void)updateVisibility;

@end
