/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.DescriptorService : NSObject {
    void _descriptorPublisher;
    void _queue_currentExtensionsAndCompletionsBeingFetched;
    void _queue_extensionEvents;
    void _queue_queryTimer;
    void _queue_readyDataSources;
    void _queue_tasks;
    void _test_noRetries;
    void configurationService;
    void descriptorCache;
    void descriptorProvider;
    void extensionManager;
    void persistentSubscriptions;
    void preferences;
    void queryTimerInterval;
    void queryTimerLeeway;
    void queue;
    void taskService;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end
