/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.TaskSessionQueuePool : NSObject {
    void _queuePool;
}

- (void).cxx_destruct;
- (id)init;

@end
