/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.PublishingLayoutDelegate : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _leadingViewFrame;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _minimalViewFrame;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _trailingViewFrame;
}

@end
