/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MetalFX.framework/MetalFX
 */

@interface MFXTemporalScalingEffectDescriptor : MTLFXTemporalScalerDescriptor

- (id)newTemporalScalingEffectWithDevice:(id)arg1;

@end
