/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFContentExfiltrationQuantityInfo : NSObject

+ (long long)deletionItemCountLimitForContentWithContentItemClassName:(id)arg1;
+ (long long)sharingItemCountLimitForContentWithAttribution:(id)arg1;

@end
