/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFFontPickerParameter : WFParameter

- (id)defaultSerializedRepresentation;
- (Class)singleStateClass;

@end
