/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFLinkBooksOpenDefaultCollectionAction : WFLinkOpenEntityAction

- (id)overrideLabelsByParameter;
- (id)overrideName;
- (bool)shouldOverrideParameterLabels;

@end
