/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFRemoteServerAccessResource : WFAccessResource

+ (bool)isSystemResource;

- (id)icon;
- (id)init;
- (id)name;
- (unsigned long long)status;

@end
