/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI
 */

@interface HealthRecordsUI.AllFeedForProfileDataSourceProvider : _TtCs12_SwiftObject {
    void sourceProfile;
    void store;
}

@end
