/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI
 */

@interface HealthRecordsUI.ConceptListViewController : HealthRecordsUI.FeedItemListViewController

- (void)viewDidAppear:(bool)arg1;

@end
