/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafariUI.framework/MobileSafariUI
 */

@interface FindOnPageCompletionTableViewCell : CompletionListTableViewCell

- (void)layoutSubviews;

@end
