/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafariUI.framework/MobileSafariUI
 */

@interface FrequentlyVisitedSitesController : WBSFrequentlyVisitedSitesController {
    WebBookmarkCollection * _bookmarkCollection;
    bool  _bookmarksNeedToSave;
    NSMutableArray * _cachedFrequentlyVisitedBookmarks;
    bool  _ignoreBookmarksFolderChangeNotifications;
}

+ (id)sharedController;

- (void).cxx_destruct;
- (id)_canonicalizedFavoritesURLStringSet;
- (void)_clearFrequentlyVisitedSitesInBookmarksDB;
- (id)_existingIconsDataFromBookmarksDB;
- (void)_receivedBookmarksFolderContentChangedNotification:(id)arg1;
- (bool)_saveFrequentlyVisitedSites:(id)arg1;
- (bool)_updateCachedFrequentlyVisitedSitesWithCandidates:(id)arg1;
- (void)banFrequentlyVisitedSite:(id)arg1 inMemoryBookmarkChangeTrackingAvailable:(bool)arg2;
- (void)clearFrequentlyVisitedSites;
- (void)dealloc;
- (id)frequentlyVisitedSites;
- (id)initWithBookmarkCollection:(id)arg1;
- (void)promoteFrequentlyVisitedSite:(id)arg1 toFavoriteAtIndex:(unsigned long long)arg2;
- (void)saveFrequentlyVisitedSitesToBookmarksDBWithCompletion:(id /* block */)arg1;

@end
