/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafariUI.framework/MobileSafariUI
 */

@interface ToggleReaderActivity : TabDocumentActivity

- (bool)_isDisabled;
- (bool)_isEnabled;
- (id)_systemImageName;
- (long long)actionType;
- (id)activityTitle;
- (id)activityType;
- (void)performActivityWithTabDocument:(id)arg1;

@end
