/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafariUI.framework/MobileSafariUI
 */

@interface WebsiteSettingsActivity : TabDocumentActivity

- (id)_systemImageName;
- (long long)actionType;
- (id)activityTitle;
- (id)activityType;
- (void)performActivityWithTabDocument:(id)arg1;

@end
