/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IconFoundation.framework/IconFoundation
 */

@interface IFGraphicSymbolDefaults : NSObject {
    long long  _enclosureColor;
    long long  _enclosureColorAlternate;
    double  _enclosureSizeMultiplier;
    long long  _fill;
    long long  _renderingMode;
    long long  _shape;
    long long  _symbolColor;
    long long  _symbolColorAlternate;
    NSString * _symbolName;
}

@property (readonly) long long enclosureColor;
@property (readonly) long long enclosureColorAlternate;
@property (readonly) double enclosureSizeMultiplier;
@property (readonly) long long fill;
@property (readonly) long long renderingMode;
@property (readonly) long long shape;
@property (readonly) long long symbolColor;
@property (readonly) long long symbolColorAlternate;
@property (readonly) NSString *symbolName;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (long long)enclosureColor;
- (long long)enclosureColorAlternate;
- (double)enclosureSizeMultiplier;
- (long long)fill;
- (id)init;
- (long long)renderingMode;
- (long long)shape;
- (long long)symbolColor;
- (long long)symbolColorAlternate;
- (id)symbolName;

@end
