/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NotTheStoreKitUIFrameworkYouAreLookingFor.framework/NotTheStoreKitUIFrameworkYouAreLookingFor
 */

@interface NTSKUIFYALFManager : NSObject

@end
