/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BookLibraryCore.framework/BookLibraryCore
 */

@interface BLJaliscoVersion : NSObject

+ (id)defaultIdentifier;
+ (id)persistentStoreFileName;
+ (id)schemaVersion;

@end
