/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourMedia.framework/SeymourMedia
 */

@interface SeymourMedia.MediaTagStringBuilder : _TtCs12_SwiftObject {
    void platform;
    void storefrontLocalizer;
    void table;
    void wheelchairStatus;
}

@end
