/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourMedia.framework/SeymourMedia
 */

@interface SeymourMedia.ScreenCaptureMonitor : _TtCs12_SwiftObject {
    void eventHub;
    void scenesProvider;
}

- (void)screenCaptureChanged:(id)arg1;

@end
