/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServicesCore.framework/PhotoLibraryServicesCore
 */

@interface PLAssetsdMigrationClient : PLAssetsdBaseClient

- (void)cleanupModelForDataMigrationForRestoreType:(long long)arg1;
- (void)dataMigrationWillFinish;
- (void)moveiPhotoLibraryMediaWithReply:(id /* block */)arg1;

@end
