/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthRecordsDaemon.framework/HealthRecordsDaemon
 */

@interface HealthRecordsDaemon.IssuerDirectoryDownloadTaskManager : _TtCs12_SwiftObject {
    void catalogDownloadTaskQueue;
    void requestPerformer;
    void scheduler;
    void signedClinicalDataStore;
}

@end
