/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherAnalytics.framework/WeatherAnalytics
 */

@interface WeatherAnalytics.TelemetryPrivacySampler : _TtCs12_SwiftObject {
    void privacySampler;
    void samplingRate;
}

@end
