/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriReferenceResolution.framework/SiriReferenceResolution
 */

@interface SiriReferenceResolution.SRRDefaults : _TtCs12_SwiftObject

@end
