/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRepairKit.framework/CoreRepairKit
 */

@interface CRBluetoothStatus : CRComponentAuth

- (long long)copyComponentStatusForQuery:(id)arg1;

@end
