/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRepairUI.framework/CoreRepairUI
 */

@interface CRComponentsDisplayRepair : CRUNonGenuineComponents

- (id)specifiers;

@end
