/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRepairUI.framework/CoreRepairUI
 */

@interface CRUNonGenuineComponentsWifi : CRUNonGenuineComponents

- (id)specifiers;

@end
