/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TranslationUI.framework/TranslationUI
 */

@interface _TtCV13TranslationUI11CloseButton11Coordinator : _TtCs12_SwiftObject {
    void button;
}

@end
