/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProductKit.framework/ProductKit
 */

@interface ProductKit.PersonalizationAssetManager : _TtCs12_SwiftObject {
    void cloudKitContainer;
    void dependencies;
}

@end
