/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iCloudSubscriptionOptimizerDaemon.framework/iCloudSubscriptionOptimizerDaemon
 */

@interface iCloudSubscriptionOptimizerDaemon.XpcCallStartedEvent : iCloudSubscriptionOptimizerDaemon.DaemonEvent

@end
