/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RenderBox.framework/RenderBox
 */

@interface RBSharedSurfaceContents : NSObject <CARenderValue> {
    struct atomic<_opaque_pthread_t *> { 
        struct __cxx_atomic_impl<_opaque_pthread_t *, std::__cxx_atomic_base_impl<_opaque_pthread_t *>> { 
            _Atomic struct _opaque_pthread_t {} *__a_value; 
        } __a_; 
    }  _last_update_thread;
    void * _surface;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id).cxx_construct;
- (void*)CA_copyRenderValue;
- (void)CA_prepareRenderValue;

@end
