/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PodcastsFoundation.framework/PodcastsFoundation
 */

@interface MTPodcastUpdateAverageCalculator : NSObject

- (id)init;
- (void)unsafeSetUpdateAverageWithPodcast:(id)arg1 on:(id)arg2;

@end
