/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DMCEnrollmentProvider.framework/DMCEnrollmentProvider
 */

@interface DMCAccountSpecifierProvider : NSObject {
    ACAccountStore * _accountStore;
    <DMCAccountSpecifierProviderDelegate> * _delegate;
    NSObject<OS_dispatch_queue> * _updateQueue;
}

@property (nonatomic) <DMCAccountSpecifierProviderDelegate> *delegate;

+ (id)groupSpecifierID;
+ (id)itemSpecifierIDForAccountUsername:(id)arg1;
+ (id)itemSpecifierIDForReauthAccountUsername:(id)arg1;
+ (id)itemSpecifierIDPrefix;

- (void).cxx_destruct;
- (void)_accountCellWasTappedWithSpecifier:(id)arg1;
- (id)_reauthSpecifierForAccount:(id)arg1;
- (id)_specifierForManagedAccount:(id)arg1;
- (id)_specifierForManagedAccountGroupWithTitle:(bool)arg1 plural:(bool)arg2;
- (void)appleAccountsDidChange:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (id)initWithAccountStore:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)specifiersWithCompletion:(id /* block */)arg1;
- (id)specifiersWithTitle:(bool)arg1 includePrimaryAccounts:(bool)arg2;

@end
