/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MagazineSectionService : _TtCs12_SwiftObject {
    void assetHandleFactory;
    void bundleSubscriptionManager;
    void magazineConfigurationService;
}

@end
