/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.SavedFeedDataProvider : _TtCs12_SwiftObject {
    void readingList;
}

@end
