/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.AudioFeedConfigService : _TtCs12_SwiftObject {
    void appConfigManager;
    void audioFeedConfigManager;
    void contentContext;
    void decoder;
}

@end
