/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.SharedWithYouFeedConfigManager : _TtCs12_SwiftObject {
    void appConfigManager;
    void decoder;
    void resourceService;
}

@end
