/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.TodayEngagementOverlayManager : NSObject {
    void blueprintViewController;
    void delegate;
    void engagementOverlayDialogRequests;
    void engagementViewControllerFactory;
    void isFetchingAssets;
    void overlayToElementSpacing;
    void presentedOverlaySize;
    void todayViewController;
}

- (void).cxx_destruct;
- (id)init;

@end
