/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HeadphoneConfigs.framework/HeadphoneConfigs
 */

@interface AccessorySubController : PSListItemsController {
    BTSDevice * _currentDevice;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (void)listItemSelected:(id)arg1;
- (id)specifiers;

@end
