/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SystemStatusServer.framework/SystemStatusServer
 */

@interface STStatusDomainXPCClientHandle : NSObject <STStatusDomainClientHandle, STStatusDomainXPCServer> {
    NSXPCConnection * _clientXPCConnection;
    BSMutableIntegerMap * _dataByDomain;
    NSSet * _entitledDomains;
    NSObject<OS_dispatch_queue> * _internalQueue;
    NSMutableSet * _observingDomains;
    <STStatusDomainServerHandle> * _serverHandle;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithXPCConnection:(id)arg1 serverHandle:(id)arg2;
- (void)observeData:(id)arg1 forDomain:(unsigned long long)arg2 withChangeContext:(id)arg3;
- (void)observeDomains:(id)arg1;
- (void)reportUserInteraction:(id)arg1 forDomain:(unsigned long long)arg2;
- (void)serverDataForDomains:(id)arg1 reply:(id /* block */)arg2;
- (void)stopObservingDomains:(id)arg1;

@end
