/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BookFoundation.framework/BookFoundation
 */

@interface BookFoundation.MBook : BFMAssetBase

@property (nonatomic, readonly) long long type;

- (long long)type;

@end
