/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MPCPlayPerfAnalytics : NSObject {
    NSString * _identifier;
    MPCPlayToSetRateSignpost * _playToSetRateSignpost;
    MPCSetRateToEffectiveRateSignpost * _setRateToEffectiveRateSignpost;
    MPCWaitForLikelyToKeepUp * _waitForLikelyToKeepUpSignpost;
    MPCWaitForReadyToPlaySignpost * _waitForReadyToPlaySignpost;
}

@property (nonatomic, retain) NSString *identifier;
@property (nonatomic, retain) MPCPlayToSetRateSignpost *playToSetRateSignpost;
@property (nonatomic, retain) MPCSetRateToEffectiveRateSignpost *setRateToEffectiveRateSignpost;
@property (nonatomic, retain) MPCWaitForLikelyToKeepUp *waitForLikelyToKeepUpSignpost;
@property (nonatomic, retain) MPCWaitForReadyToPlaySignpost *waitForReadyToPlaySignpost;

+ (id)playPerfAnalyticsWithIdentifier:(id)arg1 willPlayImmediately:(bool)arg2;

- (void).cxx_destruct;
- (void)didReceivePlayRequest;
- (void)firstFrameWillRenderForItem:(id)arg1 machAbsoluteTime:(unsigned long long)arg2;
- (id)identifier;
- (id)initWithIdentifier:(id)arg1;
- (void)itemDidBecomeCurrent:(id)arg1;
- (void)itemDidFailToLoad:(id)arg1 error:(id)arg2;
- (void)itemIsReadyToPlay:(id)arg1;
- (id)playToSetRateSignpost;
- (void)playbackDidStopForItem:(id)arg1;
- (void)playbackIsLikelyToKeepUp:(bool)arg1 forItem:(id)arg2;
- (void)playbackRateDidChangeForItem:(id)arg1 rate:(float)arg2;
- (void)setIdentifier:(id)arg1;
- (void)setPlayToSetRateSignpost:(id)arg1;
- (id)setRateToEffectiveRateSignpost;
- (void)setSetRateToEffectiveRateSignpost:(id)arg1;
- (void)setWaitForLikelyToKeepUpSignpost:(id)arg1;
- (void)setWaitForReadyToPlaySignpost:(id)arg1;
- (id)waitForLikelyToKeepUpSignpost;
- (id)waitForReadyToPlaySignpost;

@end
