/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MPCSharedListeningPlaybackIntentTracklistToken : NSObject <NSSecureCoding> {
    ICLiveLinkIdentity * _identity;
    MPCPlaybackSharedListeningProperties * _sharedListeningProperties;
}

@property (nonatomic, copy) ICLiveLinkIdentity *identity;
@property (nonatomic, copy) MPCPlaybackSharedListeningProperties *sharedListeningProperties;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)identity;
- (id)initWithCoder:(id)arg1;
- (void)setIdentity:(id)arg1;
- (void)setSharedListeningProperties:(id)arg1;
- (id)sharedListeningProperties;

@end
