/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNRequestPerformingPriorityGroup2AsyncTasksQueueCache : VNAsyncTasksQueueCache

+ (long long)maximumAllowedTasksInTheQueue;
+ (id)queueLabelWithUniqueAppendix:(id)arg1;
+ (id)sharedCache;

@end
