/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CopresenceCore.framework/CopresenceCore
 */

@interface CopresenceCore.DarwinNotification : _TtCs12_SwiftObject {
    void name;
    void subject;
    void token;
}

@end
