/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CopresenceCore.framework/CopresenceCore
 */

@interface CPSession : NSObject <NSCopying, NSSecureCoding> {
    NSString * _createdByAccountID;
    NSMutableDictionary * _members;
    NSString * _receivedFromAccountID;
    NSString * _sessionID;
}

@property (nonatomic, retain) NSString *createdByAccountID;
@property (nonatomic, retain) NSDictionary *members;
@property (nonatomic, readonly) NSString *receivedFromAccountID;
@property (nonatomic, readonly, retain) NSString *sessionID;

+ (id)memberStateToString:(unsigned char)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_idsMembersExcludingSelf:(id)arg1 withState:(unsigned char)arg2;
- (id)acceptedIDSMembersExcludingSelf:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)createdByAccountID;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSessionID:(id)arg1 createdBy:(id)arg2 memberState:(id)arg3 receivedFrom:(id)arg4;
- (id)initWithSessionID:(id)arg1 createdByAccountID:(id)arg2;
- (id)initWithSessionID:(id)arg1 createdByAccountID:(id)arg2 receivedFromAccountID:(id)arg3;
- (id)invitedIDSMembersExcludingSelf:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)members;
- (id)receivedFromAccountID;
- (id)sessionID;
- (void)setCreatedByAccountID:(id)arg1;
- (void)setMember:(id)arg1 state:(unsigned char)arg2;
- (void)setMembers:(id)arg1;

@end
