/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileTimerUI.framework/MobileTimerUI
 */

@interface MTUITimeView : UILabel {
    double  _time;
}

@property (nonatomic) double time;

// Image: /System/Library/PrivateFrameworks/MobileTimerUI.framework/MobileTimerUI

- (void)handleLocaleChange;
- (void)setTime:(double)arg1;
- (double)time;

// Image: /System/Library/AccessibilityBundles/MobileTimerUIFramework.axbundle/MobileTimerUIFramework

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;

@end
