/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRIPushServiceConnectionCreator : NSObject <TRIPushServiceConnectionCreating>

- (id)connectionWithDelegate:(id)arg1 environment:(unsigned char)arg2;

@end
