/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriActivation.framework/SiriActivation
 */

@interface SASTipKitSignalEmitter : NSObject

+ (void)_checkAndEmitSignalsWithSource:(id)arg1 forRequestOptions:(id)arg2;
+ (void)checkAndEmitSignalsForRequestOptions:(id)arg1;

@end
