/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MapsUI.framework/MapsUI
 */

@interface MUTransitLineItemViewController : UIViewController <MKETAProviderDelegate, MKPlaceActionManagerTransitDelegate, MUHeaderButtonsSectionControllerDelegate, MUInfoCardAnalyticsDelegate, MUInfoCardContentProtocol, MUNearestStationSectionControllerDelegate, MUPlaceDescriptionSectionControllerDelegate, MUTransitLineIncidentsSectionControllerDelegate, UIScrollViewDelegate> {
    MUPlaceActionManager * _actionManager;
    GEOAutomobileOptions * _automobileOptions;
    double  _contentAlpha;
    MUScrollableStackView * _contentStackView;
    GEOCyclingOptions * _cyclingOptions;
    <MUTransitLineItemViewControllerDelegate> * _delegate;
    MKETAProvider * _etaProvider;
    NSNumber * _favorited;
    MUHeaderButtonsSectionController * _headerButtonsSectionController;
    MUPlaceHeaderView * _headerView;
    NSString * _lastNearestRequestErrorMessage;
    bool  _loading;
    MULoadingOverlayController * _loadingOverlayController;
    MUNearestStationProvider * _nearbyStationProvider;
    MUNearestStationSectionController * _nearestStationSectionController;
    <UIScrollViewDelegate> * _scrollViewDelegate;
    NSArray * _sectionControllers;
    <GEOTransitLineItem> * _transitLineItem;
    GEOTransitOptions * _transitOptions;
    GEOWalkingOptions * _walkingOptions;
}

@property (nonatomic, retain) GEOAutomobileOptions *automobileOptions;
@property (nonatomic) double contentAlpha;
@property (nonatomic, retain) GEOCyclingOptions *cyclingOptions;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <MUTransitLineItemViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSNumber *favorited;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) MUHeaderButtonsSectionController *headerButtonsSectionController;
@property (nonatomic, readonly) double heightForContentAboveTitle;
@property (getter=isLoading, nonatomic) bool loading;
@property (nonatomic, readonly) UIScrollView *scrollView;
@property (nonatomic) <UIScrollViewDelegate> *scrollViewDelegate;
@property (readonly) Class superclass;
@property (nonatomic, readonly) <GEOTransitLineItem> *transitLineItem;
@property (nonatomic, retain) GEOTransitOptions *transitOptions;
@property (nonatomic, retain) GEOWalkingOptions *walkingOptions;

+ (double)headerHeightInMinimalMode;

- (void).cxx_destruct;
- (void)_attachLoadingOverlayIfNeeded;
- (void)_fetchNearestStation;
- (id)_footerSectionController;
- (void)_removeLoadingOverlayIfNeeded;
- (void)_setupContentView;
- (void)_updateSectionControllers;
- (id)automobileOptions;
- (void)contentAboveTitleScrollPositionChanged:(double)arg1;
- (double)contentAlpha;
- (id)createMenuActions;
- (double)currentHeight;
- (id)cyclingOptions;
- (id)delegate;
- (id)draggableContent;
- (id)draggableHeaderView;
- (id)favorited;
- (id)headerButtonsSectionController;
- (void)headerButtonsSectionController:(id)arg1 didSelectPrimaryType:(unsigned long long)arg2 withPresentationOptions:(id)arg3;
- (void)headerButtonsSectionControllerDidUpdateContent:(id)arg1;
- (double)heightForContentAboveTitle;
- (void)hideTitle:(bool)arg1;
- (void)incidentsSectionController:(id)arg1 didSelectDetailsForIncidents:(id)arg2;
- (void)infoCardAnalyticsDidSelectAction:(int)arg1 eventValue:(id)arg2 feedbackDelegateSelector:(int)arg3;
- (void)infoCardAnalyticsDidSelectAction:(int)arg1 target:(int)arg2 eventValue:(id)arg3 actionURL:(id)arg4 photoID:(id)arg5 feedbackDelegateSelector:(int)arg6;
- (void)infoCardAnalyticsDidSelectAction:(int)arg1 target:(int)arg2 eventValue:(id)arg3 actionURL:(id)arg4 photoID:(id)arg5 moduleMetadata:(id)arg6 feedbackDelegateSelector:(int)arg7;
- (void)infoCardAnalyticsDidSelectAction:(int)arg1 target:(int)arg2 eventValue:(id)arg3 feedbackDelegateSelector:(int)arg4;
- (void)infoCardAnalyticsDidSelectAction:(int)arg1 target:(int)arg2 eventValue:(id)arg3 moduleMetadata:(id)arg4 feedbackDelegateSelector:(int)arg5;
- (void)infoCardTransitAnalyticsDidSelectionAction:(int)arg1 resultIndex:(long long)arg2 targetID:(unsigned long long)arg3 transitSystem:(id)arg4 transitDepartureSequence:(id)arg5 transitCardCategory:(int)arg6 transitIncident:(id)arg7 feedbackDelegateSelector:(int)arg8;
- (id)initWithTransitLineItem:(id)arg1;
- (bool)isLoading;
- (int)mapTypeForETAProvider:(id)arg1;
- (void)nearestStationSectionController:(id)arg1 didTapStationItem:(id)arg2;
- (void)performAction:(id)arg1 options:(id)arg2 completion:(id /* block */)arg3;
- (void)placeActionManagerDidSelectAddToFavorites:(id)arg1;
- (void)placeActionManagerDidSelectRemoveFromFavorites:(id)arg1;
- (void)placeActionManagerDidSelectReportAProblem:(id)arg1 fromView:(id)arg2 isQuickAction:(bool)arg3;
- (void)placeActionManagerDidSelectReportAProblem:(id)arg1 isQuickAction:(bool)arg2;
- (void)placeDescriptionSectionControllerDidTapAttribution:(id)arg1;
- (void)resetNearestStation;
- (void)scrollToTopAnimated:(bool)arg1;
- (id)scrollView;
- (id)scrollViewDelegate;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setAutomobileOptions:(id)arg1;
- (void)setContentAlpha:(double)arg1;
- (void)setCyclingOptions:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setFavorited:(id)arg1;
- (void)setLoading:(bool)arg1;
- (void)setScrollViewDelegate:(id)arg1;
- (void)setTransitLineItem:(id)arg1;
- (void)setTransitLineItem:(id)arg1 loading:(bool)arg2;
- (void)setTransitOptions:(id)arg1;
- (void)setWalkingOptions:(id)arg1;
- (id)transitLineItem;
- (id)transitOptions;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (id)walkingOptions;

@end
