/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherDaemon.framework/WeatherDaemon
 */

@interface WeatherDaemon.WeatherAlertService : _TtCs12_SwiftObject {
    void client;
}

@end
