/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NeutrinoCore.framework/NeutrinoCore
 */

@interface NUVideoPlaybackFrameJob : NURenderJob

- (bool)complete:(out id*)arg1;
- (id)frameRequest;
- (id)initWithRequest:(id)arg1;
- (id)initWithVideoFrameRequest:(id)arg1;
- (id)newRenderPipelineStateForEvaluationMode:(long long)arg1;
- (bool)render:(out id*)arg1;
- (id)renderer:(out id*)arg1;
- (id)result;
- (id)scalePolicy;
- (bool)shouldGenerateHDRMetadata;
- (bool)wantsCompleteStage;
- (bool)wantsOutputVideoFrame;
- (bool)wantsPrepareNodeCached;
- (bool)wantsRenderNodeCached;

@end
