/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourServices.framework/SeymourServices
 */

@interface SeymourServices.ScriptUpdateJournalCache : _TtCs12_SwiftObject

@end
