/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourServices.framework/SeymourServices
 */

@interface SeymourServices.BookmarkListener : _TtCs12_SwiftObject {
    void bookmarkSystem;
    void remoteParticipantBroadcastConnection;
    void scriptConnection;
    void xpcBroadcastConnection;
}

@end
