/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMImaging.framework/CMImaging
 */

@interface VISProvider : NSObject

+ (id)VISConfigurationForVersion:(unsigned int)arg1;
+ (id)VISProcessorForVersion:(unsigned int)arg1;
+ (id)_loadVISBundleForVersion:(unsigned int)arg1;

@end
