/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConditionInducer.framework/ConditionInducer
 */

@interface SlowNetworkEdgeAverage : SlowNetworkCondition

+ (id)description;
+ (id)profileFriendlyName;

- (id)init;

@end
