/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriPlaybackControlSupport.framework/SiriPlaybackControlSupport
 */

@interface SiriPlaybackControlSupport.LocalizationProvider : _TtCs12_SwiftObject

@end
