/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKDumpIDSInfoRequest : CATTaskRequest

+ (Class)allowlistedClassForResultObject;
+ (bool)supportsSecureCoding;

@end
