/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherCore.framework/WeatherCore
 */

@interface WeatherCore.SevereNotificationsPowerLogger : _TtCs12_SwiftObject {
    void lastReportDate;
    void lazyNotificationStore;
}

@end
