/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherCore.framework/WeatherCore
 */

@interface WeatherCore.StubGeocodeStore : _TtCs12_SwiftObject {
    void locations;
    void lock;
}

@end
