/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherCore.framework/WeatherCore
 */

@interface WeatherCore.IdentificationService : _TtCs12_SwiftObject {
    void $__lazy_storage_$_encryptedStore;
    void $__lazy_storage_$_unencryptedStore;
    void appUpgradeKvsMigrator;
    void cache;
    void iCloudStatusProvider;
    void kvsProvider;
    void lazyEncryptedStore;
    void lazyUnencryptedStore;
    void lock;
    void notifyQueue;
    void observers;
}

@end
