/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Mercury.framework/Mercury
 */

@interface Mercury._XPCObjectDecoder : _TtCs12_SwiftObject {
    void codingPath;
    void topLevelObject;
    void underlyingConnection;
    void userInfo;
}

@end
