/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HomeKit.framework/HomeKit
 */

@interface HMHomeEventTopic : NSObject

+ (unsigned long long)suffixIDFromTopicSuffix:(id)arg1;
+ (id)topicFromSuffixID:(unsigned long long)arg1 homeUUID:(id)arg2;

@end
