/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WidgetKit.framework/WidgetKit
 */

@interface WidgetKit.CornerMonoClockComplicationFontDefinition : WidgetKit.CornerClockComplicationFontDefinition

@end
