/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriPrivateLearningAnalytics.framework/SiriPrivateLearningAnalytics
 */

@interface SiriPrivateLearningAnalytics.BiomeSignalReader : _TtCs12_SwiftObject {
    void queue;
    void reader;
    void subscriptions;
}

@end
