/* Generated by RuntimeBrowser.
 */

@protocol _SFDigitalHealthViewControllerDelegate <NSObject>

@optional

- (void)digitalHealthViewController:(_SFDigitalHealthViewController *)arg1 didFinishDismissingBlockingViewController:(STBlockingViewController *)arg2;

@end
