/* Generated by RuntimeBrowser.
 */

@protocol AVMobileChromelessControlsViewControllerDelegate <AVMobileControlsViewControllerDelegate>

@required

- (void)chromlessControlsViewControllerDidPressLiveTextButton:(AVMobileChromelessControlsViewController *)arg1;

@end
