/* Generated by RuntimeBrowser.
 */

@protocol BFMAsset <BFMResource>

@required

- (NSString *)artistName;
- (NSString *)artworkURL;
- (float)averageRating;
- (NSURL *)bookSampleDownloadURL;
- (NSString *)buyParams;
- (NSString *)contentRating;
- (NSDate *)expectedReleaseDate;
- (long long)fileSize;
- (NSString *)genre;
- (bool)hasSupplementalContent;
- (NSNumber *)height;
- (bool)isAudiobook;
- (bool)isBook;
- (bool)isExplicit;
- (bool)isPreorder;
- (bool)isSG;
- (NSString *)name;
- (NSDictionary *)offer;
- (NSString *)pageProgressionDirection;
- (NSURL *)previewURL;
- (NSNumber *)price;
- (NSString *)priceFormatted;
- (unsigned long long)ratingCount;
- (NSDate *)releaseDate;
- (NSString *)sequenceDisplayLabel;
- (NSNumber *)sequenceNumber;
- (NSString *)seriesName;
- (<BFMSeries> *)seriesResource;
- (NSString *)standardDescription;
- (NSString *)standardNotes;
- (NSURL *)url;
- (NSNumber *)width;

@end
