/* Generated by RuntimeBrowser.
 */

@protocol BLSRenderedFlipbookFrame <NSObject>

@required

- (float)apl;
- (float)aplDimming;
- (NSString *)bls_loggingString;
- (NSString *)bls_shortLoggingString;
- (<BLSPresentationDateSpecifying> *)bls_specifier;
- (unsigned long long)frameId;
- (unsigned long long)memoryUsage;
- (unsigned long long)presentationTime;
- (void)releaseSurface;
- (struct __IOSurface { }*)surface;

@end
