/* Generated by RuntimeBrowser.
 */

@protocol CAMSemanticStyleSliderDelegate <NSObject>

@required

- (void)sliderWillCollapse:(CAMSemanticStyleSlider *)arg1;
- (void)sliderWillExpand:(CAMSemanticStyleSlider *)arg1;

@end
