/* Generated by RuntimeBrowser.
 */

@protocol CNKScreenSharingStateObserving

@optional

- (void)screenSharingStateMonitor:(CNKScreenSharingStateMonitor *)arg1 didUpdateScreenSharingBroadcastingState:(bool)arg2;
- (void)screenSharingStateMonitor:(CNKScreenSharingStateMonitor *)arg1 didUpdateScreenSharingState:(bool)arg2;
- (void)screenSharingStateMonitorDidUpdateScreenInfoForParticipant:(CNKScreenSharingStateMonitor *)arg1;

@end
