/* Generated by RuntimeBrowser.
 */

@protocol COAlarmManagerServiceInterface <NSObject>

@required

- (void)addAlarm:(void *)arg1 forAccessoryUniqueIdentifier:(void *)arg2 categoryType:(void *)arg3 asInstance:(void *)arg4 cluster:(void *)arg5 withCallback:(void *)arg6; // needs 6 arg types, found 11: MTAlarm *, NSUUID *, NSString *, NSUUID *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)addObserverForNotificationName:(void *)arg1 constraints:(void *)arg2 asInstance:(void *)arg3 cluster:(void *)arg4 withCallback:(void *)arg5; // needs 5 arg types, found 10: NSString *, NSSet *, NSUUID *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)alarmsforAccessoryUniqueIdentifier:(void *)arg1 categoryType:(void *)arg2 asInstance:(void *)arg3 cluster:(void *)arg4 withCallback:(void *)arg5; // needs 5 arg types, found 11: NSUUID *, NSString *, NSUUID *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)canDispatchForAccessoryUniqueIdentifier:(void *)arg1 categoryType:(void *)arg2 asInstance:(void *)arg3 cluster:(void *)arg4 reply:(void *)arg5; // needs 5 arg types, found 10: NSUUID *, NSString *, NSUUID *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, void*
- (void)dismissAlarmWithIdentifier:(void *)arg1 cluster:(void *)arg2 withCallback:(void *)arg3; // needs 3 arg types, found 8: NSString *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)removeAlarm:(void *)arg1 forAccessoryUniqueIdentifier:(void *)arg2 categoryType:(void *)arg3 asInstance:(void *)arg4 cluster:(void *)arg5 withCallback:(void *)arg6; // needs 6 arg types, found 11: MTAlarm *, NSUUID *, NSString *, NSUUID *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)removeObserverForNotificationName:(void *)arg1 cluster:(void *)arg2 withCallback:(void *)arg3; // needs 3 arg types, found 8: NSString *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)snoozeAlarmWithIdentifier:(void *)arg1 cluster:(void *)arg2 withCallback:(void *)arg3; // needs 3 arg types, found 8: NSString *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)updateAlarm:(void *)arg1 forAccessoryUniqueIdentifier:(void *)arg2 categoryType:(void *)arg3 asInstance:(void *)arg4 cluster:(void *)arg5 withCallback:(void *)arg6; // needs 6 arg types, found 11: MTAlarm *, NSUUID *, NSString *, NSUUID *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*

@end
