/* Generated by RuntimeBrowser.
 */

@protocol COClusterRoleMonitorServiceInterface <NSObject>

@required

- (void)registerForMemberChangesWithRole:(COClusterRole *)arg1 inCluster:(NSString *)arg2;
- (void)registerForRoleChangesOfMember:(COClusterMember *)arg1 inCluster:(NSString *)arg2;
- (void)registerForSnapshotChangesInCluster:(NSString *)arg1;
- (void)unregisterForMemberChangesWithRole:(COClusterRole *)arg1 inCluster:(NSString *)arg2;
- (void)unregisterForRoleChangesOfMember:(COClusterMember *)arg1 inCluster:(NSString *)arg2;
- (void)unregisterForSnapshotChangesInCluster:(NSString *)arg1;

@end
