/* Generated by RuntimeBrowser.
 */

@protocol CoreAudioKit.CAAUViewParameterDataSource

@required

- (NSString *)accessibilityValueFor:(unsigned int)arg1;
- (const struct CGPath { }*)curveIn:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (float)maxValueFor:(unsigned int)arg1;
- (float)minValueFor:(unsigned int)arg1;
- (NSString *)nameFor:(unsigned int)arg1;
- (void)setWithParameter:(unsigned int)arg1 value:(float)arg2;
- (NSString *)shortNameFor:(unsigned int)arg1;
- (NSArray *)stringValuesFor:(unsigned int)arg1;
- (NSString *)unitLabelFor:(unsigned int)arg1;
- (float)valueFor:(unsigned int)arg1;
- (long long)widthTypeFor:(unsigned int)arg1;

@end
