/* Generated by RuntimeBrowser.
 */

@protocol CPFeatureFlags <NSObject>

@required

- (bool)autoGameCenterEnabled;
- (bool)expanseEnabled;
- (bool)expanseParticipantIDHashed;
- (bool)expanseTopicStateEnabled;
- (bool)mochiEnabled;
- (bool)newApplicationLauncherEnabled;
- (bool)qrPluginEncryptionEnabled;
- (bool)sharePlayLiteEnabled;
- (bool)unreliableMessengerEnabled;

@end
