/* Generated by RuntimeBrowser.
 */

@protocol CRTextFeaturesFiltering

@required

- (NSArray *)filterBlocks:(NSArray *)arg1 imageSize:(struct CGSize { double x1; double x2; })arg2;
- (NSArray *)filterFeatures:(NSArray *)arg1;

@end
