/* Generated by RuntimeBrowser.
 */

@protocol DNDSAppForegroundTriggerManagerDataSource <NSObject>

@required

- (DNDSAppForegroundTriggerConfiguration *)appForegroundTriggerConfigurationForAppForegroundTriggerManager:(DNDSAppForegroundTriggerManager *)arg1;

@end
