/* Generated by RuntimeBrowser.
 */

@protocol HMDMediaDestinationControllerLocalDataStorageHandler

@required

- (void)updateDestinationController:(HMMediaDestinationControllerData *)arg1;
- (void)updateDestinationControllerAvailableDestinationIdentifiers:(NSArray *)arg1;
- (void)updateDestinationControllerDestinationIdentifier:(NSUUID *)arg1;

@end
