/* Generated by RuntimeBrowser.
 */

@protocol HMDPrimaryResidentMessageRouterFactory <NSObject>

@required

- (HMDPrimaryResidentMessageRouter *)createPrimaryResidentMessageRouterWithMessageDispatcher:(HMFMessageDispatcher *)arg1 metricsDispatcher:(HMDPrimaryResidentMessageRouterMetricsDispatcher *)arg2;

@end
