/* Generated by RuntimeBrowser.
 */

@protocol HMMediaGroupsControllerDelegate_Deprecated <NSObject>

@optional

- (void)mediaGroupsController:(HMMediaGroupsController *)arg1 didCreateGroup:(HMMediaGroup *)arg2;
- (void)mediaGroupsController:(HMMediaGroupsController *)arg1 didUpdateGroup:(HMMediaGroup *)arg2;
- (void)mediaGroupsController:(HMMediaGroupsController *)arg1 didUpdateSettings:(HMAccessorySettings *)arg2 group:(HMMediaGroup *)arg3;

@end
