/* Generated by RuntimeBrowser.
 */

@protocol IDSLink <NSObject>

@required

- (<IDSLinkDelegate> *)alternateDelegate;
- (NSString *)cbuuid;
- (NSDictionary *)copyLinkStatsDict;
- (<IDSLinkDelegate> *)delegate;
- (NSString *)deviceUniqueID;
- (NSString *)generateLinkReport:(double)arg1 isCurrentLink:(bool)arg2;
- (unsigned long long)headerOverhead;
- (NSString *)linkTypeString;
- (unsigned long long)sendPacketBuffer:(struct { char *x1; unsigned long long x2; long long x3; long long x4; unsigned int x5; bool x6; bool x7; bool x8; bool x9; bool x10; bool x11; bool x12; bool x13; unsigned int x14; struct sockaddr_storage { unsigned char x_15_1_1; unsigned char x_15_1_2; BOOL x_15_1_3[6]; long long x_15_1_4; BOOL x_15_1_5[112]; } x15; struct sockaddr_storage { unsigned char x_16_1_1; unsigned char x_16_1_2; BOOL x_16_1_3[6]; long long x_16_1_4; BOOL x_16_1_5[112]; } x16; struct sockaddr_storage { unsigned char x_17_1_1; unsigned char x_17_1_2; BOOL x_17_1_3[6]; long long x_17_1_4; BOOL x_17_1_5[112]; } x17; unsigned short x18; unsigned char x19; int x20; struct { char *x_21_1_1; unsigned short x_21_1_2; int x_21_1_3; unsigned short x_21_1_4[12]; long long x_21_1_5; unsigned char x_21_1_6; unsigned short x_21_1_7; unsigned char x_21_1_8; bool x_21_1_9; bool x_21_1_10; unsigned short x_21_1_11; struct { unsigned short x_12_2_1; unsigned short x_12_2_2; unsigned short x_12_2_3; unsigned short x_12_2_4; unsigned short x_12_2_5; } x_21_1_12; bool x_21_1_13; bool x_21_1_14; int x_21_1_15; unsigned short x_21_1_16[4]; unsigned char x_21_1_17; bool x_21_1_18; bool x_21_1_19; bool x_21_1_20; unsigned int x_21_1_21; } x21[8]; }*)arg1 toDeviceUniqueID:(NSString *)arg2 cbuuid:(NSString *)arg3;
- (unsigned long long)sendPacketBufferArray:(struct { /* ? */ }**)arg1 arraySize:(int)arg2 toDeviceUniqueID:(NSString *)arg3 cbuuid:(NSString *)arg4;
- (void)setAlternateDelegate:(id <IDSLinkDelegate>)arg1;
- (void)setCbuuid:(NSString *)arg1;
- (void)setDelegate:(id <IDSLinkDelegate>)arg1;
- (void)setDeviceUniqueID:(NSString *)arg1;
- (unsigned long long)state;

@optional

- (void)start;

@end
