/* Generated by RuntimeBrowser.
 */

@protocol MKPOSTCertificateRouterDelegate <NSObject>

@required

- (void)router:(MKPOSTCertificateRouter *)arg1 didReceiveCertifciate:(MKCertificate *)arg2;

@end
