/* Generated by RuntimeBrowser.
 */

@protocol MPCQueueControllerDelegate <NSObject>

@required

- (void)queueController:(MPCQueueController *)arg1 didChangeActionAtQueueEnd:(long long)arg2;
- (void)queueController:(MPCQueueController *)arg1 didChangeContentsWithReplacementPlaybackContext:(MPPlaybackContext *)arg2;
- (void)queueController:(MPCQueueController *)arg1 didChangeRepeatType:(long long)arg2;
- (void)queueController:(MPCQueueController *)arg1 didChangeShuffleType:(long long)arg2;
- (void)queueController:(MPCQueueController *)arg1 didIncrementVersionForSegment:(NSString *)arg2;
- (void)queueController:(MPCQueueController *)arg1 failedToLoadItem:(MPAVItem *)arg2;
- (void)queueControllerDidChangeContents:(MPCQueueController *)arg1;

@end
