/* Generated by RuntimeBrowser.
 */

@protocol MREndpointObserver <NSObject>

@optional

- (void)endpointDidConnect:(MRAVEndpoint *)arg1;
- (void)endpointDidDisconnect:(MRAVEndpoint *)arg1;
- (void)endpointDidDisconnect:(MRAVEndpoint *)arg1 withError:(NSError *)arg2;

@end
