/* Generated by RuntimeBrowser.
 */

@protocol MSDStoreInfoListViewControllerDelegate <MSDStoreInfoViewControllerDelegate>

@required

- (void)listViewDidClose:(MSDStoreInfoListViewController *)arg1;

@end
