/* Generated by RuntimeBrowser.
 */

@protocol PKPaymentSetupAssistantContextProtocol <NSObject>

@required

- (NSData *)externalizedContext;
- (void)setExternalizedContext:(NSData *)arg1;
- (unsigned long long)setupAssistant;

@end
