/* Generated by RuntimeBrowser.
 */

@protocol SAUIElementViewProviding <SAElementViewProviding, SAUIElementLayoutAxisObserving>

@required

- (UIView *)leadingView;
- (UIView *)minimalView;
- (UIView *)trailingView;

@end
