/* Generated by RuntimeBrowser.
 */

@protocol SFActionableSecurityRecommendationDataDelegate <NSObject>

@required

- (void)actionableSecurityRecommendationDataDidUpdate:(SFActionableSecurityRecommendationData *)arg1;

@end
