/* Generated by RuntimeBrowser.
 */

@protocol SFUserReportRequest <NSObject>

@required

- (NSString *)affordanceText;
- (NSDictionary *)dictionaryRepresentation;
- (NSString *)dismissText;
- (NSData *)jsonData;
- (int)reportType;
- (void)setAffordanceText:(NSString *)arg1;
- (void)setDismissText:(NSString *)arg1;
- (void)setReportType:(int)arg1;
- (void)setTitle:(NSString *)arg1;
- (void)setUserReportOptions:(NSArray *)arg1;
- (NSString *)title;
- (NSArray *)userReportOptions;

@end
