/* Generated by RuntimeBrowser.
 */

@protocol WFUIEvent <NSObject>

@required

- (NSDictionary *)eventDictionary;
- (NSString *)eventName;
- (PBCodable<WFAWDWiFiUIEvent> *)metric;
- (unsigned int)metricIdentifier;

@end
