/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriContactsIntents.framework/SiriContactsIntents
 */

@interface SiriContactsIntents.ContactsAgeInfo : _TtCs12_SwiftObject {
    void age;
    void futureAge;
    void mockGlobals;
    void pastAge;
    void requestedYear;
}

@end
