/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriContactsIntents.framework/SiriContactsIntents
 */

@interface SiriContactsIntents.ContactService : _TtCs12_SwiftObject {
    void $__lazy_storage_$_contactStore;
    void cachedMeCard;
}

- (void)clearCachedMeCard;

@end
