/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CallKit.framework/CallKit
 */

@interface CXFeatures : NSObject

@property (getter=isChannelEnabled, nonatomic, readonly) bool channelEnabled;

- (bool)isChannelEnabled;

@end
