/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherMaps.framework/WeatherMaps
 */

@interface _TtCC11WeatherMaps27OverlayTileResourcesManagerP33_BE8AEB7348449D40BCBD22C50644102019ResourceHolderEntry : _TtCs12_SwiftObject {
    void interestedProcessors;
    void processors;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  state;
}

@end
