/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherMaps.framework/WeatherMaps
 */

@interface WeatherMaps.MapLocationAccessibilityModelFactory : _TtCs12_SwiftObject {
    void temperatureFormatter;
}

@end
