/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
 */

@interface AVCMediaStreamNegotiatorSettingsAirplayMirroring : AVCMediaStreamNegotiatorSettings {
    long long  _tilesPerFrame;
}

- (long long)captureSource;
- (id)initWithOptions:(id)arg1 deviceRole:(unsigned char)arg2 error:(id*)arg3;
- (int)operatingMode;
- (long long)tilesPerFrame;
- (long long)videoStreamMode;

@end
