/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DistributedEvaluation.framework/DistributedEvaluation
 */

@interface DESDPBitValueRecorder : NSObject <DESDPRecorderProtocol>

- (bool)record:(id)arg1 data:(id)arg2 metadata:(id)arg3;

@end
