/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface CNKAudioPowerSpectrumViewController : UIViewController {
    void $__lazy_storage_$_audioPowerSpectrumView;
    void $__lazy_storage_$_viewModel;
    void call;
    void hostingViewController;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end
