/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.SystemApertureIconFactory : _TtCs12_SwiftObject {
    void cachedIconSet;
}

@end
