/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.LinkShareCoordinator : NSObject <UIPopoverPresentationControllerDelegate> {
    void hostViewController;
    void originatingView;
    void shareSheetViewController;
    void type;
}

- (void).cxx_destruct;
- (id)init;

@end
