/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.NowPlayingMenuFactory : _TtCs12_SwiftObject {
    void commandCenter;
    void tracker;
}

@end
