/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.AppConfigurationRefreshManager : _TtCs12_SwiftObject {
    void appConfigurationManager;
    void refreshDeduper;
}

@end
