/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.PriceChangeDisplayCommandHandler : _TtCs12_SwiftObject {
    void tracker;
}

@end
