/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.TickerModule : _TtCs12_SwiftObject {
    void resolver;
    void tracker;
}

@end
