/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.WatchlistCellViewLayoutAttributesFactory : _TtCs12_SwiftObject {
    void cache;
    void styler;
}

@end
