/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.WelcomeViewStyler : _TtCs12_SwiftObject {
    void baseStyler;
    void parameters;
}

@end
