/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.AudioSeekCommandHandler : _TtCs12_SwiftObject {
    void audioPlaybackTracker;
    void playbackController;
}

@end
