/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.StockSparklineViewLayoutAttributesFactory : _TtCs12_SwiftObject {
    void styler;
    void valueCoordinateCalculator;
}

@end
