/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksUI.framework/StocksUI
 */

@interface StocksUI.ForYouFeedMastheadViewRenderer : _TtCs12_SwiftObject {
    void styler;
}

@end
