/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebBookmarks.framework/WebBookmarks
 */

@interface WebBookmarkProductionSafariCloudKitSyncTabCollection : WebBookmarkProductionSafariTabCollection

- (void)dealloc;

@end
