/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaAnalysisServices.framework/MediaAnalysisServices
 */

@interface MADServiceProxy : NSObject <VCPMediaAnalysisClientProtocol> {
    MADService * _service;
}

- (void).cxx_destruct;
- (id)initWithService:(id)arg1;
- (void)reportProgress:(double)arg1 forRequest:(int)arg2;

@end
