/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomePodSettings.framework/HomePodSettings
 */

@interface HomePodSettings.ProfileController : _TtCs12_SwiftObject <HomePodSettings.ProfileControllerXPCClientInterface> {
    void observedTargets;
    void profilesUpdatedHandler;
    void target;
    void xpc;
}

- (void)profilesChangedForLocalDeviceWithProfiles:(id)arg1;

@end
