/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ReminderKitInternal.framework/ReminderKitInternal
 */

@interface ReminderKitInternal.REMSuggestedAttributesFeatureExtractor : REMStoreSwiftInvocation

+ (bool)supportsSecureCoding;

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFetchResultTokenToDiffAgainst:(id)arg1;

@end
