/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DocumentManagerExecutables.framework/DocumentManagerExecutables
 */

@interface DOCSearchControllerUpdateRequest : NSObject {
    UISearchController * _searchController;
}

@property (retain) UISearchController *searchController;

- (void).cxx_destruct;
- (id)searchController;
- (void)setSearchController:(id)arg1;

@end
