/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MusicUI.framework/MusicUI
 */

@interface MusicUI.UserSocialProfileCoordinator : NSObject {
    void $__lazy_storage_$_socialServiceController;
    void _userSocialProfile;
    void isUserOnboarded;
    void lock;
    void objectGraph;
    void onFollowStateDidChange;
    void onPendingFollowRequestsDidChange;
    void onSocialOnboardingSharedPlaylistsHidden;
    void onUserOnboardedStatusHasChanged;
    void onUserProfileDidChange;
    void pendingUserSelectedPhotoData;
    void socialOnboardingFriendIDsToRequest;
    void socialOnboardingUserAttributes;
    void socialProfileSharedPlaylistIDsMap;
    void state;
    void userArtistFavoritesCache;
    void userNotificationSettings;
}

- (void).cxx_destruct;
- (id)init;

@end
