/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomePubSub.framework/BiomePubSub
 */

@interface BPSMulticast : BMBookmarkablePublisher <BPSConnectablePublisher> {
    id /* block */  _createSubject;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    <BPSSubject><BPSSubscriber> * _subject;
    <BPSPublisher> * _upstream;
}

@property (nonatomic, readonly) id /* block */ createSubject;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) <BPSPublisher> *upstream;

+ (id)publisherWithPublisher:(id)arg1 upstreams:(id)arg2 bookmarkState:(id)arg3;

- (void).cxx_destruct;
- (id)bookmarkableUpstreams;
- (bool)canStoreInternalStateInBookmark;
- (void)connect;
- (id /* block */)createSubject;
- (id)initWithUpstream:(id)arg1 createSubject:(id /* block */)arg2;
- (id)lazySubject;
- (void)subscribe:(id)arg1;
- (id)upstream;

@end
