/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthMedicationsDaemonPlugin.framework/HealthMedicationsDaemonPlugin
 */

@interface HDOntologyBasicDoseFormProvider : NSObject

+ (id)basicDoseFormsForConceptWithIdentifier:(id)arg1 ontologyTransaction:(id)arg2 error:(id*)arg3;

@end
