/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeStreams.framework/BiomeStreams
 */

@interface BMStreamSyncPolicy : NSObject {
    long long  _currentPlatform;
    NSDictionary * _policy;
    Class  _registeredEventClass;
}

@property (nonatomic, readonly) NSDictionary *policy;
@property (nonatomic, readonly) Class registeredEventClass;

- (void).cxx_destruct;
- (unsigned long long)directionsSupportedForTransport:(unsigned long long)arg1;
- (unsigned long long)directionsSupportedForTransport:(unsigned long long)arg1 fromPlatform:(long long)arg2;
- (id)init;
- (id)initWithPolicyDictionary:(id)arg1 eventClass:(Class)arg2;
- (id)policy;
- (Class)registeredEventClass;
- (bool)supportsSyncingWithPlatform:(long long)arg1 overTransport:(unsigned long long)arg2 inDirection:(unsigned long long)arg3;
- (bool)supportsSyncingWithPlatform:(long long)arg1 overTransport:(unsigned long long)arg2 inDirection:(unsigned long long)arg3 fromPlatform:(long long)arg4;
- (bool)supportsTransport:(unsigned long long)arg1 direction:(unsigned long long)arg2;
- (bool)supportsTransport:(unsigned long long)arg1 direction:(unsigned long long)arg2 fromPlatform:(long long)arg3;

@end
