/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDCloudManagerModelFailureEvent : HMMLogEvent <HMMCoreAnalyticsLogging> {
    NSNumber * _errorCode;
    NSString * _errorDomain;
    NSNumber * _failureCode;
    NSString * _model;
}

@property (nonatomic, readonly) NSString *accessoryIdentifier;
@property (readonly, copy) NSNumber *errorCode;
@property (readonly, copy) NSString *errorDomain;
@property (nonatomic, readonly) NSString *eventName;
@property (readonly, copy) NSNumber *failureCode;
@property (nonatomic, readonly) bool logEventWithAppendedCommonDimensions;
@property (readonly, copy) NSString *model;
@property (nonatomic, readonly) NSDictionary *serializedEvent;

- (void).cxx_destruct;
- (id)attributeDescriptions;
- (id)errorCode;
- (id)errorDomain;
- (id)eventName;
- (id)failureCode;
- (id)initWithModel:(id)arg1 failureCode:(unsigned long long)arg2 error:(id)arg3;
- (id)model;
- (id)serializedEvent;

@end
