/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDHAPMetricsReachabilityAddRemoveEvent : HMDHAPMetrics <HMMCoreAnalyticsLogging> {
    unsigned long long  _addRemoveEvent;
    NSNumber * _linkType;
}

@property (nonatomic, readonly) NSString *accessoryIdentifier;
@property (nonatomic, readonly) unsigned long long addRemoveEvent;
@property (nonatomic, readonly) NSString *eventName;
@property (nonatomic, readonly) NSNumber *linkType;
@property (nonatomic, readonly) bool logEventWithAppendedCommonDimensions;
@property (nonatomic, readonly) NSDictionary *serializedEvent;

- (void).cxx_destruct;
- (unsigned long long)addRemoveEvent;
- (id)eventName;
- (id)initWithAccessory:(id)arg1 hmdAddRemoveEvent:(unsigned long long)arg2 forLinkType:(id)arg3;
- (id)linkType;
- (id)serializedEvent;

@end
