/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDMotionSensorLogEvent : HMMHomeLogEvent <HMMCoreAnalyticsLogging> {
    NSString * _accessoryUUID;
    NSString * _characteristicUUID;
    NSString * _homePresence;
    NSString * _motionSensorStatus;
    NSString * _timeStamp;
}

@property (nonatomic, readonly) NSString *accessoryIdentifier;
@property (nonatomic, readonly, copy) NSString *accessoryUUID;
@property (nonatomic, readonly, copy) NSString *characteristicUUID;
@property (nonatomic, readonly) NSString *eventName;
@property (nonatomic, readonly, copy) NSString *homePresence;
@property (nonatomic, readonly) bool logEventWithAppendedCommonDimensions;
@property (nonatomic, readonly, copy) NSString *motionSensorStatus;
@property (nonatomic, readonly) NSDictionary *serializedEvent;
@property (nonatomic, readonly, copy) NSString *timeStamp;

- (void).cxx_destruct;
- (id)accessoryUUID;
- (id)characteristicUUID;
- (id)eventName;
- (id)homePresence;
- (id)initWithMotionSensorStatus:(id)arg1 accessoryUUID:(id)arg2 characteristicUUID:(id)arg3 timeStamp:(id)arg4 homeUUID:(id)arg5 homePresence:(id)arg6;
- (id)motionSensorStatus;
- (id)serializedEvent;
- (id)timeStamp;

@end
