/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDMultiUserSettingsLogEvent : HMMLogEvent <HMMCoreAnalyticsLogging> {
    HMMultiUserSettingsForMetrics * _multiUserSettings;
}

@property (nonatomic, readonly) NSString *accessoryIdentifier;
@property (nonatomic, readonly) NSString *eventName;
@property (nonatomic, readonly) bool logEventWithAppendedCommonDimensions;
@property (readonly, copy) HMMultiUserSettingsForMetrics *multiUserSettings;
@property (nonatomic, readonly) NSDictionary *serializedEvent;

- (void).cxx_destruct;
- (id)eventName;
- (id)initWithMultiUserSettings:(id)arg1;
- (id)multiUserSettings;
- (id)serializedEvent;

@end
