/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDUploadMaximumDelayLogEvent : HMMLogEvent

+ (id)uploadMaximumDelay;

@end
