/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDUnpairedHAPAccessoryConfiguration : NSObject {
    NSNumber * _chipFabricIndex;
    NSString * _isoCountryCode;
    HMDAccessoryNetworkCredential * _networkCredential;
    bool  _requiresUserConsent;
    NSString * _setupCode;
    id /* block */  _setupCodeProvider;
}

@property (copy) NSNumber *chipFabricIndex;
@property (copy) NSString *isoCountryCode;
@property (retain) HMDAccessoryNetworkCredential *networkCredential;
@property bool requiresUserConsent;
@property (copy) NSString *setupCode;
@property (copy) id /* block */ setupCodeProvider;

- (void).cxx_destruct;
- (id)chipFabricIndex;
- (id)isoCountryCode;
- (id)networkCredential;
- (bool)requiresUserConsent;
- (void)setChipFabricIndex:(id)arg1;
- (void)setIsoCountryCode:(id)arg1;
- (void)setNetworkCredential:(id)arg1;
- (void)setRequiresUserConsent:(bool)arg1;
- (void)setSetupCode:(id)arg1;
- (void)setSetupCodeProvider:(id /* block */)arg1;
- (id)setupCode;
- (id /* block */)setupCodeProvider;

@end
