/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface MKFNotificationRegistrationMediaPropertyDatabaseID : MKFNotificationRegistrationDatabaseID

@end
