/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSetup.framework/SiriSetup
 */

@interface SiriSetup.LocalDataSource : _TtCs12_SwiftObject {
    void siriEnabled;
    void siriVoice;
    void voiceTriggerDuringPhoneCallEnabled;
    void voiceTriggerEnabled;
}

@end
