/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsAnalytics.framework/NewsAnalytics
 */

@interface NewsAnalytics.NotificationReceiptReporter : _TtCs12_SwiftObject {
    void decoder;
    void log;
    void sessionManager;
    void sharedDefaults;
}

@end
