/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface _MPRemoteLaunchCommandCenter : MPRemoteCommandCenter

- (void)_scheduleSupportedCommandsChanged:(bool)arg1;
- (void)_startMediaRemoteSync;
- (void)_stopMediaRemoteSync;
- (void)dealloc;

@end
