/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksAnalytics.framework/StocksAnalytics
 */

@interface StocksAnalytics.TelemetrySessionManager : _TtCs12_SwiftObject {
    void networkEventSubscriber;
    void sessionManager;
    void sessionObserver;
    void sessionRestartingGroup;
}

@end
