/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionClient.framework/AppPredictionClient
 */

@interface ATXBiomeUIStream : ATXUniversalBiomeUIStream

- (id)deprecatedPublisherFromStartTime:(double)arg1;
- (void)donateUIEvent:(id)arg1;
- (id)publisherFromStartTime:(double)arg1;
- (id)publisherFromStartTime:(double)arg1 consumerSubType:(unsigned char)arg2;

@end
