/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionClient.framework/AppPredictionClient
 */

@interface ATXDefaultHomeScreenItemTilerGridSize5 : ATXDefaultHomeScreenItemTilerPodBuilder

- (bool)_addTwoSmallWidgets:(id)arg1;
- (bool)_shouldAllowAlternatePodTypeAsBackupForTilingBlueprint:(id)arg1;
- (id)_tilingBlueprint;
- (id)tiledHomeScreenItems;

@end
