/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionClient.framework/AppPredictionClient
 */

@interface ATXHomeScreenSuggestionClientGuardedData : NSObject {
    NSMutableDictionary * appPanelIdentifierToPageIndex;
    NSDictionary * currentAppPredictionPanelLayouts;
    NSString * currentBlendingCacheId;
    NSMutableArray * currentFallbacks;
    NSDictionary * currentStackSuggestions;
    NSDictionary * currentSuggestionWidgetLayouts;
    bool  isUserInteractingWithProactiveWidget;
    NSSet * knownHomeScreenProactiveWidgetUniqueIdsAtTimeOfBlending;
    NSSet * knownTodayPageProactiveWidgetUniqueIdsAtTimeOfBlending;
    NSObject<OS_dispatch_source> * layoutUpdateSuppressionTimer;
    ATXHomeScreenEventLogger * logger;
    NSHashTable * observers;
    NSMutableDictionary * pagesToUsedFallbackAppSuggestions;
    NSDictionary * previousSuggestedSuggestionWidgetLayouts;
    NSObject<OS_dispatch_source> * rotationSuppressionTimer;
    bool  shouldUpdateKnownHomeScreenWidgetUniqueIdsAtTimeOfBlending;
    bool  shouldUpdateKnownTodayPageWidgetUniqueIdsAtTimeOfBlending;
    NSMutableArray * stacksAffectedByDebugRotation;
    ATXInformationStore * store;
    ATXHomeScreenCachedSuggestions * suppressedSuggestions;
    ATXWidgetSuggestionDismissManager * widgetDismissManager;
}

- (void).cxx_destruct;

@end
