/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DiagnosticExtensionsDaemon.framework/DiagnosticExtensionsDaemon
 */

@interface DEDCloudKitExtensionsUtil : NSObject

+ (id)copyFiles:(id)arg1 toDirectory:(id)arg2;
+ (id)flattenDirectories:(id)arg1;
+ (id)getAllFilesInSessionDirectoryForSessionID:(id)arg1;
+ (id)getCompletedExtensionFromAllExtensions:(id)arg1;
+ (id)getVerifiedExtensionDirectoriesFromCompletedExtensions:(id)arg1 forSession:(id)arg2;
+ (void)updateELSSnapshotStatus:(unsigned long long)arg1;

@end
