/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestions.framework/SiriSuggestions
 */

@interface SiriSuggestions.DefaultSuggestionFactory : _TtCs12_SwiftObject

@end
