/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestions.framework/SiriSuggestions
 */

@interface SiriSuggestions.RankedCandidateSuggestion : _TtCs12_SwiftObject {
    void rankInfo;
    void result;
}

@end
