/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AuthenticationServicesCore.framework/AuthenticationServicesCore
 */

@interface ASCAuthorizationPresenterHostInterface : NSObject

+ (id)xpcInterface;

@end
