/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEEthernetTunnelProvider : NEPacketTunnelProvider

- (id)init;
- (void)setTunnelNetworkSettings:(id)arg1 completionHandler:(id /* block */)arg2;

@end
