/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PaymentUI.framework/PaymentUI
 */

@interface PaymentUI.PresentationContext : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _presenter;
}

@end
