/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriCarCommandsIntents.framework/SiriCarCommandsIntents
 */

@interface IntentCarDefrosterResolutionResult : INEnumResolutionResult

+ (id)confirmationRequiredWithIntentCarDefrosterToConfirm:(long long)arg1;
+ (id)successWithResolvedIntentCarDefroster:(long long)arg1;

@end
