/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MagnifierSupport.framework/MagnifierSupport
 */

@interface MagnifierSupport.RotationRateManager : _TtCs12_SwiftObject {
    void isStarted;
    void motionManager;
}

@end
