/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Portrait.framework/Portrait
 */

@interface PTEffectDebugLayer : NSObject {
    <MTLCommandQueue> * _commandQueue;
    <MTLDevice> * _device;
    <MTLTexture> * _disparityFixedFocus;
    PTEffectFilter * _disparityNormalFilter;
    PTEffectRelighting * _effectRelighting;
    float  _focusDepthFixed;
    <MTLBuffer> * _focusObject;
    int  _height;
    <MTLLibrary> * _library;
    PTMSRResize * _msrColorPyramid;
    PTRenderEffectNetwork * _network;
    PTOpticalFlow * _opticalFlow;
    <MTLPipelineLibrary> * _pipelineLibrary;
    PTColor * _portraitColor;
    <PTRenderState> * _renderState;
    PTUtil * _util;
    int  _width;
}

- (void).cxx_destruct;
- (id)initWithDevice:(id)arg1 library:(id)arg2 pipelineLibrary:(id)arg3 commandQueue:(id)arg4 effectRelighting:(id)arg5 disparityNormalFilter:(id)arg6 opticalFlow:(id)arg7 renderState:(id)arg8 util:(id)arg9 portraitColor:(id)arg10 msrColorPyramid:(id)arg11 network:(id)arg12 disparityFixedFocus:(id)arg13 focusDepthFixed:(float)arg14 focusObject:(id)arg15;
- (void)renderDebugInformation:(long long)arg1 renderRequest:(id)arg2 humanDetections:(id)arg3 transform:(struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })arg4;
- (void)renderDebugSubjectRelighting:(id)arg1 humanDetections:(id)arg2 renderRequest:(id)arg3 transform:(struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })arg4;
- (void)renderThumbnails:(id)arg1 defaults:(id)arg2 renderRequest:(id)arg3;

@end
