/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Portrait.framework/Portrait
 */

@interface PTMTLDropHints : NSObject {
    int  _count;
    bool  _enabled;
    NSString * _name;
    <MTLResourceGroupSPI> * _resourceGroup;
}

@property bool enabled;

- (void).cxx_destruct;
- (void)dropHintsFor:(id)arg1;
- (bool)enabled;
- (id)initWithDevice:(id)arg1 resources:(id)arg2 name:(id)arg3;
- (void)setDropHintsFor:(id)arg1;
- (void)setEnabled:(bool)arg1;

@end
