/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Portrait.framework/Portrait
 */

@interface PTNormalEstimation : NSObject {
    <MTLComputePipelineState> * _estimateNormalsFromDisparity;
}

- (void).cxx_destruct;
- (void)estimateNormalsFromDisparity:(id)arg1 inDiparity:(id)arg2 outNormal:(id)arg3 sensorWidth:(float)arg4 focalLength:(float)arg5;
- (id)initWithDevice:(id)arg1;

@end
