/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.UIKitContentScrollViewBridge : _TtCs12_SwiftObject {
    void lastSeed;
    void lastSeenEdges;
    void pendingScrollViews;
    void viewController;
}

@end
