/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRApplicationLauncherClusterLaunchAppParams : NSObject {
    MTRApplicationLauncherClusterApplication * _application;
    NSData * _data;
    NSNumber * _timedInvokeTimeoutMs;
}

@property (nonatomic, retain) MTRApplicationLauncherClusterApplication *application;
@property (nonatomic, retain) NSData *data;
@property (nonatomic, retain) NSNumber *timedInvokeTimeoutMs;

- (void).cxx_destruct;
- (id)application;
- (id)data;
- (id)description;
- (id)init;
- (void)setApplication:(id)arg1;
- (void)setData:(id)arg1;
- (void)setTimedInvokeTimeoutMs:(id)arg1;
- (id)timedInvokeTimeoutMs;

@end
