/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRChannelClusterChannelInfo : NSObject {
    NSString * _affiliateCallSign;
    NSString * _callSign;
    NSNumber * _majorNumber;
    NSNumber * _minorNumber;
    NSString * _name;
}

@property (nonatomic, retain) NSString *affiliateCallSign;
@property (nonatomic, retain) NSString *callSign;
@property (nonatomic, retain) NSNumber *majorNumber;
@property (nonatomic, retain) NSNumber *minorNumber;
@property (nonatomic, retain) NSString *name;

- (void).cxx_destruct;
- (id)affiliateCallSign;
- (id)callSign;
- (id)description;
- (id)init;
- (id)majorNumber;
- (id)minorNumber;
- (id)name;
- (void)setAffiliateCallSign:(id)arg1;
- (void)setCallSign:(id)arg1;
- (void)setMajorNumber:(id)arg1;
- (void)setMinorNumber:(id)arg1;
- (void)setName:(id)arg1;

@end
