/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRColorControlClusterMoveColorTemperatureParams : NSObject {
    NSNumber * _colorTemperatureMaximumMireds;
    NSNumber * _colorTemperatureMinimumMireds;
    NSNumber * _moveMode;
    NSNumber * _optionsMask;
    NSNumber * _optionsOverride;
    NSNumber * _rate;
    NSNumber * _timedInvokeTimeoutMs;
}

@property (nonatomic, retain) NSNumber *colorTemperatureMaximumMireds;
@property (nonatomic, retain) NSNumber *colorTemperatureMinimumMireds;
@property (nonatomic, retain) NSNumber *moveMode;
@property (nonatomic, retain) NSNumber *optionsMask;
@property (nonatomic, retain) NSNumber *optionsOverride;
@property (nonatomic, retain) NSNumber *rate;
@property (nonatomic, retain) NSNumber *timedInvokeTimeoutMs;

- (void).cxx_destruct;
- (id)colorTemperatureMaximumMireds;
- (id)colorTemperatureMinimumMireds;
- (id)description;
- (id)init;
- (id)moveMode;
- (id)optionsMask;
- (id)optionsOverride;
- (id)rate;
- (void)setColorTemperatureMaximumMireds:(id)arg1;
- (void)setColorTemperatureMinimumMireds:(id)arg1;
- (void)setMoveMode:(id)arg1;
- (void)setOptionsMask:(id)arg1;
- (void)setOptionsOverride:(id)arg1;
- (void)setRate:(id)arg1;
- (void)setTimedInvokeTimeoutMs:(id)arg1;
- (id)timedInvokeTimeoutMs;

@end
