/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRContentLauncherClusterLaunchContentParams : NSObject {
    NSNumber * _autoPlay;
    NSString * _data;
    MTRContentLauncherClusterContentSearch * _search;
    NSNumber * _timedInvokeTimeoutMs;
}

@property (nonatomic, retain) NSNumber *autoPlay;
@property (nonatomic, retain) NSString *data;
@property (nonatomic, retain) MTRContentLauncherClusterContentSearch *search;
@property (nonatomic, retain) NSNumber *timedInvokeTimeoutMs;

- (void).cxx_destruct;
- (id)autoPlay;
- (id)data;
- (id)description;
- (id)init;
- (id)search;
- (void)setAutoPlay:(id)arg1;
- (void)setData:(id)arg1;
- (void)setSearch:(id)arg1;
- (void)setTimedInvokeTimeoutMs:(id)arg1;
- (id)timedInvokeTimeoutMs;

@end
