/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRGroupKeyManagementClusterGroupKeyMapStruct : NSObject {
    NSNumber * _fabricIndex;
    NSNumber * _groupId;
    NSNumber * _groupKeySetID;
}

@property (nonatomic, retain) NSNumber *fabricIndex;
@property (nonatomic, retain) NSNumber *groupId;
@property (nonatomic, retain) NSNumber *groupKeySetID;

- (void).cxx_destruct;
- (id)description;
- (id)fabricIndex;
- (id)groupId;
- (id)groupKeySetID;
- (id)init;
- (void)setFabricIndex:(id)arg1;
- (void)setGroupId:(id)arg1;
- (void)setGroupKeySetID:(id)arg1;

@end
