/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRKeypadInputClusterSendKeyParams : NSObject {
    NSNumber * _keyCode;
    NSNumber * _timedInvokeTimeoutMs;
}

@property (nonatomic, retain) NSNumber *keyCode;
@property (nonatomic, retain) NSNumber *timedInvokeTimeoutMs;

- (void).cxx_destruct;
- (id)description;
- (id)init;
- (id)keyCode;
- (void)setKeyCode:(id)arg1;
- (void)setTimedInvokeTimeoutMs:(id)arg1;
- (id)timedInvokeTimeoutMs;

@end
