/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTROtaSoftwareUpdateRequestorClusterProviderLocation : NSObject {
    NSNumber * _endpoint;
    NSNumber * _fabricIndex;
    NSNumber * _providerNodeID;
}

@property (nonatomic, retain) NSNumber *endpoint;
@property (nonatomic, retain) NSNumber *fabricIndex;
@property (nonatomic, retain) NSNumber *providerNodeID;

- (void).cxx_destruct;
- (id)description;
- (id)endpoint;
- (id)fabricIndex;
- (id)init;
- (id)providerNodeID;
- (void)setEndpoint:(id)arg1;
- (void)setFabricIndex:(id)arg1;
- (void)setProviderNodeID:(id)arg1;

@end
