/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRTargetNavigatorClusterTargetInfo : NSObject {
    NSNumber * _identifier;
    NSString * _name;
}

@property (nonatomic, retain) NSNumber *identifier;
@property (nonatomic, retain) NSString *name;

- (void).cxx_destruct;
- (id)description;
- (id)identifier;
- (id)init;
- (id)name;
- (void)setIdentifier:(id)arg1;
- (void)setName:(id)arg1;

@end
