/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRWindowCoveringClusterGoToTiltPercentageParams : NSObject {
    NSNumber * _tiltPercent100thsValue;
    NSNumber * _timedInvokeTimeoutMs;
}

@property (nonatomic, retain) NSNumber *tiltPercent100thsValue;
@property (nonatomic, retain) NSNumber *timedInvokeTimeoutMs;

- (void).cxx_destruct;
- (id)description;
- (id)init;
- (void)setTiltPercent100thsValue:(id)arg1;
- (void)setTimedInvokeTimeoutMs:(id)arg1;
- (id)tiltPercent100thsValue;
- (id)timedInvokeTimeoutMs;

@end
