/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRWriteParams : NSObject {
    NSNumber * _dataVersion;
    NSNumber * _timedWriteTimeout;
}

@property (nonatomic, retain) NSNumber *dataVersion;
@property (nonatomic, retain) NSNumber *timedWriteTimeout;

- (void).cxx_destruct;
- (id)dataVersion;
- (id)init;
- (void)setDataVersion:(id)arg1;
- (void)setTimedWriteTimeout:(id)arg1;
- (id)timedWriteTimeout;

@end
