/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMTransientMessagePartChatItem : IMMessagePartChatItem

- (id)initWithGUID:(id)arg1;

@end
