/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemotePairingDevice.framework/RemotePairingDevice
 */

@interface RemotePairingDevice.NWConnectionControlChannelTransport : _TtCs12_SwiftObject {
    void _netlinkEndpoint;
    void _netlinkManager;
    void connection;
    void endpoint;
    void endpointHasBeenUpdatedSinceInitialization;
    void id;
    void interfaceIsProhibitedPredicate;
    void physicallyConnected;
}

@end
