/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface _TtGC16HealthExperience34FetchedResultsControllerDataSourceC18HealthPlatformCore8FeedItem_ : NSObject <NSFetchedResultsControllerDelegate> {
    void $__lazy_storage_$_identifier;
    void changesSubject;
    void eventHandler;
    void fetchedResultsController;
    void sections;
    void transactionState;
}

@property (nonatomic, readonly) NSString *description;

- (void).cxx_destruct;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1;
- (id)description;
- (id)init;

@end
