/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKComparisonOptionsValidator : CKPredicateValidatorInstance {
    unsigned long long  _options;
}

- (id)CKPropertiesDescription;
- (bool)validate:(id)arg1 error:(id*)arg2;

@end
