/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKOperationConfiguration : NSObject <NSCopying, NSSecureCoding> {
    NSDictionary * _additionalRequestHTTPHeaders;
    bool  _allowsCellularAccess;
    bool  _allowsExpensiveNetworkAccess;
    NSString * _applicationBundleIdentifierOverrideForContainerAccess;
    NSString * _applicationBundleIdentifierOverrideForNetworkAttribution;
    CKAssetDownloadStagingManager * _assetDownloadStagingManager;
    bool  _automaticallyRetryNetworkFailures;
    NSNumber * _cacheDeleteAvailableSpaceClass;
    CKContainer * _container;
    unsigned long long  _discretionaryNetworkBehavior;
    bool  _discretionarySchedulingForEntireOperation;
    bool  _hasAdditionalRequestHTTPHeaders;
    bool  _hasAllowsCellularAccess;
    bool  _hasAllowsExpensiveNetworkAccess;
    bool  _hasApplicationBundleIdentifierOverrideForContainerAccess;
    bool  _hasApplicationBundleIdentifierOverrideForNetworkAttribution;
    bool  _hasAssetDownloadStagingManager;
    bool  _hasAutomaticallyRetryNetworkFailures;
    bool  _hasCacheDeleteAvailableSpaceClass;
    bool  _hasContainer;
    bool  _hasDiscretionaryNetworkBehavior;
    bool  _hasDiscretionarySchedulingForEntireOperation;
    bool  _hasIsCloudKitSupportOperation;
    bool  _hasLongLived;
    bool  _hasPreferAnonymousRequests;
    bool  _hasQualityOfService;
    bool  _hasSchedulerActivity;
    bool  _hasSourceApplicationBundleIdentifier;
    bool  _hasSourceApplicationSecondaryIdentifier;
    bool  _hasTimeoutIntervalForRequest;
    bool  _hasTimeoutIntervalForResource;
    bool  _hasXPCActivity;
    bool  _hasXPCActivityAutomaticallyDefer;
    bool  _isCloudKitSupportOperation;
    bool  _longLived;
    bool  _preferAnonymousRequests;
    long long  _qualityOfService;
    CKSchedulerActivity * _schedulerActivity;
    NSString * _sourceApplicationBundleIdentifier;
    NSString * _sourceApplicationSecondaryIdentifier;
    double  _timeoutIntervalForRequest;
    double  _timeoutIntervalForResource;
    NSDictionary * _unitTestOverrides;
    NSObject<OS_xpc_object> * _xpcActivity;
    bool  _xpcActivityAutomaticallyDefer;
}

@property (nonatomic, copy) NSString *_sourceApplicationSecondaryIdentifier;
@property (nonatomic, copy) NSDictionary *additionalRequestHTTPHeaders;
@property (nonatomic) bool allowsCellularAccess;
@property (nonatomic) bool allowsExpensiveNetworkAccess;
@property (nonatomic, copy) NSString *applicationBundleIdentifierOverrideForContainerAccess;
@property (nonatomic, copy) NSString *applicationBundleIdentifierOverrideForNetworkAttribution;
@property (nonatomic, copy) CKAssetDownloadStagingManager *assetDownloadStagingManager;
@property (nonatomic) bool automaticallyRetryNetworkFailures;
@property (nonatomic, copy) NSNumber *cacheDeleteAvailableSpaceClass;
@property (nonatomic, retain) CKContainer *container;
@property (nonatomic) unsigned long long discretionaryNetworkBehavior;
@property (nonatomic) bool discretionarySchedulingForEntireOperation;
@property (nonatomic) bool hasAllowsExpensiveNetworkAccess;
@property (nonatomic) bool hasAutomaticallyRetryNetworkFailures;
@property (nonatomic) bool hasDiscretionaryNetworkBehavior;
@property (nonatomic) bool hasQualityOfService;
@property (nonatomic) bool isCloudKitSupportOperation;
@property (getter=isLongLived, nonatomic) bool longLived;
@property (nonatomic) bool preferAnonymousRequests;
@property (nonatomic) long long qualityOfService;
@property (nonatomic, copy) CKSchedulerActivity *schedulerActivity;
@property (nonatomic, copy) NSString *sourceApplicationBundleIdentifier;
@property (nonatomic, copy) NSString *sourceApplicationSecondaryIdentifier;
@property (nonatomic) double timeoutIntervalForRequest;
@property (nonatomic) double timeoutIntervalForResource;
@property (nonatomic, retain) NSDictionary *unitTestOverrides;
@property (nonatomic, retain) NSObject<OS_xpc_object> *xpcActivity;
@property (nonatomic) bool xpcActivityAutomaticallyDefer;

// Image: /System/Library/Frameworks/CloudKit.framework/CloudKit

+ (id)defaultConvenienceOperationConfiguration;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)CKDescriptionPropertiesWithPublic:(bool)arg1 private:(bool)arg2 shouldExpand:(bool)arg3;
- (id)_sourceApplicationSecondaryIdentifier;
- (void)addUnitTestOverrides:(id)arg1;
- (id)additionalRequestHTTPHeaders;
- (bool)allowsCellularAccess;
- (bool)allowsExpensiveNetworkAccess;
- (id)applicationBundleIdentifierOverrideForContainerAccess;
- (id)applicationBundleIdentifierOverrideForNetworkAttribution;
- (id)assetDownloadStagingManager;
- (bool)automaticallyRetryNetworkFailures;
- (id)cacheDeleteAvailableSpaceClass;
- (id)container;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (unsigned long long)discretionaryNetworkBehavior;
- (bool)discretionarySchedulingForEntireOperation;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasAllowsExpensiveNetworkAccess;
- (bool)hasAutomaticallyRetryNetworkFailures;
- (bool)hasDiscretionaryNetworkBehavior;
- (bool)hasQualityOfService;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isCloudKitSupportOperation;
- (bool)isLongLived;
- (bool)preferAnonymousRequests;
- (long long)qualityOfService;
- (void)removeUnitTestOverride:(id)arg1;
- (id)resolveAgainstGenericConfiguration:(id)arg1;
- (id)schedulerActivity;
- (void)setAdditionalRequestHTTPHeaders:(id)arg1;
- (void)setAllowsCellularAccess:(bool)arg1;
- (void)setAllowsExpensiveNetworkAccess:(bool)arg1;
- (void)setApplicationBundleIdentifierOverride:(id)arg1;
- (void)setApplicationBundleIdentifierOverrideForContainerAccess:(id)arg1;
- (void)setApplicationBundleIdentifierOverrideForNetworkAttribution:(id)arg1;
- (void)setAssetDownloadStagingManager:(id)arg1;
- (void)setAutomaticallyRetryNetworkFailures:(bool)arg1;
- (void)setCacheDeleteAvailableSpaceClass:(id)arg1;
- (void)setContainer:(id)arg1;
- (void)setDiscretionaryNetworkBehavior:(unsigned long long)arg1;
- (void)setDiscretionarySchedulingForEntireOperation:(bool)arg1;
- (void)setHasAllowsExpensiveNetworkAccess:(bool)arg1;
- (void)setHasAutomaticallyRetryNetworkFailures:(bool)arg1;
- (void)setHasDiscretionaryNetworkBehavior:(bool)arg1;
- (void)setHasQualityOfService:(bool)arg1;
- (void)setIsCloudKitSupportOperation:(bool)arg1;
- (void)setLongLived:(bool)arg1;
- (void)setPreferAnonymousRequests:(bool)arg1;
- (void)setQualityOfService:(long long)arg1;
- (void)setSchedulerActivity:(id)arg1;
- (void)setSourceApplicationBundleIdentifier:(id)arg1;
- (void)setSourceApplicationSecondaryIdentifier:(id)arg1;
- (void)setTimeoutIntervalForRequest:(double)arg1;
- (void)setTimeoutIntervalForResource:(double)arg1;
- (void)setUnitTestOverrides:(id)arg1;
- (void)setXpcActivity:(id)arg1;
- (void)setXpcActivityAutomaticallyDefer:(bool)arg1;
- (void)set_sourceApplicationSecondaryIdentifier:(id)arg1;
- (id)sourceApplicationBundleIdentifier;
- (id)sourceApplicationSecondaryIdentifier;
- (double)timeoutIntervalForRequest;
- (double)timeoutIntervalForResource;
- (id)unitTestOverrides;
- (id)xpcActivity;
- (bool)xpcActivityAutomaticallyDefer;

// Image: /System/Library/PrivateFrameworks/BookDataStore.framework/BookDataStore

+ (id)bds_defaultConfiguration;

// Image: /System/Library/PrivateFrameworks/IMDaemonCore.framework/IMDaemonCore

- (void)im_setActivity:(id)arg1;

@end
