/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FitnessCoachingServices.framework/FitnessCoachingServices
 */

@interface FitnessCoachingServices.NotificationRequestStore : _TtCs12_SwiftObject {
    void requestMap;
}

@end
