/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourUI.framework/SeymourUI
 */

@interface SeymourUI.SessionPresenter : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  activityTypeBehavior;
    void assetClient;
    void audioHintPresenter;
    void backgroundPresenter;
    void bufferPresenter;
    void castingPresenter;
    void catalogClient;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  catalogWorkout;
    void contentAvailabilityClient;
    void continueOnWatchPresenter;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  countdown;
    void display;
    void displayPreferencesPresenter;
    void eventHub;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  gymKitConnection;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  initiatedGroupActivity;
    void instructionsPresenter;
    void introSequencePresenter;
    void mediaPlayerPresenter;
    void mediaTagStringBuilder;
    void multiUserClient;
    void ongoingWorkoutDetectedPresenter;
    void orientationObserver;
    void overlayPresenter;
    void platform;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  playback;
    void presentationCoordinator;
    void remoteBrowsingSource;
    void routePickerPresenter;
    void sessionClient;
    void sessionEventPublisher;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  sessionOrigin;
    void sessionPowerLog;
    void standaloneWorkoutTimeProvider;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  startDate;
    void startTime;
    void state;
    void subscriptionToken;
    void summaryPresenter;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  termination;
    void timeline;
    void timerProvider;
    void unitPreferencesProvider;
    void watchConnectionState;
    void watchDiscoveryPresenter;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  workout;
}

@end
