/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourUI.framework/SeymourUI
 */

@interface SMUCompositing : NSObject

+ (id)kCAFilterColorBurnBlendMode;
+ (id)kCAFilterPlusD;
+ (id)kCAFilterPlusL;
+ (id)kCAFilterScreenBlendMode;
+ (id)kCAFilterSourceAtop;

@end
