/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriOntology.framework/SiriOntology
 */

@interface SiriOntology.UsoEntityBuilder_common_CompletionStatus : SiriOntology.UsoEntityBuilder

@end
