/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCCurrentFeaturedHeadlinesFetchOperation : FCOperation {
    <FCContentContext> * _context;
    id /* block */  _fetchCompletionHandler;
    NSArray * _resultHeadlines;
    <FCFeedTransforming> * _transformation;
    bool  _useFallbackArticleSource;
}

@property (nonatomic, copy) id /* block */ fetchCompletionHandler;

- (void).cxx_destruct;
- (id /* block */)fetchCompletionHandler;
- (id)init;
- (id)initWithContext:(id)arg1 transformation:(id)arg2;
- (id)initWithContext:(id)arg1 transformation:(id)arg2 useFallbackArticleSource:(bool)arg3;
- (void)operationWillFinishWithError:(id)arg1;
- (void)performOperation;
- (void)setFetchCompletionHandler:(id /* block */)arg1;
- (bool)validateOperation;

@end
