/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKPlayerActivityItemInternal : GKInternalRepresentation {
    long long  _activityType;
    NSString * _instrumentationKey;
    long long  _layoutType;
    NSString * _message;
    GKPlayerActivityRelationships * _relationships;
    NSDate * _timeStamp;
    NSString * _title;
}

@property (nonatomic) long long activityType;
@property (nonatomic, retain) NSString *instrumentationKey;
@property (nonatomic) long long layoutType;
@property (nonatomic, retain) NSString *message;
@property (nonatomic, retain) GKPlayerActivityRelationships *relationships;
@property (nonatomic, retain) NSDate *timeStamp;
@property (nonatomic, retain) NSString *title;

+ (id)constantToTypeMap;
+ (id)secureCodedPropertyKeys;
+ (id)typeToConstantMap;

- (void).cxx_destruct;
- (long long)activityType;
- (id)description;
- (id)initWithDictionary:(id)arg1;
- (id)instrumentationKey;
- (long long)layoutType;
- (id)message;
- (id)relationships;
- (void)setActivityType:(long long)arg1;
- (void)setInstrumentationKey:(id)arg1;
- (void)setLayoutType:(long long)arg1;
- (void)setMessage:(id)arg1;
- (void)setRelationships:(id)arg1;
- (void)setTimeStamp:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)timeStamp;
- (id)title;

@end
