/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceShortcutClient.framework/VoiceShortcutClient
 */

@interface _TtCO19VoiceShortcutClientP33_AF7300B6C9E30E4373285D89F83589AA17XPCEncoderStorage15XPCEncoderValue : _TtCs12_SwiftObject {
    void value;
}

@end
