/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceShortcutClient.framework/VoiceShortcutClient
 */

@interface WFContextualActionIcon : NSObject <NSSecureCoding> {
    NSString * _applicationBundleIdentifier;
    NSData * _imageData;
    NSString * _imageName;
    double  _imageScale;
    WFImage * _renderedImage;
    WFColor * _renderedSymbolBackgroundColor;
    NSString * _renderedSymbolSystemName;
    NSString * _systemName;
}

@property (nonatomic, readonly, copy) NSString *applicationBundleIdentifier;
@property (nonatomic, readonly) NSData *imageData;
@property (nonatomic, readonly, copy) NSString *imageName;
@property (nonatomic, readonly) double imageScale;
@property (nonatomic, readonly) WFImage *renderedImage;
@property (nonatomic, readonly) WFColor *renderedSymbolBackgroundColor;
@property (nonatomic, readonly, copy) NSString *renderedSymbolSystemName;
@property (nonatomic, readonly) NSString *systemName;
@property (nonatomic, readonly) WFIcon *wfIcon;

+ (id)iconWithApplicationBundleIdentifier:(id)arg1;
+ (id)iconWithImageData:(id)arg1 scale:(double)arg2;
+ (id)iconWithImageName:(id)arg1;
+ (id)iconWithRenderedSymbolOfSystemName:(id)arg1 backgroundColor:(id)arg2;
+ (id)iconWithSystemName:(id)arg1;
+ (id)imageNamed:(id)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)applicationBundleIdentifier;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)imageData;
- (id)imageName;
- (double)imageScale;
- (id)initWithApplicationBundleIdentifier:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithImageData:(id)arg1 scale:(double)arg2;
- (id)initWithImageName:(id)arg1;
- (id)initWithRenderedSymbolOfSystemName:(id)arg1 backgroundColor:(id)arg2;
- (id)initWithSystemName:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)renderedImage;
- (id)renderedSymbolBackgroundColor;
- (id)renderedSymbolSystemName;
- (id)systemName;
- (id)wfIcon;

@end
