/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceShortcutClient.framework/VoiceShortcutClient
 */

@interface WFSiriWorkflowRunnerClient : WFWorkflowRunnerClient <NSXPCListenerDelegate, WFSiriUIPresenterInterface> {
    NSXPCListener * _dialogRequestListener;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <WFSiriWorkflowRunnerClientDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSXPCListener *dialogRequestListener;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)dialogRequestListener;
- (void)executeIntent:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)executeLinkAction:(id)arg1 inApplication:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)executeLinkAction:(id)arg1 inApplication:(id)arg2 withNameOverride:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)handleUserActivityData:(id)arg1 withBundleIdentifier:(id)arg2 completionHandler:(id /* block */)arg3;
- (id)initWithAutoShortcutIdentifier:(id)arg1 action:(id)arg2 metadata:(id)arg3;
- (id)initWithWorkflowName:(id)arg1 executionContext:(long long)arg2 airPlayRouteIDs:(id)arg3;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)openApp:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)openInteractionInApp:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)openUrl:(id)arg1 withBundleIdentifier:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)punchOutRequestedWithCompletionHandler:(id /* block */)arg1;
- (void)showDialogRequest:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)speakTextWithUtterance:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)start;
- (void)stop;

@end
