/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKitUI.framework/ShazamKitUI
 */

@interface SHListeningMediaTimingFunctionProvider : NSObject

+ (id)inOutQuartMediaTimingFunction;
+ (id)inOutSineMediaTimingFunction;

@end
