/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BlastDoor.framework/BlastDoor
 */

@interface BlastDoor.BlastDoorService : _TtCs12_SwiftObject {
    void connection;
    void queue;
}

@end
