/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MessagesCloudSync.framework/MessagesCloudSync
 */

@interface MessagesCloudSync.TimeoutManager : _TtCs12_SwiftObject {
    void tasksMap;
}

@end
