/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriPlaybackControlIntents.framework/SiriPlaybackControlIntents
 */

@interface SiriPlaybackControlIntents.PauseMediaHandleIntentStrategy : _TtCs12_SwiftObject {
    void analyticsService;
    void deviceState;
    void dialogProvider;
    void featureFlagProvider;
    void patternProvider;
    void playbackController;
    void userDefaultsProvider;
}

@end
