/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriTTSService.framework/SiriTTSService
 */

@interface SiriTTSService.DelegateHandler : _TtCs12_SwiftObject {
    void delegate;
    void notificationCenter;
    void observers;
    void request;
}

@end
