/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriTTSService.framework/SiriTTSService
 */

@interface SiriTTSAudibleContext : NSObject <NSSecureCoding> {
    void audioSessionId;
    void didStartSpeaking;
    void immediate;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  siriRequestId;
}

@property (nonatomic) unsigned int audioSessionId;
@property (nonatomic, copy) id /* block */ didStartSpeaking;
@property (nonatomic) bool immediate;
@property (nonatomic, copy) NSUUID *siriRequestId;

+ (void)setSupportsSecureCoding:(bool)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (unsigned int)audioSessionId;
- (id /* block */)didStartSpeaking;
- (void)encodeWithCoder:(id)arg1;
- (bool)immediate;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)setAudioSessionId:(unsigned int)arg1;
- (void)setDidStartSpeaking:(id /* block */)arg1;
- (void)setImmediate:(bool)arg1;
- (void)setSiriRequestId:(id)arg1;
- (id)siriRequestId;

@end
