/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriTaskEngagement.framework/SiriTaskEngagement
 */

@interface SiriTaskEngagement.PSEFeatureStoreManager : _TtCs12_SwiftObject {
    void donators;
}

@end
