/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BrailleTranslation.framework/BrailleTranslation
 */

@interface BRLTUnicodePrintPreprocessor : NSObject <BRLTPrintPreprocessor>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id)preprocessPrintString:(id)arg1 withLocationMap:(id*)arg2;
- (id)preprocessPrintString:(id)arg1 withLocationMap:(id*)arg2 isEightDot:(bool)arg3;

@end
