/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppIntents.framework/AppIntents
 */

@interface AppIntents.AppManager : _TtCs12_SwiftObject {
    void $__lazy_storage_$_providedSystemActions;
    void $__lazy_storage_$_siriLanguageCode;
    void _appEntities;
    void _appEnums;
    void _appIntents;
    void _entityQueries;
    void _entityQueryMetadata;
    void bridges;
    void deferredOutputs;
    void hasFetchedStaticMetadata;
    void lock;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  logger;
    void viewActionsCount;
}

@end
