/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MusicKit.framework/MusicKit
 */

@interface MusicKit.ApplicationMusicPlayer : MusicKit.MusicPlayer {
    void _queue;
    void noisyQueueUpdateTimer;
    void playbackQueueObservationTask;
}

@end
