/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MusicKit.framework/MusicKit
 */

@interface MusicKit.ArtworkCatalogRegistry : _TtCs12_SwiftObject {
    void artworkCatalogs;
    void lock;
}

@end
