/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoUIServices.framework/ChronoUIServices
 */

@interface CHUISMutableWidgetSceneClientSettings : UIMutableApplicationSceneClientSettings

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
