/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUICore.framework/WorkflowUICore
 */

@interface WorkflowUICore.PreviewableContentCollection : _TtCs12_SwiftObject {
    void cachedListItems;
    void cachedThumbnailItems;
    void contentCollection;
}

@end
