/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInference.framework/SiriInference
 */

@interface SiriInference.SystemUserDefaultsProvider : _TtCs12_SwiftObject {
    void userDefaults;
}

@end
