/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.SportsDataServiceRequestFetcher : _TtCs12_SwiftObject {
    void authTokenManager;
    void callbackQueue;
    void connection;
    void jsonDecoder;
    void resourceService;
}

@end
