/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.EngagementBannerViewLayoutAttributesFactory : _TtCs12_SwiftObject {
    void layoutStore;
    void styler;
}

@end
