/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatIssueCoverNodeRenderer : _TtCs12_SwiftObject {
    void issueCoverViewRenderer;
}

@end
