/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatLayoutViewAnimation : _TtCs12_SwiftObject {
    void allLayers;
    void animationCompletion;
    void animationData;
    void animators;
    void identifier;
    void layer;
    void runModeRunner;
    void supplementaryLayers;
    void view;
}

@end
