/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.LayeredMediaLayerProcessorRequest : _TtCs12_SwiftObject {
    void assetHandle;
    void assetHandles;
    void cacheIdentifier;
    void scale;
    void size;
}

@end
