/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatPrintNode : _TtCs12_SwiftObject {
    void _identifier;
    void _values;
    void message;
}

@end
