/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatSwitchNodeCase : _TtCs12_SwiftObject {
    void _children;
    void expression;
}

@end
