/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.LayeredMediaViewModelFactory : _TtCs12_SwiftObject {
    void layerRenderableProvider;
}

@end
