/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariSharedUI.framework/SafariSharedUI
 */

@interface WBSWebExtensionAPIAlarmsObjC : WBSWebExtensionAPIObject {
    WBSWebExtensionAPIEventObjC * _onAlarm;
}

- (void).cxx_destruct;

@end
