/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TipsDaemon.framework/TipsDaemon
 */

@interface NotificationsClassifier : NSObject {
    MLModel * _model;
}

@property (nonatomic, readonly) MLModel *model;

+ (id)URLOfModelInThisBundle;
+ (void)loadContentsOfURL:(id)arg1 configuration:(id)arg2 completionHandler:(id /* block */)arg3;
+ (void)loadWithConfiguration:(id)arg1 completionHandler:(id /* block */)arg2;

- (void).cxx_destruct;
- (id)init;
- (id)initWithConfiguration:(id)arg1 error:(id*)arg2;
- (id)initWithContentsOfURL:(id)arg1 configuration:(id)arg2 error:(id*)arg3;
- (id)initWithContentsOfURL:(id)arg1 error:(id*)arg2;
- (id)initWithMLModel:(id)arg1;
- (id)model;
- (id)predictionFromFeatures:(id)arg1 error:(id*)arg2;
- (id)predictionFromFeatures:(id)arg1 options:(id)arg2 error:(id*)arg3;
- (id)predictionFrom_0:(double)arg1 _1:(double)arg2 _2:(double)arg3 _3:(double)arg4 _4:(double)arg5 _5:(double)arg6 _6:(double)arg7 _7:(double)arg8 _8:(double)arg9 _9:(double)arg10 _10:(double)arg11 _11:(double)arg12 _12:(double)arg13 _13:(double)arg14 _14:(double)arg15 _15:(double)arg16 _16:(double)arg17 _17:(double)arg18 _18:(double)arg19 _19:(double)arg20 _20:(double)arg21 _21:(double)arg22 _22:(double)arg23 _23:(double)arg24 _24:(double)arg25 _25:(double)arg26 _26:(double)arg27 _27:(double)arg28 _28:(double)arg29 _29:(double)arg30 _30:(double)arg31 _31:(double)arg32 _32:(double)arg33 _33:(double)arg34 _34:(double)arg35 error:(id*)arg36;
- (id)predictionsFromInputs:(id)arg1 options:(id)arg2 error:(id*)arg3;

@end
