/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKApplyActionExplanationViewController : PKApplyExplanationViewController

- (void)_configureAppleCardIcon;
- (void)_handleCancelTapped;
- (void)_terminateFlow;
- (void)_withdrawApplicationTapped;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;

@end
