/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPeerPaymentMessagesContentAmountEntryView : UIView {
    PKPeerPaymentMessagesMultiActionView * _actionView;
    PKPeerPaymentMessagesAmountStepperView * _amountStepperView;
    UILabel * _balanceLabel;
    UIView * _containerView;
    PKPeerPaymentMessagesNumberPadView * _numberPadView;
    bool  _usesAccessibilityLayout;
}

@property (nonatomic, readonly) PKPeerPaymentMessagesMultiActionView *actionView;
@property (nonatomic, readonly) PKPeerPaymentMessagesAmountStepperView *amountStepperView;
@property (nonatomic, readonly) UILabel *balanceLabel;
@property (nonatomic, readonly) PKPeerPaymentMessagesNumberPadView *numberPadView;

- (void).cxx_destruct;
- (bool)_isCompactUI;
- (bool)_useLargeLayout;
- (id)actionView;
- (id)amountStepperView;
- (id)balanceLabel;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (id)numberPadView;
- (void)setFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (void)traitCollectionDidChange:(id)arg1;

@end
