/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PreviewsOSSupport.framework/PreviewsOSSupport
 */

@interface PreviewsOSSupport.UVServiceHubPreviewService : NSObject <UVServiceHubService> {
    void invalidationHandle;
    void shellConnection;
}

+ (id)createAndReturnError:(id*)arg1;

- (void).cxx_destruct;
- (void)activateWithCompletion:(id /* block */)arg1;
- (void)cancel;
- (id)init;
- (void)observeCancelation:(id /* block */)arg1;

@end
