/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudKitDistributedSync.framework/CloudKitDistributedSync
 */

@interface CKXAtomBindingImplementationFormatVersionORC : CKXAtomBindingImplementation <CKXBinding>

- (id)init;
- (id)orcHelpers;

@end
