/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
 */

@interface _TtCOC8RemoteUI3RUI6LiftUI10XMLDecoder : _TtCs12_SwiftObject {
    void userInfo;
}

@end
