/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.CommonNetworkObservation : _TtCs12_SwiftObject {
    void body;
    void scheduler;
}

- (void)networkStateDidChange:(id)arg1;

@end
