/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.PageGridCache : _TtCs12_SwiftObject {
    void contentPageGrids;
    void supplementaryPageGrids;
}

@end
