/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.ComponentContainerCollectionElementsObserver : _TtCs12_SwiftObject {
    void impressionsCalculator;
    void parent;
    void presenter;
    void scrollObserver;
}

@end
