/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.AutomaticUpdates : _TtCs12_SwiftObject {
    void lastAreEnabledValue;
}

- (void)applicationWillEnterForegroundWithNotification:(id)arg1;

@end
