/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.TodayCardMediaAppEvent : AppStoreKitInternal.TodayCardMedia {
    void artwork;
    void blurStyle;
    void formattedDates;
    void subtitle;
    void tintColor;
}

@end
