/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.Trailers : _TtCs12_SwiftObject {
    void id;
    void mediaPlatform;
    void videos;
}

@end
