/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.OfferConfirmationAction : AppStoreKitInternal.Action {
    void buyAction;
    void confirmationAccessibilityAction;
    void confirmationInitiationAction;
}

@end
