/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.TodayCardMixedMediaRiverLockupOverlay : AppStoreKitInternal.TodayCardOverlay {
    void lockup;
}

@end
