/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SnippetUI.framework/SnippetUI
 */

@interface VRXTurnBasedInstrumentationEvent : VRXInstrumentationEvent

@property (nonatomic, readonly) bool requiresNewTurn;

- (void)emitWithTurnIdentifier:(id)arg1;
- (bool)requiresNewTurn;

@end
