/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVideoIntents.framework/SiriVideoIntents
 */

@interface SiriVideoIntents.AppSelectionResultAnalyticsLogger : _TtCs12_SwiftObject {
    void analyticsService;
    void getTrialIdentifiers;
}

@end
