/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactlessReaderUI.framework/ContactlessReaderUI
 */

@interface ContactlessReaderUI.MerchantCategoryDefinitions : _TtCs12_SwiftObject

@end
