/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoKit.framework/ChronoKit
 */

@interface ChronoKit.CHDMonotonicTimer : _TtCs12_SwiftObject {
    void interval;
    void invalidated;
    void lock;
    void time;
    void timer;
}

@end
