/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGGraphSocialGroupEdgeCollection : PGGraphEdgeCollection

+ (Class)edgeClass;

@end
