/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGHighlightTailorHighlightInfo : NSObject {
    bool  _babyIsPresent;
    NSArray * _childHighlights;
    CLSInvestigationPhotoKitFeeder * _feeder;
    <PGHighlightModel> * _highlight;
    PGGraphHighlightNode * _highlightNode;
    PGHighlightTailorContext * _highlightTailorContext;
    NSString * _keyAssetPrivateUUID;
    NSString * _keyAssetSharedUUID;
    NSSet * _meaningLabels;
    NSDictionary * _meaningLabelsByChildHighlightUUID;
    NSSet * _momentNodes;
    unsigned long long  _numberOfExtendedAssets;
    bool  _petIsPresent;
    double  _promotionScore;
    NSArray * _uuidsOfEligibleAssets;
}

@property (nonatomic, readonly) bool babyIsPresent;
@property (nonatomic, retain) NSArray *childHighlights;
@property (nonatomic, readonly) CLSInvestigationPhotoKitFeeder *feeder;
@property (nonatomic, readonly) <PGHighlightModel> *highlight;
@property (nonatomic, readonly) PGGraphHighlightNode *highlightNode;
@property (readonly) PGHighlightTailorContext *highlightTailorContext;
@property (nonatomic, copy) NSString *keyAssetPrivateUUID;
@property (nonatomic, copy) NSString *keyAssetSharedUUID;
@property (nonatomic, retain) NSSet *meaningLabels;
@property (nonatomic, readonly) NSDictionary *meaningLabelsByChildHighlightUUID;
@property (nonatomic, readonly) NSSet *momentNodes;
@property (nonatomic) unsigned long long numberOfExtendedAssets;
@property (nonatomic, readonly) bool petIsPresent;
@property (nonatomic) double promotionScore;
@property (nonatomic, retain) NSArray *uuidsOfEligibleAssets;

- (void).cxx_destruct;
- (id)assetsForSharingFilter:(unsigned short)arg1;
- (bool)babyIsPresent;
- (id)childHighlights;
- (id)description;
- (id)feeder;
- (id)highlight;
- (id)highlightNode;
- (id)highlightTailorContext;
- (id)initForTestingWithHighlight:(id)arg1;
- (id)initWithHighlight:(id)arg1 graph:(id)arg2 highlightTailorContext:(id)arg3;
- (id)keyAssetPrivateUUID;
- (id)keyAssetSharedUUID;
- (id)meaningLabels;
- (id)meaningLabelsByChildHighlightUUID;
- (id)momentNodes;
- (unsigned long long)numberOfExtendedAssets;
- (bool)petIsPresent;
- (double)promotionScore;
- (void)setChildHighlights:(id)arg1;
- (void)setKeyAssetPrivateUUID:(id)arg1;
- (void)setKeyAssetSharedUUID:(id)arg1;
- (void)setMeaningLabels:(id)arg1;
- (void)setNumberOfExtendedAssets:(unsigned long long)arg1;
- (void)setPromotionScore:(double)arg1;
- (void)setUuidsOfEligibleAssets:(id)arg1;
- (id)uuidsOfEligibleAssets;
- (id)uuidsOfRequiredAssetsForSharingFilter:(unsigned short)arg1;

@end
