/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGInvariantMyFriendMemoryNodeFeatureExtractor : PGGraphMemoryNodeFeatureExtractor

- (id)initWithError:(id*)arg1;

@end
