/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGWallpaperSuggestionInformer : NSObject {
    PGManagerWorkingContext * _workingContext;
}

- (void).cxx_destruct;
- (id)initWithWorkingContext:(id)arg1;
- (id)personLocalIdentifiersForTopPeople:(bool)arg1;

@end
