/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PhotosGraph.PGSharedLibrarySimulationEvent : _TtCs12_SwiftObject {
    void asset;
    void assetIsCurrentlyInSharedLibrary;
    void capturedSharedLibraryMode;
    void dateFormatter;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  mdataFilePath;
    void name;
    void photoLibrary;
    void photosChallengeInferredSuggestsSharing;
    void sharedLibraryDiagnostics;
}

@end
