/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PhotosGraph.PhotosChallengeEvaluableAlgorithmMayDay : PhotosGraph.PhotosChallengeEvaluableHolidayAlgorithm

@end
