/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariCore.framework/SafariCore
 */

@interface WBSPasswordBreachSettings : NSObject

+ (bool)isPasswordBreachDetectionEnabled;
+ (void)setPasswordBreachDetectionEnabled:(bool)arg1;

@end
