/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAutomationInternal.framework/HomeAutomationInternal
 */

@interface HomeAutomationInternal.NativeZone : HomeAutomationInternal.NativeEntity {
    void delegate;
}

@end
