/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriCorrections.framework/SiriCorrections
 */

@interface SiriCorrections.ReferenceResolutionUtils : _TtCs12_SwiftObject

@end
