/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VisualIntelligence.framework/VisualIntelligence
 */

@interface VisualIntelligence.RegionSelectionProcessor : _TtCs12_SwiftObject {
    void ontologyGraph;
}

@end
