/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VisualIntelligence.framework/VisualIntelligence
 */

@interface VisualIntelligence.NSFWNode : _TtCs12_SwiftObject {
    void inputLabels;
    void outputLabels;
    void parseFlow;
}

@end
