/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VisualIntelligence.framework/VisualIntelligence
 */

@interface VisualIntelligence.S2EdgeIndex : _TtCs12_SwiftObject {
    void cells;
    void edges;
    void isIndexComputed;
    void minimumS2LevelUsed;
    void queryCount;
}

@end
