/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface WebScriptObjectPrivate : NSObject {
    void * imp;
    bool  isCreatedByDOMWrapper;
    void * originRootObject;
    void * rootObject;
}

@end
