/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI
 */

@interface GameCenterUI.ActivityFeedErrorDashboardSection : GameCenterUI.DashboardSections {
    void game;
}

@end
