/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI
 */

@interface GameCenterUI.GameLayerAchievementsPresenter : _TtCs12_SwiftObject {
    void achievementIdsToHighlight;
    void combinedAchievementsGrid;
    void data;
    void entryPoint;
    void gameCenterDataUpdatePresenter;
    void gameRecord;
    void highlightCompletedAchievements;
    void isUpdating;
    void listHeaderStyle;
    void onApplySnapshot;
    void onUpdatePhaseChange;
    void sectionHeaderStyle;
}

@end
