/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VisageHRTF.framework/VisageHRTF
 */

@interface VGExpressionIsBlinkFilter : VGExpressionFilter

- (float)filter:(id)arg1;

@end
