/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosFormats.framework/PhotosFormats
 */

@interface PFStoryRecipeDisplayAssetFactory : NSObject

+ (id)createAssetWithCategory:(long long)arg1 scheme:(id)arg2 cloudIdentifier:(id)arg3;

@end
