/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeLibrary.framework/BiomeLibrary
 */

@interface _BMContextSyncLibraryNode : _BMLibraryNode

+ (id)LOI;
+ (id)configurationForLOI;
+ (id)identifier;
+ (id)storeConfigurationForLOI;
+ (id)streamNames;
+ (id)streamWithName:(id)arg1;
+ (id)sublibraries;
+ (id)syncPolicyForLOI;
+ (id)validKeyPaths;

@end
