/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WallpaperKit.framework/WallpaperKit
 */

@interface WKSpringBoardMigrationInputSource : NSObject <WKWallpaperInputSource> {
    NSMutableDictionary * __wallpaperBokehVariantLookup;
    NSMutableDictionary * __wallpaperColorLookup;
    NSMutableDictionary * __wallpaperImageLookup;
    NSMutableDictionary * __wallpaperOptionsLookup;
    NSMutableDictionary * __wallpaperOriginalImageLookup;
    NSMutableDictionary * __wallpaperOriginalVideoURLLookup;
    NSMutableDictionary * __wallpaperVideoURLLookup;
    bool  _homeScreenIsAppearanceAware;
    bool  _homeScreenIsSystemContent;
    bool  _homeScreenMirrorsLockScreen;
    unsigned long long  _homeScreenWallpaperType;
    bool  _lockScreenIsAppearanceAware;
    bool  _lockScreenIsSystemContent;
    unsigned long long  _lockScreenWallpaperType;
}

@property (nonatomic, retain) NSMutableDictionary *_wallpaperBokehVariantLookup;
@property (nonatomic, retain) NSMutableDictionary *_wallpaperColorLookup;
@property (nonatomic, retain) NSMutableDictionary *_wallpaperImageLookup;
@property (nonatomic, retain) NSMutableDictionary *_wallpaperOptionsLookup;
@property (nonatomic, retain) NSMutableDictionary *_wallpaperOriginalImageLookup;
@property (nonatomic, retain) NSMutableDictionary *_wallpaperOriginalVideoURLLookup;
@property (nonatomic, retain) NSMutableDictionary *_wallpaperVideoURLLookup;
@property (getter=isHomeScreenIsAppearanceAware, nonatomic, readonly) bool homeScreenIsAppearanceAware;
@property (getter=isHomeScreenIsSystemContent, nonatomic, readonly) bool homeScreenIsSystemContent;
@property (nonatomic, readonly) bool homeScreenMirrorsLockScreen;
@property (nonatomic, readonly) unsigned long long homeScreenWallpaperType;
@property (getter=isLockScreenIsAppearanceAware, nonatomic, readonly) bool lockScreenIsAppearanceAware;
@property (getter=isLockScreenIsSystemContent, nonatomic, readonly) bool lockScreenIsSystemContent;
@property (nonatomic, readonly) unsigned long long lockScreenWallpaperType;

- (void).cxx_destruct;
- (bool)_isAppearanceAwareWallpaperAtLocation:(id)arg1 withConfigurationManager:(id)arg2;
- (bool)_isWallpaperConfigurationAppleSystemContent:(id)arg1;
- (void)_populateMigrationInputWithConfigurationManager:(id)arg1;
- (id)_wallpaperBokehVariantLookup;
- (id)_wallpaperColorLookup;
- (id)_wallpaperImageLookup;
- (id)_wallpaperOptionsLookup;
- (id)_wallpaperOriginalImageLookup;
- (id)_wallpaperOriginalVideoURLLookup;
- (id)_wallpaperVideoURLLookup;
- (id)bokehVariantForLocation:(id)arg1;
- (bool)homeScreenMirrorsLockScreen;
- (unsigned long long)homeScreenWallpaperType;
- (id)initWithConfigurationManager:(id)arg1;
- (bool)isAppearanceWallpaperAtLocation:(id)arg1;
- (bool)isHomeScreenIsAppearanceAware;
- (bool)isHomeScreenIsSystemContent;
- (bool)isLockScreenIsAppearanceAware;
- (bool)isLockScreenIsSystemContent;
- (unsigned long long)lockScreenWallpaperType;
- (void)set_wallpaperBokehVariantLookup:(id)arg1;
- (void)set_wallpaperColorLookup:(id)arg1;
- (void)set_wallpaperImageLookup:(id)arg1;
- (void)set_wallpaperOptionsLookup:(id)arg1;
- (void)set_wallpaperOriginalImageLookup:(id)arg1;
- (void)set_wallpaperOriginalVideoURLLookup:(id)arg1;
- (void)set_wallpaperVideoURLLookup:(id)arg1;
- (id)wallpaperColorForLocation:(id)arg1;
- (id)wallpaperImageForLocation:(id)arg1 wallpaperAppearance:(id)arg2;
- (id)wallpaperOptionsForLocation:(id)arg1 wallpaperAppearance:(id)arg2;
- (id)wallpaperOriginalImageForLocation:(id)arg1 wallpaperAppearance:(id)arg2;
- (id)wallpaperOriginalVideoURLForLocation:(id)arg1 wallpaperAppearance:(id)arg2;
- (unsigned long long)wallpaperTypeForLocation:(id)arg1;
- (id)wallpaperVideoURLForLocation:(id)arg1 wallpaperAppearance:(id)arg2;

@end
