/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInferredHelpfulness.framework/SiriInferredHelpfulness
 */

@interface SiriInferredHelpfulness.FeaturedTurn : _TtCs12_SwiftObject {
    void conversationID;
    void features;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  requestID;
    void timestamp;
    void turnID;
}

@end
