/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKit.framework/NanoTimeKit
 */

@interface NTKCWhistlerSubdialsFacesGalleryCollection : NTKDeviceSpecificFacesArrayGalleryCollection

- (id)facesForDevice:(id)arg1;
- (id)title;

@end
