/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKit.framework/NanoTimeKit
 */

@interface NTKCFaceDetailKaleidoscopeStyleSectionController : NTKCFaceDetailEditOptionHorizontalSectionController

+ (bool)hasSectionForFace:(id)arg1 forEditMode:(long long)arg2;

- (void)faceDidChangeResourceDirectory;

@end
