/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKit.framework/NanoTimeKit
 */

@interface NTKPaletteColorEditOption : NTKEnumeratedEditOption <NTKPigmentEditOptionConvertible>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long paletteColor;
@property (readonly) Class superclass;

+ (id)__orderedValuesForDevice:(id)arg1;
+ (id)_orderedValuesForDevice:(id)arg1;
+ (id)_orderedValuesRestrictedByDevice:(id)arg1;
+ (id)_snapshotKeyForValue:(unsigned long long)arg1 forDevice:(id)arg2;
+ (void)colorName:(id*)arg1 collectionName:(id*)arg2 forColorValue:(unsigned long long)arg3;
+ (id)colorNameForColorValue:(unsigned long long)arg1;
+ (unsigned long long)colorValueForColorName:(id)arg1;
+ (id)optionByValidatingValueOfInvalidOption:(id)arg1;
+ (id)optionWithPaletteColor:(unsigned long long)arg1 forDevice:(id)arg2;

- (id)_valueToFaceBundleStringDict;
- (id)localizedName;
- (bool)optionExistsInDevice:(id)arg1;
- (unsigned long long)paletteColor;
- (id)pigmentEditOption;
- (long long)swatchStyle;

@end
