/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKit.framework/NanoTimeKit
 */

@interface NTKSalmonColorEditOption : NTKCuratedColorEditOption <NTKPigmentEditOptionConvertible>

@property (nonatomic, readonly) unsigned long long color;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)_orderedValuesForDevice:(id)arg1;
+ (id)curatedColorValuesForDevice:(id)arg1;
+ (id)domain;
+ (id)optionWithColor:(unsigned long long)arg1 forDevice:(id)arg2;

- (unsigned long long)color;
- (id)localizedName;
- (id)pigmentEditOption;

@end
