/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKit.framework/NanoTimeKit
 */

@interface NTKSolarRichComplicationCircularView : NTKSolarRichComplicationBaseCircularView

+ (bool)supportsComplicationFamily:(long long)arg1;

- (id)init;

@end
