/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKit.framework/NanoTimeKit
 */

@interface NTKWorldClockRichComplicationHandsView : NTKWorldClockRichComplicationHandsBaseView

- (long long)complicationFamily;

@end
