/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IconServices.framework/IconServices
 */

@interface ISCurrentDeviceIcon : ISTypeIcon

+ (id)sharedInstance;

- (id)init;

@end
