/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IconServices.framework/IconServices
 */

@interface ISEmbossedSmartFolder 

// Image: /System/Library/PrivateFrameworks/IconServices.framework/IconServices

- (unsigned long long)embossVariant;
- (id)folderResourceName;

// Image: /usr/lib/libobjc.A.dylib

+ (void)initialize;

@end
