/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BusinessServicesUI.framework/BusinessServicesUI
 */

@interface BSUIBrandManager : BSBrandManager

- (id)initWithCachingEnabled:(bool)arg1;
- (id)initWithCachingEnabled:(bool)arg1 cacheURL:(id)arg2;

@end
