/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PaperKit.framework/PaperKit
 */

@interface _TtCC8PaperKit13ImageRenderer7Context : _TtCs12_SwiftObject {
    void cgContext;
    void size;
}

@end
