/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PaperKit.framework/PaperKit
 */

@interface PaperKit.StrokeWidthViewController : PaperKit.ValueEditingViewController

- (bool)_canShowWhileLocked;
- (id)initWithCoder:(id)arg1;
- (void)viewDidLoad;

@end
