/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNSimulatedLocationGenerator : NSObject {
    unsigned long long  _currentLegIndex;
    double  _currentTime;
    bool  _endAtFinalDestination;
    bool  _isChinaShifted;
    MNLocation * _lastLocation;
    struct { 
        unsigned int index; 
        float offset; 
    }  _lastRouteCoordinate;
    MNActiveRouteInfo * _routeInfo;
    double  _speedOverride;
    double  _startWaitingTime;
    long long  _state;
}

@property (nonatomic) bool endAtFinalDestination;
@property (nonatomic, readonly) MNLocation *lastLocation;
@property (nonatomic, readonly) struct { unsigned int x1; float x2; } lastRouteCoordinate;
@property (nonatomic) double speedOverride;
@property (nonatomic, readonly) long long state;

- (void).cxx_destruct;
- (double)_courseFromCoordinate:(struct { double x1; double x2; double x3; })arg1 toCoordinate:(struct { double x1; double x2; double x3; })arg2;
- (bool)_isCoordinate:(struct { unsigned int x1; float x2; })arg1 atEndOfLeg:(id)arg2;
- (id)_locationWithCoordinate:(struct { double x1; double x2; double x3; })arg1 course:(double)arg2 speed:(double)arg3;
- (struct { double x1; double x2; double x3; })_projectedCoordinateOffRouteFrom:(struct { double x1; double x2; double x3; })arg1 toCoordinate:(struct { double x1; double x2; double x3; })arg2 overTimeDelta:(double)arg3 outCourse:(out double*)arg4 outSpeed:(out double*)arg5;
- (struct { unsigned int x1; float x2; })_projectedCoordinateOnRouteFrom:(struct { unsigned int x1; float x2; })arg1 overTimeDelta:(double)arg2 outSpeed:(out double*)arg3;
- (bool)_shouldProceedToWaypointForLeg:(id)arg1;
- (struct { unsigned int x1; float x2; })_simulationStartRouteCoordinate;
- (struct { double x1; double x2; double x3; })_updateForFollowingRouteOverTimeDelta:(double)arg1 outCourse:(out double*)arg2 outSpeed:(out double*)arg3;
- (struct { double x1; double x2; double x3; })_updateForProceedingToStartOfLegOverTimeDelta:(double)arg1 outCourse:(out double*)arg2 outSpeed:(out double*)arg3;
- (struct { double x1; double x2; double x3; })_updateForProceedingToWaypointOverTimeDelta:(double)arg1 outCourse:(out double*)arg2 outSpeed:(out double*)arg3;
- (struct { double x1; double x2; double x3; })_updateForWaitingAtWaypointOverTimeDelta:(double)arg1 outCourse:(out double*)arg2 outSpeed:(out double*)arg3;
- (void)_updateStartState;
- (bool)endAtFinalDestination;
- (id)initWithRouteInfo:(id)arg1;
- (id)lastLocation;
- (struct { unsigned int x1; float x2; })lastRouteCoordinate;
- (id)nextSimulatedLocationWithElapsedTime:(double)arg1;
- (void)setEndAtFinalDestination:(bool)arg1;
- (void)setSpeedOverride:(double)arg1;
- (double)speedOverride;
- (long long)state;
- (id)stringForState:(long long)arg1;
- (void)updatePosition:(double)arg1;
- (void)updateWithRouteInfo:(id)arg1;

@end
