/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
 */

@interface NPKRemotePassActionUIServicePresenterInterface : NSObject

+ (id)interface;

@end
