/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
 */

@interface NPKUserNotificationExpressModeEnabled : NPKPassUserNotification

- (id)body;
- (id)initWithPass:(id)arg1;
- (id)notificationCategoryIdentifier;
- (id)title;
- (id)userInfo;
- (bool)wantsBadgedIcon;

@end
