/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSpeechSynthesis.framework/SiriSpeechSynthesis
 */

@interface QSSMutablePronunciation : QSSPronunciation

@property (nonatomic, copy) NSString *phonemes;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (id)phonemes;
- (void)setPhonemes:(id)arg1;

@end
