/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SwiftNN.framework/SwiftNN
 */

@interface _TtCC7SwiftNN13MLCGraphCache13OperationNode : _TtCs12_SwiftObject {
    void descriptor;
}

@end
