/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SwiftNN.framework/SwiftNN
 */

@interface SwiftNN.Conv2D : _TtCs12_SwiftObject {
    void _bias;
    void _isEveryParameterInitialized;
    void _weight;
    void backendModuleState;
    void dilations;
    void filterCount;
    void groupCount;
    void kernelSize;
    void padding;
    void strides;
}

@end
