/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUIApps.framework/PhotosUIApps
 */

@interface PhotosUIApps.PUXStoryColorGradeEditorLayoutSpecManager : PXFeatureSpecManager

- (id)createSpec;
- (id)initWithExtendedTraitCollection:(id)arg1 options:(unsigned long long)arg2;
- (Class)specClass;

@end
