/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXGRadialMotionBlurEffect : PXGMotionBlurEffect {
    PXGPolarBlurKernel * _polarBlur;
}

- (void).cxx_destruct;
- (id)kernel;

@end
