/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXSearchZeroKeywordPlaceViewModel : PXSearchZeroKeywordBaseViewModel

- (id)initWithTitle:(id)arg1 representedObject:(id)arg2 fullGeoLocationName:(id)arg3;

@end
