/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXMediaUtilities.framework/AXMediaUtilities
 */

@interface AXMCIMorphologyRectangleMinimum : AXMCIMorphologyRectangle

- (bool)_doMinimum;

@end
