/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLBVHBuilder : NSObject

- (void)getCapacitiesForDescriptor:(id)arg1 fragmentCapacity:(unsigned long long*)arg2 innerNodeCapacity:(unsigned long long*)arg3 leafNodeCapacity:(unsigned long long*)arg4;
- (void)getCapacitiesForDescriptor:(id)arg1 fragmentCapacity:(unsigned long long*)arg2 innerNodeCapacity:(unsigned long long*)arg3 leafNodeCapacity:(unsigned long long*)arg4 primitiveDataCapacity:(unsigned long long*)arg5;
- (id)init;

@end
