/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLFunctionStitchingGraphSPI : MTLFunctionStitchingGraph

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
