/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLFunctionReflection : NSObject

@property (readonly) NSArray *arguments;
@property (readonly) unsigned long long primitiveKind;
@property (readonly) NSArray *tags;

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;

@end
