/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXWatchRemoteScreenUI.framework/AXWatchRemoteScreenUI
 */

@interface AXWatchRemoteScreenUIAssetObjcWrapper : NSObject

+ (id)watchView;

@end
