/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SessionCore.framework/SessionCore
 */

@interface _TtC11SessionCoreP33_3EB6553D2992046DCD21680C8109860026AuthorizationServiceClient : NSObject <ActivityKit.ActivityAuthorizationXPCServer> {
    void authorizationManager;
    void connection;
}

- (void).cxx_destruct;
- (bool)areActivitiesEnabledForBundleId:(id)arg1;
- (bool)areActivitiesEnabledForCurrentProcess;
- (id)init;
- (bool)setActivitiesAuthorizationFor:(id)arg1 with:(id)arg2 error:(id*)arg3;
- (bool)supportsActivitiesForBundleId:(id)arg1;

@end
