/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SessionCore.framework/SessionCore
 */

@interface _TtCC11SessionCore16ActivityDatabase36MutableSyncEngineRecordMetadataStore : _TtCC11SessionCore16ActivityDatabase29SyncEngineRecordMetadataStore

@end
