/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriExpanseInternal.framework/SiriExpanseInternal
 */

@interface SiriExpanseInternal.ConfirmRecipientsFlow : _TtCs12_SwiftObject {
    void outputPublisher;
    void pattern;
    void patternExecutor;
    void state;
}

@end
