/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriExpanseInternal.framework/SiriExpanseInternal
 */

@interface SiriExpanseInternal.SharingNLv4Intent : _TtCs12_SwiftObject {
    void appIdentifier;
    void appName;
    void confirmationValue;
    void containsSharingRecipient;
    void containsSharingReference;
    void isShareViaMessagesIntent;
    void recipients;
    void refersToEverything;
    void refersToScreen;
    void verb;
}

@end
