/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LighthouseReferenceResolution.framework/LighthouseReferenceResolution
 */

@interface LighthouseReferenceResolution.LRRCdmNluResponseUtils : NSObject

+ (id)getObjcProtoWithResponse:(id)arg1;
+ (id)getProtoDataWithResponse:(id)arg1;

- (id)init;

@end
