/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIFulfilledContextMenuConfiguration : NSObject {
    NSArray * _accessoryViews;
    unsigned long long  _badgeCount;
    UIResponder * _firstResponderTarget;
    <NSCopying> * _identifier;
    id  _internalIdentifier;
    UIMenu * _menu;
    UIAction * _previewAction;
    UIViewController * _previewViewController;
    unsigned long long  _representedItemCount;
}

@property (nonatomic, retain) NSArray *accessoryViews;
@property (nonatomic) unsigned long long badgeCount;
@property (nonatomic) UIResponder *firstResponderTarget;
@property (nonatomic, copy) <NSCopying> *identifier;
@property (nonatomic, retain) id internalIdentifier;
@property (nonatomic, readonly) bool isMultiItemMenu;
@property (nonatomic, copy) UIMenu *menu;
@property (nonatomic, copy) UIAction *previewAction;
@property (nonatomic, retain) UIViewController *previewViewController;
@property (nonatomic) unsigned long long representedItemCount;

- (void).cxx_destruct;
- (id)accessoryViews;
- (unsigned long long)badgeCount;
- (id)firstResponderTarget;
- (id)identifier;
- (id)internalIdentifier;
- (bool)isMultiItemMenu;
- (bool)isPresentable;
- (id)menu;
- (id)previewAction;
- (id)previewViewController;
- (unsigned long long)representedItemCount;
- (void)setAccessoryViews:(id)arg1;
- (void)setBadgeCount:(unsigned long long)arg1;
- (void)setFirstResponderTarget:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setInternalIdentifier:(id)arg1;
- (void)setMenu:(id)arg1;
- (void)setPreviewAction:(id)arg1;
- (void)setPreviewViewController:(id)arg1;
- (void)setRepresentedItemCount:(unsigned long long)arg1;

@end
