/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UINavigationBarTitleRenamer : NSObject {
    _UINavigationBarTitleRenamerSession * _currentSession;
    <_UINavigationBarTitleRenamerDelegate> * _delegate;
}

@property (nonatomic, retain) _UINavigationBarTitleRenamerSession *currentSession;
@property (nonatomic) <_UINavigationBarTitleRenamerDelegate> *delegate;

- (void).cxx_destruct;
- (void)_sessionTextFieldDidEndEditing:(id)arg1;
- (void)_sessionTextFieldWillEndEditing:(id)arg1;
- (id)currentSession;
- (id)delegate;
- (void)endSession:(id)arg1;
- (void)setCurrentSession:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)startSession:(id)arg1;

@end
