/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarIndicatorQuietModeItem : _UIStatusBarIndicatorItem {
    _UIStatusBarImageView * _emphasizedImageView;
    NSString * _focusName;
}

@property (nonatomic, retain) _UIStatusBarImageView *emphasizedImageView;
@property (nonatomic, retain) NSString *focusName;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (id)emphasizedQuietModeIdentifier;

- (void).cxx_destruct;
- (void)_create_emphasizedImageView;
- (id)applyUpdate:(id)arg1 toDisplayItem:(id)arg2;
- (id)emphasizedImageView;
- (id)focusName;
- (id)imageViewForIdentifier:(id)arg1;
- (id)indicatorEntryKey;
- (void)setEmphasizedImageView:(id)arg1;
- (void)setFocusName:(id)arg1;
- (bool)shouldUpdateIndicatorForIdentifier:(id)arg1;
- (id)systemImageNameForUpdate:(id)arg1;
- (id)viewForIdentifier:(id)arg1;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;

@end
