/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIWindowSystemOverlayWindow : UIWindow

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (bool)_isSecure;
+ (bool)_isSystemWindow;
+ (bool)_needsPassthroughInteraction;

- (bool)_canActAsKeyWindowForScreen:(id)arg1;
- (bool)_extendsScreenSceneLifetime;
- (bool)_isSettingFirstResponder;
- (bool)_shouldAdjustSizeClassesAndResizeWindow;
- (bool)canBecomeKeyWindow;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (bool)isInternalWindow;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityCanBeConsideredAsMainWindow;

@end
