/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIContentUnavailableConstants_Phone : UIContentUnavailableConstants_IOS

+ (id)sharedConstants;

@end
