/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKBEmojiSnapshotSizingView : UIView {
    struct CGSize { 
        double width; 
        double height; 
    }  _snapshotSize;
    UIView * _snapshotView;
}

@property (nonatomic, readonly) UIView *snapshotView;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

- (void).cxx_destruct;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

// Image: /usr/lib/libMainThreadChecker.dylib

- (id)initWithSnapshotView:(id)arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (id)snapshotView;

@end
