/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestionsSupport.framework/SiriSuggestionsSupport
 */

@interface SiriSuggestionsSupport.SourceOwnerSuggestionsDispatcher : _TtCs12_SwiftObject {
    void siriHelpDispatcher;
    void staticDeliverySuggestionsDispatcher;
}

@end
