/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestionsSupport.framework/SiriSuggestionsSupport
 */

@interface SiriSuggestionsSupport.SiriSuggestionsHelper : _TtCs12_SwiftObject

@end
