/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestionsSupport.framework/SiriSuggestionsSupport
 */

@interface SiriSuggestionsSupport.SiriSuggestionsServiceDelegate : NSObject <NSXPCListenerDelegate> {
    void client;
}

- (void).cxx_destruct;
- (id)init;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;

@end
