/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProactiveHarvesting.framework/ProactiveHarvesting
 */

@interface HVInteraction : NSObject <BMIdentifiableContentEvent, NSCopying> {
    NSString * _bundleIdentifier;
    INInteraction * _interaction;
    NSString * _uniqueId;
}

@property (nonatomic, readonly) double absoluteTimestamp;
@property (nonatomic, readonly) NSString *bundleId;
@property (nonatomic, readonly) NSString *bundleIdentifier;
@property (nonatomic, readonly) NSString *domainId;
@property (nonatomic, readonly) INInteraction *interaction;
@property (nonatomic, readonly) NSString *uniqueId;

- (void).cxx_destruct;
- (double)absoluteTimestamp;
- (id)bundleId;
- (id)bundleIdentifier;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)domainId;
- (unsigned long long)hash;
- (id)init;
- (id)initWithInteraction:(id)arg1 uniqueId:(id)arg2 bundleIdentifier:(id)arg3;
- (id)interaction;
- (bool)isEqual:(id)arg1;
- (id)uniqueId;

@end
