/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HoverTextUI.framework/HoverTextUI
 */

@interface HoverTextUI.HoverTextEventHandler : NSObject <AXUIEventHandler> {
    void $__lazy_storage_$_activationKeyHoldTimer;
    void activationButtonPressed;
    void activationButtonReleased;
    void activationKey;
    void activationKeyPressCount;
    void activationKeyPressIsActive;
    void activationLockSequenceOccurred;
    void focusChange;
    void keyboardEventProcessor;
    void lastEventTime;
    void mouseStream;
    void passiveSystemWindow;
    void previousHoverElement;
    void previousKeyModifierState;
}

- (void).cxx_destruct;
- (bool)handlePointerEvent:(id)arg1;
- (id)init;

@end
