/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AACCore.framework/AACCore
 */

@interface AEAssessmentStatePublishingXPCInterfaceFactory : NSObject

- (id)makeInterface;

@end
