/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameControllerFoundation.framework/GameControllerFoundation
 */

@interface _GCDeviceDBBundleDevice : NSObject {
    NSBundle * _bundle;
    NSString * _identifier;
    NSPredicate * _ioMatchingPredicate;
    NSArray * _personalityPaths;
}

@property (readonly, copy) NSString *identifier;
@property (readonly, copy) NSPredicate *ioMatchingPredicate;

- (void).cxx_destruct;
- (id)identifier;
- (id)init;
- (id)initWithBundle:(id)arg1 dictionary:(id)arg2 error:(out id*)arg3;
- (id)ioMatchingPredicate;
- (id)personalities;

@end
