/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFAudio.framework/AVFAudio
 */

@interface AVAudioSinkNode : AVAudioNode

+ (id /* block */)pullInputBlockFromReceiverBlock:(id /* block */)arg1;

- (id)initWithReceiverBlock:(id /* block */)arg1;

@end
