/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CoreSpeechXPC : NSObject <CoreSpeechXPCProtocol> {
    CoreSpeechXPCFakeModelMonitor * _fakeAssetMonitor;
}

@property (nonatomic, retain) CoreSpeechXPCFakeModelMonitor *fakeAssetMonitor;

+ (id)accessoryModelTypeToString:(long long)arg1;
+ (void)logLanguageMismatchMetricWithJarvisSelectedLocale:(id)arg1 jarvisTriggerMode:(long long)arg2;

- (void).cxx_destruct;
- (void)_fetchVoiceTriggerInstalledAssetWithLanguage:(id)arg1 completion:(id /* block */)arg2;
- (void)_handleFakeHearstModelRequest:(id)arg1 majorVersion:(unsigned long long)arg2 minorVersion:(unsigned long long)arg3 downloadedModels:(id)arg4 preinstalledModels:(id)arg5 completion:(id /* block */)arg6;
- (id)fakeAssetMonitor;
- (void)fetchRemoteVoiceTriggerAssetForLanguageCode:(id)arg1 completion:(id /* block */)arg2;
- (id)getAccessoryFallbackFamilyLocal:(id)arg1 fromLocaleMap:(id)arg2;
- (id)getAccessoryFallbackLocalTable;
- (id)initWithFakeMonitor:(id)arg1;
- (void)installedVoiceTriggerAssetForLanguageCode:(id)arg1 completion:(id /* block */)arg2;
- (id)selectFallbackModelForLocale:(id)arg1 downloadedModels:(id)arg2 preinstalledModels:(id)arg3 rtLocaleMap:(id)arg4;
- (void)setFakeAssetMonitor:(id)arg1;
- (void)voiceTriggerHearstRTModelForVersion:(unsigned long long)arg1 minorVersion:(unsigned long long)arg2 locale:(id)arg3 downloadedModels:(id)arg4 preinstalledModels:(id)arg5 completion:(id /* block */)arg6;
- (void)voiceTriggerJarvisLanguageList:(id)arg1 jarvisSelectedLanguage:(id)arg2 completion:(id /* block */)arg3;
- (void)voiceTriggerRTModelForVersion:(unsigned long long)arg1 minorVersion:(unsigned long long)arg2 accessoryRTModelType:(long long)arg3 locale:(id)arg4 endpointId:(id)arg5 downloadedModels:(id)arg6 preinstalledModels:(id)arg7 completion:(id /* block */)arg8;
- (void)voiceTriggerRTModelForVersion:(unsigned long long)arg1 minorVersion:(unsigned long long)arg2 locale:(id)arg3 downloadedModels:(id)arg4 preinstalledModels:(id)arg5 completion:(id /* block */)arg6;
- (void)voiceTriggerRemoraRTModelForVersion:(unsigned long long)arg1 minorVersion:(unsigned long long)arg2 locale:(id)arg3 endpointId:(id)arg4 downloadedModels:(id)arg5 preinstalledModels:(id)arg6 completion:(id /* block */)arg7;

@end
