/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSAudioRouteChangeMonitorImplWatch : CSAudioRouteChangeMonitor {
    bool  _isHearstConnected;
    bool  _isHearstRouted;
    NSObject<OS_dispatch_queue> * _queue;
}

- (void).cxx_destruct;
- (bool)_fetchHearstRoutedState;
- (void)_notifyHearstRoutedState:(bool)arg1;
- (void)_startMonitoringWithQueue:(id)arg1;
- (void)_startObservingAudioRouteChange;
- (void)_startObservingSystemControllerLifecycle;
- (void)_stopMonitoring;
- (void)_systemControllerDied:(id)arg1;
- (void)activeAudioRouteDidChange:(id)arg1;
- (bool)carPlayConnected;
- (void)getHearstConnected:(id /* block */)arg1;
- (void)getHearstRouted:(id /* block */)arg1;
- (void)getJarvisConnected:(id /* block */)arg1;
- (bool)hearstConnected;
- (bool)hearstRouted;
- (id)init;
- (bool)jarvisConnected;

@end
