/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PegasusAPI.framework/PegasusAPI
 */

@interface _TtCV10PegasusAPI28Searchfoundation_CardSectionP33_A998263E27E0D03290CB0E5946B4B72E13_StorageClass : _TtCs12_SwiftObject {
    void _cardSectionDetail;
    void _cardSectionID;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _command;
    void _commands;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _nextCard;
    void _parameterKeyPaths;
    void _previewButtonItems;
    void _previewButtonItemsTitle;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _previewCommand;
    void _resultIdentifier;
    void _type;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _userReportRequest;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _value;
}

@end
