/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DocumentUnderstanding.framework/DocumentUnderstanding
 */

@interface DocumentUnderstanding.DUProductClassificationSpecification : _TtCs12_SwiftObject

@end
