/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AuthKitUI.framework/AuthKitUI
 */

@interface AKAuthorizationPaneMetrics : NSObject

+ (double)blurryTrayHeight;
+ (double)clearButtonWidth;
+ (double)contentOffsetThresholdToShowBlurTray;
+ (double)continueButtonBottomSpacing;
+ (double)continueButtonCornerRadius;
+ (double)continueButtonHeight;
+ (double)continueButtonTextHorizontalPadding;
+ (double)continueButtonTopSpacing;
+ (double)editPaneInfoLabelHorizontalPadding;
+ (double)emailCellHeight;
+ (double)iconBottomSpacing;
+ (struct CGSize { double x1; double x2; })iconSize;
+ (double)iconTopSpacing;
+ (double)infoLabelBottomSpacing;
+ (double)infoLabelToTableSpacing;
+ (double)interBulletSpacing;
+ (double)interScopeFieldSpacing;
+ (double)keyboardAccessoryViewHeight;
+ (double)maximumContentHeightFactor;
+ (double)nameCellHeight;
+ (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })paneAdditionSafeAreaInsets;
+ (double)paneCornerRadius;
+ (double)privacyInfoToLinkBottomSpacing;
+ (double)privacyInfoTopSpacing;
+ (double)privacyLinkBottomSpacing;
+ (double)privacyLinkTopSpacing;
+ (double)selectEmailCellHeight;
+ (double)tableSectionFooterHeight;
+ (double)titleBottomSpacing;
+ (double)titleToSmallTitleVerticalSpacing;
+ (double)titleTopSpacing;
+ (double)upgradeAccountInterItemSpacing;
+ (double)upgradeAccountTopSpacing;
+ (double)useOtherAppleIDBottomSpacing;
+ (double)useOtherAppleIDTopSpacing;

@end
