/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface _HKTimeScopeControlBar : HKTimeScopeControl {
    UISegmentedControl * _segments;
}

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (void).cxx_destruct;
- (void)_segmentValueChanged:(id)arg1;
- (void)layoutSubviews;
- (long long)selectedTimeScope;
- (void)setSelectedTimeScope:(long long)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

// Image: /System/Library/AccessibilityBundles/HealthUI.axbundle/HealthUI

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 timeScopes:(id)arg2 shortTextStyle:(bool)arg3;

@end
