/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKImproveSafetyDataCollectionViewController : OBTextWelcomeController {
    id /* block */  _completion;
}

@property (nonatomic, copy) id /* block */ completion;

+ (id)localizedStringWithKey:(id)arg1;
+ (id)localizedStringWithKey:(id)arg1 hasMaskedVariant:(bool)arg2;
+ (bool)needsRequestedPermission;
+ (void)presentInViewController:(id)arg1 completion:(id /* block */)arg2;

- (void).cxx_destruct;
- (void)_disableDataCollection;
- (void)_enableDataCollection;
- (void)_setDataCollectionToNewValue:(bool)arg1;
- (void)_showDataCollectionAdditionalInfo;
- (id /* block */)completion;
- (id)localizedStringWithKey:(id)arg1;
- (id)localizedStringWithKey:(id)arg1 hasMaskedVariant:(bool)arg2;
- (void)setCompletion:(id /* block */)arg1;
- (void)setUpButtons;
- (void)setUpContent;
- (bool)shouldInlineButtonTray;
- (void)viewDidLoad;

@end
