/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Network.framework/Network
 */

@interface NWURLSessionRequestBodyStream : NSObject <NSStreamDelegate, NWURLSessionRequestBodyProvider> {
    unsigned long long  _offset;
    NSObject<OS_dispatch_queue> * _queue;
    NWURLSessionReadRequest * _readRequest;
    NSInputStream * _stream;
    bool  _streamIsSetup;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)readMinimumIncompleteLength:(unsigned long long)arg1 maximumLength:(unsigned long long)arg2 completionHandler:(id /* block */)arg3;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;

@end
