/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iTunesCloud.framework/iTunesCloud
 */

@interface ICLiveLinkQueueEventContentReordered : NSObject {
    NSString * _itemIdentifier;
}

@property (nonatomic, readonly, copy) NSString *itemIdentifier;

- (void).cxx_destruct;
- (id)description;
- (id)initWithItemIdentifier:(id)arg1;
- (id)itemIdentifier;

@end
