/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PencilKit.framework/PencilKit
 */

@interface PKEraserTool : PKTool

@property (nonatomic, readonly) double _weight;
@property (nonatomic, readonly) long long eraserType;

- (double)_weight;
- (long long)eraserType;
- (id)initWithEraserType:(long long)arg1;
- (id)initWithEraserType:(long long)arg1 weight:(double)arg2;

@end
