/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PencilKit.framework/PencilKit
 */

@interface PKTextInputLanguageSpec : NSObject {
    long long  __languageBehavior;
    NSArray * __locales;
}

- (void).cxx_destruct;

@end
