/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileMailUI.framework/MobileMailUI
 */

@interface MailQLAttachmentContext : NSObject {
    NSURL * _attachmentURL;
    bool  _contentManaged;
    long long  _editBehavior;
    EMMailboxObjectID * _mailboxObjectID;
    EMMessageObjectID * _messageObjectID;
    NSString * _subject;
}

@property (nonatomic, readonly) NSURL *attachmentURL;
@property (getter=isContentManaged, nonatomic, readonly) bool contentManaged;
@property (nonatomic, readonly) long long editBehavior;
@property (nonatomic, readonly) EMMailboxObjectID *mailboxObjectID;
@property (nonatomic, readonly) EMMessageObjectID *messageObjectID;
@property (nonatomic, readonly) NSString *subject;
@property (nonatomic, readonly, copy) NSUserActivity *userActivity;

+ (id)contextWithUserActivity:(id)arg1;

- (void).cxx_destruct;
- (id)attachmentURL;
- (long long)editBehavior;
- (id)initWithAttachmentURL:(id)arg1 editBehavior:(long long)arg2 messageObjectID:(id)arg3 mailboxObjectID:(id)arg4 subject:(id)arg5 contentManaged:(bool)arg6;
- (bool)isContentManaged;
- (id)mailboxObjectID;
- (id)messageObjectID;
- (id)subject;
- (id)userActivity;

@end
