/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsTransport.framework/NewsTransport
 */

@interface NTPBArticleTopic : PBCodable <NSCopying> {
    COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList * _cohorts;
    COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats * _conversionStats;
    double  _flowRate;
    struct { 
        unsigned int flowRate : 1; 
        unsigned int ontologyLevel : 1; 
        unsigned int quality : 1; 
        unsigned int subscriptionRate : 1; 
        unsigned int isEligibleForGrouping : 1; 
        unsigned int isEligibleForGroupingIfAutofavorited : 1; 
        unsigned int isEligibleForGroupingIfFavorited : 1; 
        unsigned int isHidden : 1; 
        unsigned int isManagedTopic : 1; 
        unsigned int isManagedTopicWinner : 1; 
    }  _has;
    bool  _isEligibleForGrouping;
    bool  _isEligibleForGroupingIfAutofavorited;
    bool  _isEligibleForGroupingIfFavorited;
    bool  _isHidden;
    bool  _isManagedTopic;
    bool  _isManagedTopicWinner;
    long long  _ontologyLevel;
    double  _quality;
    double  _subscriptionRate;
    NSString * _tagID;
}

@property (nonatomic, retain) COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList *cohorts;
@property (nonatomic, retain) COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats *conversionStats;
@property (nonatomic) double flowRate;
@property (nonatomic, readonly) bool hasCohorts;
@property (nonatomic, readonly) bool hasConversionStats;
@property (nonatomic) bool hasFlowRate;
@property (nonatomic) bool hasIsEligibleForGrouping;
@property (nonatomic) bool hasIsEligibleForGroupingIfAutofavorited;
@property (nonatomic) bool hasIsEligibleForGroupingIfFavorited;
@property (nonatomic) bool hasIsHidden;
@property (nonatomic) bool hasIsManagedTopic;
@property (nonatomic) bool hasIsManagedTopicWinner;
@property (nonatomic) bool hasOntologyLevel;
@property (nonatomic) bool hasQuality;
@property (nonatomic) bool hasSubscriptionRate;
@property (nonatomic, readonly) bool hasTagID;
@property (nonatomic) bool isEligibleForGrouping;
@property (nonatomic) bool isEligibleForGroupingIfAutofavorited;
@property (nonatomic) bool isEligibleForGroupingIfFavorited;
@property (nonatomic) bool isHidden;
@property (nonatomic) bool isManagedTopic;
@property (nonatomic) bool isManagedTopicWinner;
@property (nonatomic) long long ontologyLevel;
@property (nonatomic) double quality;
@property (nonatomic) double subscriptionRate;
@property (nonatomic, retain) NSString *tagID;

- (id)cohorts;
- (id)conversionStats;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (double)flowRate;
- (bool)hasCohorts;
- (bool)hasConversionStats;
- (bool)hasFlowRate;
- (bool)hasIsEligibleForGrouping;
- (bool)hasIsEligibleForGroupingIfAutofavorited;
- (bool)hasIsEligibleForGroupingIfFavorited;
- (bool)hasIsHidden;
- (bool)hasIsManagedTopic;
- (bool)hasIsManagedTopicWinner;
- (bool)hasOntologyLevel;
- (bool)hasQuality;
- (bool)hasSubscriptionRate;
- (bool)hasTagID;
- (unsigned long long)hash;
- (bool)isEligibleForGrouping;
- (bool)isEligibleForGroupingIfAutofavorited;
- (bool)isEligibleForGroupingIfFavorited;
- (bool)isEqual:(id)arg1;
- (bool)isHidden;
- (bool)isManagedTopic;
- (bool)isManagedTopicWinner;
- (void)mergeFrom:(id)arg1;
- (long long)ontologyLevel;
- (double)quality;
- (bool)readFrom:(id)arg1;
- (void)setCohorts:(id)arg1;
- (void)setConversionStats:(id)arg1;
- (void)setFlowRate:(double)arg1;
- (void)setHasFlowRate:(bool)arg1;
- (void)setHasIsEligibleForGrouping:(bool)arg1;
- (void)setHasIsEligibleForGroupingIfAutofavorited:(bool)arg1;
- (void)setHasIsEligibleForGroupingIfFavorited:(bool)arg1;
- (void)setHasIsHidden:(bool)arg1;
- (void)setHasIsManagedTopic:(bool)arg1;
- (void)setHasIsManagedTopicWinner:(bool)arg1;
- (void)setHasOntologyLevel:(bool)arg1;
- (void)setHasQuality:(bool)arg1;
- (void)setHasSubscriptionRate:(bool)arg1;
- (void)setIsEligibleForGrouping:(bool)arg1;
- (void)setIsEligibleForGroupingIfAutofavorited:(bool)arg1;
- (void)setIsEligibleForGroupingIfFavorited:(bool)arg1;
- (void)setIsHidden:(bool)arg1;
- (void)setIsManagedTopic:(bool)arg1;
- (void)setIsManagedTopicWinner:(bool)arg1;
- (void)setOntologyLevel:(long long)arg1;
- (void)setQuality:(double)arg1;
- (void)setSubscriptionRate:(double)arg1;
- (void)setTagID:(id)arg1;
- (double)subscriptionRate;
- (id)tagID;
- (void)writeTo:(id)arg1;

@end
