/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MailUI.framework/MailUI
 */

@interface MailUI.RichLinkMetadataGenerator : _TtCs12_SwiftObject {
    void messageRepository;
    void metadataCache;
}

@end
