/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MailUI.framework/MailUI
 */

@interface MUISnippetGenerator : NSObject

+ (id)highlightedSnippetUsingTokens:(id)arg1 attributedString:(id)arg2 maxNumberOfWordsBeforeOrAfterToken:(long long)arg3 maxNumberOfRanges:(long long)arg4 highlighting:(id /* block */)arg5 error:(id*)arg6;
+ (id)highlightingIfAddresses:(id)arg1 containTokens:(id)arg2 attributedString:(id)arg3 highlighting:(id /* block */)arg4 error:(id*)arg5;
+ (id)highlightingTokens:(id)arg1 attributedString:(id)arg2 highlighting:(id /* block */)arg3 error:(id*)arg4;

@end
