/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssetViewer.framework/AssetViewer
 */

@interface AssetViewer.CameraController : _TtCs12_SwiftObject {
    void camera;
    void environmentEntity;
    void identityState;
    void observer;
    void state;
}

@end
