/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Coherence.framework/Coherence
 */

@interface Coherence.CRSQLStoreSnapshot : _TtCs12_SwiftObject {
    void sqliteSnapshot;
}

@end
