/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Coherence.framework/Coherence
 */

@interface Coherence.CRDecodeContext : _TtCs12_SwiftObject {
    void assetManager;
    void capsuleReferences;
    void decodingReferences;
}

@end
