/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DVTInstrumentsFoundation.framework/DVTInstrumentsFoundation
 */

@interface DTActivityTraceTapMessage : DTTapMessage <NSSecureCoding>

+ (bool)supportsSecureCoding;

@end
