/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DVTInstrumentsFoundation.framework/DVTInstrumentsFoundation
 */

@interface DTSysmonTapMessageHandler : DTTapMessageHandler {
    NSData * _nextSampleData;
    unsigned int  _tapVersion;
}

- (void).cxx_destruct;
- (id)messageReceived:(id)arg1;

@end
