/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityFoundation.framework/RealityFoundation
 */

@interface _TtCV10RealityKit13__REAnchoring12Registration : _TtCs12_SwiftObject {
    void componentType;
    void introspectionStruct;
}

@end
