/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityFoundation.framework/RealityFoundation
 */

@interface RealityKit.__RKVisibilityHideDropAnimation : RealityKit.__RKVisibilityBaseAnimation

@end
