/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityFoundation.framework/RealityFoundation
 */

@interface RealityFoundation.UnkeyedEC : _TtCs12_SwiftObject {
    void codingPath;
    void count;
    void encoder;
    void nestedContainer;
}

@end
