/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityFoundation.framework/RealityFoundation
 */

@interface RealityKit.__RKEmphasisBlinkAnimation : RealityKit.__RKEmphasisBaseAnimation

@end
