/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GPUToolsTransport.framework/GPUToolsTransport
 */

@interface GTLocalXPCConnection : NSObject <GTXPCConnection> {
    NSObject<OS_xpc_object> * _connection;
    NSMutableArray * _connectionHandlers;
    NSMutableDictionary * _dispatchers;
    NSObject<OS_xpc_object> * _error;
    NSMutableDictionary * _observers;
    NSUUID * _originDeviceUUID;
    unsigned long long  _originPort;
    NSObject<OS_os_transaction> * _transaction;
}

@property (nonatomic, readonly) NSObject<OS_xpc_object> *connection;
@property (nonatomic, retain) NSObject<OS_xpc_object> *error;
@property (nonatomic, retain) NSMutableDictionary *observers;
@property (readonly) NSUUID *originDeviceUUID;
@property (readonly) unsigned long long originPort;
@property (readonly) NSArray *proxyHandlers;

- (void).cxx_destruct;
- (id)connection;
- (void)dispatchMessage:(id)arg1;
- (id)error;
- (id)initWithTransactionScopedXPCConnection:(id)arg1;
- (id)initWithXPCConnection:(id)arg1;
- (id)observers;
- (id)originDeviceUUID;
- (unsigned long long)originPort;
- (id)proxyHandlers;
- (void)registerDispatcher:(id)arg1 forServicePort:(unsigned long long)arg2;
- (void)registerProxyHandler:(id /* block */)arg1;
- (void)removeProxyHandler:(id /* block */)arg1;
- (void)sendMessage:(id)arg1;
- (void)sendMessage:(id)arg1 queue:(id)arg2 replyHandler:(id /* block */)arg3;
- (id)sendMessageWithReplySync:(id)arg1;
- (void)setError:(id)arg1;
- (void)setObservers:(id)arg1;
- (void)setupDeviceUUID:(id)arg1;
- (void)setupPort:(unsigned long long)arg1;

@end
