/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthMedicationsExperience.framework/HealthMedicationsExperience
 */

@interface HealthMedicationsExperience.TestMedicationDetailProvider : HealthMedicationsExperience.MedicationDetailProvider

@end
