/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDCodableSignedClinicalDataRecord : PBCodable <HDDecoding, NSCopying> {
    HDCodableStringList * _credentialTypes;
    NSData * _dataValue;
    double  _expirationDate;
    struct { 
        unsigned int expirationDate : 1; 
        unsigned int issuedDate : 1; 
        unsigned int relevantDate : 1; 
        unsigned int signatureStatus : 1; 
        unsigned int sourceType : 1; 
    }  _has;
    double  _issuedDate;
    NSString * _issuerIdentifier;
    HDCodableSignedClinicalDataItemList * _items;
    HDCodableMedicalRecord * _medicalRecord;
    double  _relevantDate;
    long long  _signatureStatus;
    long long  _sourceType;
    HDCodableSignedClinicalDataSubject * _subject;
}

@property (nonatomic, retain) HDCodableStringList *credentialTypes;
@property (nonatomic, retain) NSData *dataValue;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) double expirationDate;
@property (nonatomic, readonly) bool hasCredentialTypes;
@property (nonatomic, readonly) bool hasDataValue;
@property (nonatomic) bool hasExpirationDate;
@property (nonatomic) bool hasIssuedDate;
@property (nonatomic, readonly) bool hasIssuerIdentifier;
@property (nonatomic, readonly) bool hasItems;
@property (nonatomic, readonly) bool hasMedicalRecord;
@property (nonatomic) bool hasRelevantDate;
@property (nonatomic) bool hasSignatureStatus;
@property (nonatomic) bool hasSourceType;
@property (nonatomic, readonly) bool hasSubject;
@property (readonly) unsigned long long hash;
@property (nonatomic) double issuedDate;
@property (nonatomic, retain) NSString *issuerIdentifier;
@property (nonatomic, retain) HDCodableSignedClinicalDataItemList *items;
@property (nonatomic, retain) HDCodableMedicalRecord *medicalRecord;
@property (nonatomic) double relevantDate;
@property (nonatomic) long long signatureStatus;
@property (nonatomic) long long sourceType;
@property (nonatomic, retain) HDCodableSignedClinicalDataSubject *subject;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)applyToObject:(id)arg1;
- (bool)applyToObject:(id)arg1 error:(out id*)arg2;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)credentialTypes;
- (id)dataValue;
- (id)description;
- (id)dictionaryRepresentation;
- (double)expirationDate;
- (bool)hasCredentialTypes;
- (bool)hasDataValue;
- (bool)hasExpirationDate;
- (bool)hasIssuedDate;
- (bool)hasIssuerIdentifier;
- (bool)hasItems;
- (bool)hasMedicalRecord;
- (bool)hasRelevantDate;
- (bool)hasSignatureStatus;
- (bool)hasSourceType;
- (bool)hasSubject;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (double)issuedDate;
- (id)issuerIdentifier;
- (id)items;
- (id)medicalRecord;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (double)relevantDate;
- (void)setCredentialTypes:(id)arg1;
- (void)setDataValue:(id)arg1;
- (void)setExpirationDate:(double)arg1;
- (void)setHasExpirationDate:(bool)arg1;
- (void)setHasIssuedDate:(bool)arg1;
- (void)setHasRelevantDate:(bool)arg1;
- (void)setHasSignatureStatus:(bool)arg1;
- (void)setHasSourceType:(bool)arg1;
- (void)setIssuedDate:(double)arg1;
- (void)setIssuerIdentifier:(id)arg1;
- (void)setItems:(id)arg1;
- (void)setMedicalRecord:(id)arg1;
- (void)setRelevantDate:(double)arg1;
- (void)setSignatureStatus:(long long)arg1;
- (void)setSourceType:(long long)arg1;
- (void)setSubject:(id)arg1;
- (long long)signatureStatus;
- (long long)sourceType;
- (id)subject;
- (void)writeTo:(id)arg1;

@end
