/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriNaturalLanguageParsing.framework/SiriNaturalLanguageParsing
 */

@interface SNLPFeatureFlagUtilities : NSObject

+ (bool)isSNLPFeatureStoreEnabled;

@end
