/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriNaturalLanguageParsing.framework/SiriNaturalLanguageParsing
 */

@interface UPPLToken : NSObject {
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _charIndicesRange;
    NSArray * _encodedLabels;
    NSArray * _graphemeClusters;
    bool  _isOverflow;
    bool  _isSpecialToken;
    bool  _isWordPiece;
    NSString * _token;
    unsigned long long  _tokenId;
}

@property (nonatomic, readonly) struct _NSRange { unsigned long long x1; unsigned long long x2; } charIndicesRange;
@property (nonatomic, readonly) NSArray *encodedLabels;
@property (nonatomic, readonly) NSArray *graphemeClusters;
@property (nonatomic, readonly) bool isOverflow;
@property (nonatomic, readonly) bool isSpecialToken;
@property (nonatomic, readonly) bool isWordPiece;
@property (nonatomic, readonly) NSString *token;
@property (nonatomic, readonly) unsigned long long tokenId;

- (void).cxx_destruct;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })charIndicesRange;
- (id)dictionaryRepresentation;
- (id)encodedLabels;
- (id)graphemeClusters;
- (id)initWithToken:(id)arg1 tokenId:(unsigned long long)arg2 charIndicesRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg3 graphemeClusters:(id)arg4;
- (id)initWithToken:(id)arg1 tokenId:(unsigned long long)arg2 charIndicesRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg3 graphemeClusters:(id)arg4 isSpecialToken:(bool)arg5 isWordPiece:(bool)arg6 isOverflow:(bool)arg7 encodedLabels:(id)arg8;
- (bool)isOverflow;
- (bool)isSpecialToken;
- (bool)isWordPiece;
- (id)token;
- (unsigned long long)tokenId;

@end
