/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PosterBoard.framework/PosterBoard
 */

@interface PBFPosterGalleryPreviewWithDescriptionCell : UICollectionViewCell <PBFPosterGalleryCollectionViewCell> {
    unsigned long long  _index;
    struct { 
        struct CGRect { 
            struct CGPoint { 
                double x; 
                double y; 
            } origin; 
            struct CGSize { 
                double width; 
                double height; 
            } size; 
        } posterViewFrame; 
        struct CGRect { 
            struct CGPoint { 
                double x; 
                double y; 
            } origin; 
            struct CGSize { 
                double width; 
                double height; 
            } size; 
        } posterDescriptionLabelFrame; 
        struct CGSize { 
            double width; 
            double height; 
        } intrinsicContentSize; 
    }  _metrics;
    NSString * _posterDescription;
    UILabel * _posterDescriptionLabel;
    <PBFPosterPreview> * _posterPreview;
    PBFPosterGalleryPreviewView * _posterPreviewView;
    PBFPosterGalleryViewSpec * _spec;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long index;
@property (nonatomic, retain) NSString *posterDescription;
@property (nonatomic, retain) <PBFPosterPreview> *posterPreview;
@property (nonatomic, readonly) PBFPosterGalleryPreviewView *posterPreviewView;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)didMoveToWindow;
- (unsigned long long)index;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (void)layoutSubviews;
- (struct { struct CGRect { struct CGPoint { double x_1_2_1; double x_1_2_2; } x_1_1_1; struct CGSize { double x_2_2_1; double x_2_2_2; } x_1_1_2; } x1; struct CGRect { struct CGPoint { double x_1_2_1; double x_1_2_2; } x_2_1_1; struct CGSize { double x_2_2_1; double x_2_2_2; } x_2_1_2; } x2; struct CGSize { double x_3_1_1; double x_3_1_2; } x3; })metrics;
- (id)posterDescription;
- (id)posterDescriptionLabel;
- (id)posterPreview;
- (id)posterPreviewView;
- (void)prepareForReuse;
- (void)setIndex:(unsigned long long)arg1;
- (void)setPosterDescription:(id)arg1;
- (void)setPosterPreview:(id)arg1;
- (id)spec;

@end
