/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PosterBoard.framework/PosterBoard
 */

@interface PBFRuntimeAssertionManager : NSObject <BSInvalidatable, PBFRuntimeAssertionProviding> {
    <BSInvalidatable> * _stateCaptureSentinel;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _stateLock;
    NSMapTable * _stateLock_acquistionDateForAssertion;
    NSMapTable * _stateLock_acquistionInvalidationHandlerForAssertion;
    bool  _stateLock_invalidated;
    NSHashTable * _stateLock_knownAssertions;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_buildRBSAssertionForTarget:(id)arg1 assertionIdentifier:(id)arg2 explanation:(id)arg3 invalidationHandler:(id /* block */)arg4;
- (void)_runningBoardAssertionStateDidUpdate:(id)arg1 assertionIdentifier:(id)arg2 error:(id)arg3;
- (id)_stateLock_debugDescriptionForPosterBoardProcessAssertions;
- (id)_stateLock_debugDescriptionForPosterExtensionProcessAssertions;
- (id)_stateLock_debugDescriptionForTarget:(id)arg1;
- (id)acquireAssertion:(id)arg1 reason:(id)arg2 target:(id)arg3 invalidationHandler:(id /* block */)arg4;
- (id)acquirePosterUpdateMemoryAssertionForReason:(id)arg1 target:(id)arg2 auditToken:(id)arg3 posterProviderBundleIdentifier:(id)arg4;
- (id)acquirePosterUpdateRuntimeAssertionForReason:(id)arg1 target:(id)arg2;
- (id)acquirePrewarmRuntimeAssertionForReason:(id)arg1 target:(id)arg2 invalidationHandler:(id /* block */)arg3;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)init;
- (void)invalidate;

@end
