/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RunningBoard.framework/RunningBoard
 */

@interface RBLaunchdJobManager : NSObject {
    RBContainerManager * _containerManager;
    <RBLaunchdInterfacing> * _launchdInterface;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    NSMutableDictionary * _lock_jobsByIdentifier;
    NSMutableDictionary * _lock_monitoredJobsByIdentifier;
    NSMutableOrderedSet * _lock_reslideIdentities;
    RBPersonaManager * _personaManager;
}

+ (id)lastExitStatusForLabel:(id)arg1 error:(out id*)arg2;

- (void).cxx_destruct;
- (bool)_addAppPropertiesToData:(id)arg1 forIdentity:(id)arg2 context:(id)arg3 error:(id*)arg4;
- (void)_addDextPropertiesToData:(id)arg1 forIdentity:(id)arg2 context:(id)arg3;
- (void)_addReslideIdentityIfNeeded:(id)arg1 exitStatus:(id)arg2;
- (void)_addSharedPropertiesToData:(id)arg1 forIdentity:(id)arg2 context:(id)arg3;
- (void)_addStandardAppPropertiesToData:(id)arg1;
- (id)_createAndSubmitExtensionJob:(id)arg1 UUID:(id)arg2 error:(id*)arg3;
- (id)_createLaunchdJobWithIdentity:(id)arg1 context:(id)arg2 error:(id*)arg3;
- (id)_generateDataWithIdentity:(id)arg1 context:(id)arg2 error:(id*)arg3;
- (bool)_isRunningBoardLaunched:(id)arg1;
- (bool)_removeJobWithInstance:(id)arg1 orJob:(id)arg2 error:(out id*)arg3;
- (id)createAndLaunchWithIdentity:(id)arg1 context:(id)arg2 error:(out id*)arg3;
- (id)initWithLaunchdInterface:(id)arg1 personaManager:(id)arg2 containerManager:(id)arg3;
- (void)invokeOnProcessDeath:(id)arg1 handler:(id /* block */)arg2 onQueue:(id)arg3;
- (bool)removeJobWithInstance:(id)arg1 error:(out id*)arg2;
- (id)synchronizeJobs;
- (unsigned long long)test_trackedJobCount;

@end
