/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PlatformSSO.framework/PlatformSSO
 */

@interface PORS256JWTSigningAlgorithm : NSObject <POJWTSigningAlgorithm>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id)signData:(id)arg1 usingKey:(struct __SecKey { }*)arg2;
- (bool)verifySignature:(id)arg1 onData:(id)arg2 usingCertificateString:(id)arg3;
- (bool)verifySignature:(id)arg1 onData:(id)arg2 usingKey:(struct __SecKey { }*)arg3;

@end
