/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVDatabaseDelete : CKVDatabaseCommand

+ (id)builderWithTableName:(id)arg1;

@end
