/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShareSheet.framework/ShareSheet
 */

@interface SHSheetPresentationBlockingViewController : UIViewController

- (void)viewDidLoad;

@end
