/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightServices.framework/SpotlightServices
 */

@interface SSRelatedSearchesSectionBuilder : SSSectionBuilder

+ (id)supportedBundleIds;

- (id)buildCardSections;
- (id)buildTitle;
- (bool)shouldSkipSection;
- (bool)useHorizontallyScrollingCardSectionUI;

@end
