/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/PersonalizationPortraitInternals
 */

@interface PersonalizationPortraitInternals.Consumer : NSObject {
    void entityDissector;
    void entityStoreOverride;
    void locationStoreOverride;
    void topicDissector;
    void topicStoreOverride;
    void writebackDissector;
}

- (void).cxx_destruct;
- (id)init;

@end
