/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/PersonalizationPortraitInternals
 */

@interface PPSocialHighlightStorageGuardedData : NSObject {
    BMSocialHighlightFeedbackStream * feedbackStream;
}

- (void).cxx_destruct;

@end
