/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRAVExternalRoutingDiscoverySession : MRAVRoutingDiscoverySession <MREndpointObserver> {
    MRAVRoutingDiscoverySessionConfiguration * _configuration;
    MRAVEndpoint * _destination;
    unsigned int  _discoveryMode;
    MRExternalDevice * _externalDevice;
    id  _externalDeviceDiscoveryToken;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) MRAVEndpoint *destination;
@property (nonatomic, retain) MRExternalDevice *externalDevice;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)availableEndpoints;
- (id)availableOutputDevices;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)destination;
- (id)destinationOutputDeviceUID;
- (bool)devicePresenceDetected;
- (unsigned int)discoveryMode;
- (void)endpointDidDisconnect:(id)arg1;
- (unsigned int)endpointFeatures;
- (id)externalDevice;
- (id)initWithConfiguration:(id)arg1;
- (void)setDestination:(id)arg1;
- (void)setDiscoveryMode:(unsigned int)arg1;
- (void)setExternalDevice:(id)arg1;

@end
