/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKFixedCurrentCountryCodeProvider : NSObject <HKCurrentCountryCodeProvider> {
    NSString * _countryCode;
}

- (void).cxx_destruct;
- (id)currentCountryCode;
- (id)initWithCountryCode:(id)arg1;

@end
