/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HearingUtilities.framework/HearingUtilities
 */

@interface HUAudioSession : AVAudioSession {
    unsigned long long  _currentFeature;
}

@property (nonatomic) unsigned long long currentFeature;

- (unsigned long long)currentFeature;
- (void)setActive:(bool)arg1 forFeature:(unsigned long long)arg2 error:(id*)arg3;
- (void)setCurrentFeature:(unsigned long long)arg1;

@end
