/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface _TtCC7Message28BackFillMessageBodySchedulerP33_8C94728D29B9D9CACC7F5FFB5564322B8Activity : _TtCs12_SwiftObject {
    void didComplete;
    void queue;
    void running;
    void scheduler;
    void timer;
    void underlying;
}

@end
