/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXAppEntityFeatures : NSObject <ATXJSONSerializableProtocol> {
    NSNumber * _appCategoryScore;
    NSNumber * _appCategoryScore_v2;
    NSNumber * _globalInterruptingPrior;
    NSNumber * _globalModeAffinityPrior;
    NSNumber * _notificationsReceivedInLastTwoWeeks;
}

@property (nonatomic, retain) NSNumber *appCategoryScore;
@property (nonatomic, retain) NSNumber *appCategoryScore_v2;
@property (nonatomic, retain) NSNumber *globalInterruptingPrior;
@property (nonatomic, retain) NSNumber *globalModeAffinityPrior;
@property (nonatomic, retain) NSNumber *notificationsReceivedInLastTwoWeeks;

- (void).cxx_destruct;
- (id)appCategoryScore;
- (id)appCategoryScore_v2;
- (id)globalInterruptingPrior;
- (id)globalModeAffinityPrior;
- (id)init;
- (id)initFromJSON:(id)arg1;
- (id)jsonRepresentation;
- (id)notificationsReceivedInLastTwoWeeks;
- (void)setAppCategoryScore:(id)arg1;
- (void)setAppCategoryScore_v2:(id)arg1;
- (void)setGlobalInterruptingPrior:(id)arg1;
- (void)setGlobalModeAffinityPrior:(id)arg1;
- (void)setNotificationsReceivedInLastTwoWeeks:(id)arg1;

@end
