/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXCategoricalFeatureLocationType : ATXCandidateRelevanceModelOneHotCategoricalFeaturizer

- (id)categoricalFeatureValueForContext:(id)arg1 candidate:(id)arg2;
- (id)featureNameForRTLocationOfInterestType:(long long)arg1;

@end
