/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.ShineImage : _TtCs12_SwiftObject {
    void backgroundImage;
    void context;
    void image;
    void size;
}

@end
