/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContextKitExtraction.framework/ContextKitExtraction
 */

@interface CKContextUIClasses : NSObject

+ (bool)isPDFView:(id)arg1;
+ (bool)isSFSafariView:(id)arg1;
+ (bool)isWKWebView:(id)arg1;
+ (void)lookupClasses;

@end
