/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FMIPCore.framework/FMIPCore
 */

@interface _TtCC8FMIPCore27FMIPDeviceActionsControllerP33_77C0998289D48A37179EA61E868FB8C814CommandFutures : _TtCs12_SwiftObject {
    void futures;
}

@end
