/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FMIPCore.framework/FMIPCore
 */

@interface FMIPCore.FMIPAddSafeLocationToAllSupportedBeaconsAction : FMIPCore.FMIPSafeLocationAction {
    void safeLocation;
}

@end
