/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MapsSync.framework/MapsSync
 */

@interface MSRAPRecord : MapsSync.MapsSyncObject {
    void _contentData;
    void _countryCode;
    void _positionIndex;
    void _reportId;
    void _status;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _statusLastUpdatedDate;
    void _summary;
    void _type;
}

@property (nonatomic, copy) NSData *contentData;
@property (nonatomic, copy) NSString *countryCode;
@property (nonatomic) long long positionIndex;
@property (nonatomic, copy) NSString *reportId;
@property (nonatomic) short status;
@property (nonatomic, copy) NSDate *statusLastUpdatedDate;
@property (nonatomic, copy) NSString *summary;
@property (nonatomic) short type;

+ (Class)managedClass;

- (void).cxx_destruct;
- (id)contentData;
- (id)countryCode;
- (id)initWithObject:(id)arg1 store:(id)arg2;
- (id)initWithStore:(id)arg1 contentData:(id)arg2 countryCode:(id)arg3 positionIndex:(long long)arg4 reportId:(id)arg5 status:(short)arg6 statusLastUpdatedDate:(id)arg7 summary:(id)arg8 type:(short)arg9;
- (long long)positionIndex;
- (id)reportId;
- (void)setContentData:(id)arg1;
- (void)setCountryCode:(id)arg1;
- (void)setPositionIndex:(long long)arg1;
- (void)setPropertiesUnsafeWithManagedObject:(id)arg1;
- (void)setReportId:(id)arg1;
- (void)setStatus:(short)arg1;
- (void)setStatusLastUpdatedDate:(id)arg1;
- (void)setSummary:(id)arg1;
- (void)setType:(short)arg1;
- (short)status;
- (id)statusLastUpdatedDate;
- (id)summary;
- (short)type;

@end
