/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SleepDaemon.framework/SleepDaemon
 */

@interface HDSPSleepModeAutomatedOffState : _HDSPSleepModeTurnedOffState

- (void)automationTurnedOnSleepModeWithReason:(unsigned long long)arg1;
- (unsigned long long)defaultChangeReason;
- (void)sleepModeTurnedOnForUnknownReason;
- (id)stateName;

@end
