/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProximityAppleIDSetup.framework/ProximityAppleIDSetup
 */

@interface ProximityAppleIDSetup.PASFamilyMember : _TtCs12_SwiftObject {
    void familyMember;
    void imageData;
}

@end
