/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAI.framework/HomeAI
 */

@interface HMITorsoprint : HMFObject <NSSecureCoding> {
    NSUUID * _UUID;
    NSData * _data;
    bool  _lowQuality;
}

@property (readonly, copy) NSUUID *UUID;
@property (readonly, copy) NSData *data;
@property (readonly) bool lowQuality;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)UUID;
- (id)attributeDescriptions;
- (id)data;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithUUID:(id)arg1 data:(id)arg2;
- (id)initWithUUID:(id)arg1 data:(id)arg2 lowQuality:(bool)arg3;
- (bool)isEqual:(id)arg1;
- (bool)lowQuality;

@end
