/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksCore.framework/StocksCore
 */

@interface StocksCore.RemoteAppConfigurationService : _TtCs12_SwiftObject {
    void jsonProvider;
    void settingsFactory;
}

@end
