/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/IntelligencePlatformCore
 */

@interface _TtCV24IntelligencePlatformCore21SubgraphDatabaseTable24SubgraphComparableTriple : IntelligencePlatformCore.ExtendedTriple {
    void subgraphColumns;
}

@end
