/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/IntelligencePlatformCore
 */

@interface _TtCOO24IntelligencePlatformCore12OneShotTasks25IntelligencePlatformTasksP33_AD948141065DF512D4334E10387519D439HighFrequencyDataCollectionHourlyWakeup : _TtCs12_SwiftObject {
    void criteria;
    void name;
}

@end
