/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/IntelligencePlatformCore
 */

@interface IntelligencePlatformCore.dnhu_reranker_fj8szzw2rb : _TtCs12_SwiftObject {
    void model;
}

@end
