/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PreviewsServices.framework/PreviewsServices
 */

@interface _TtCC16PreviewsServices25PreviewsServiceConnectionP33_52070E8ABE391F2A715A602A9B1AE8AE15InterfaceTarget : NSObject <_TtP16PreviewsServicesP33_52070E8ABE391F2A715A602A9B1AE8AE26UVPreviewsServiceInterface_> {
    void receiver;
}

- (void).cxx_destruct;
- (id)init;
- (void)receiveMessage:(id)arg1;
- (void)receiveMessage:(id)arg1 replyHandler:(id /* block */)arg2;

@end
