/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.PDFSectionLoader : _TtCs12_SwiftObject {
    void sectionProviders;
}

@end
