/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

@interface SBAlwaysOnLiveRenderingSceneAssertionManager : NSObject <BLSBacklightStateObserving> {
    <BLSAssertionObserving> * _assertionObserver;
    BLSAssertion * _liveRenderingAssertion;
    NSHashTable * _liveRenderingAssertionProxies;
}

@property (nonatomic) <BLSAssertionObserving> *assertionObserver;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_acquireLiveRenderingAssertionIfNeededForProxy:(id)arg1 backlight:(id)arg2;
- (void)_acquireLiveRenderingAssertionProxy:(id)arg1;
- (void)_invalidateWithReason:(id)arg1;
- (id)_nextLiveRenderingAssertionProxyIfAny;
- (void)_releaseLiveRenderingAssertionProxy:(id)arg1;
- (void)_releaseLiveRenderingAssertionWithReason:(id)arg1;
- (id)acquireLiveRenderingAssertionWithReason:(id)arg1;
- (id)assertionAttributes;
- (id)assertionObserver;
- (void)backlight:(id)arg1 didChangeAlwaysOnEnabled:(bool)arg2;
- (void)backlight:(id)arg1 didCompleteUpdateToState:(long long)arg2 forEvent:(id)arg3;
- (void)dealloc;
- (id)description;
- (id)init;
- (void)invalidate;
- (void)setAssertionObserver:(id)arg1;

@end
