/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExposureNotificationUI.framework/HealthExposureNotificationUI
 */

@interface HealthExposureNotificationUI.KeyReleaseAuthorizationViewController : _TtGC28HealthExposureNotificationUI27AuthorizationViewControllerVS_18KeyReleaseDialogue_

- (id)initWithCoder:(id)arg1;

@end
