/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExposureNotificationUI.framework/HealthExposureNotificationUI
 */

@interface HealthExposureNotificationUI.PreApprovalViewController : _TtGC28HealthExposureNotificationUI27AuthorizationViewControllerVS_19PreApprovalDialogue_

- (id)initWithCoder:(id)arg1;

@end
