/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoAnalysis.framework/PhotoAnalysis
 */

@interface PHAFeaturesUsageReportingTask : NSObject <PHATask>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) double period;
@property (readonly) Class superclass;
@property (nonatomic, readonly) unsigned long long version;

+ (id)_dateFormatter;
+ (void)_reportCameraSharingSettingsWithPhotoLibrary:(id)arg1 andAnalytics:(id)arg2;
+ (bool)shouldReportSettingsWithLoggingConnection:(id)arg1;
+ (void)updateLastReportSettings;

- (id)_libraryScopedWorkerFeaturesUsageForLibrary:(id)arg1 error:(id*)arg2;
- (id)_libraryScopedWorkerFeaturesUsageURLForPhotoLibrary:(id)arg1;
- (bool)currentPlatformIsSupported;
- (id)name;
- (double)period;
- (bool)recordFeatureUsageFromCounts:(id)arg1 forPhotoLibrary:(id)arg2 error:(id*)arg3;
- (bool)runWithGraphManager:(id)arg1 progressReporter:(id)arg2 error:(id*)arg3;
- (bool)shouldRunWithGraphManager:(id)arg1;

@end
