/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemoteManagementUI.framework/RemoteManagementUI
 */

@interface RMUIAccountViewModelProvider : NSObject {
    NSMutableArray * _accountViewModels;
    RMObserverStore * _observerStore;
}

@property (nonatomic, retain) NSMutableArray *accountViewModels;
@property (nonatomic, retain) RMObserverStore *observerStore;

- (void).cxx_destruct;
- (id)_detailsForCalDAVDeclaration:(id)arg1;
- (id)_detailsForCardDAVDeclaration:(id)arg1;
- (id)_detailsForDeclaration:(id)arg1;
- (id)_detailsForExchangeDeclaration:(id)arg1;
- (id)_detailsForGoogleDeclaration:(id)arg1;
- (id)_detailsForLDAPDeclaration:(id)arg1;
- (id)_detailsForMailDeclaration:(id)arg1;
- (id)_detailsForSubscribedCalendarDeclaration:(id)arg1;
- (void)_updateViewModelsWithDeclarations:(id)arg1;
- (id)accountViewModels;
- (id)init;
- (void)loadAccountsFromConfigurationsWithCompletionHandler:(id /* block */)arg1;
- (id)observerStore;
- (void)setAccountViewModels:(id)arg1;
- (void)setObserverStore:(id)arg1;

@end
