/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeCore.framework/ScreenTimeCore
 */

@interface STCommunicationSafetyResourcesURLGenerator : NSObject

+ (id)communicationSafetySupportedCountryLanguagePairs;
+ (id)resourcesURL;
+ (id)resourcesURLForCountryCode:(id)arg1 languageCode:(id)arg2;

@end
