/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeCore.framework/ScreenTimeCore
 */

@interface STIntroductionModel : NSObject <NSSecureCoding> {
    NSDateComponents * _downtimeEndTime;
    NSDateComponents * _downtimeStartTime;
    NSString * _passcode;
    NSDictionary * _restrictions;
}

@property (copy) NSDateComponents *downtimeEndTime;
@property (copy) NSDateComponents *downtimeStartTime;
@property (copy) NSString *passcode;
@property (copy) NSDictionary *restrictions;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)downtimeEndTime;
- (id)downtimeStartTime;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDowntimeStartTime:(id)arg1 downtimeEndTime:(id)arg2 restrictions:(id)arg3 passcode:(id)arg4;
- (id)passcode;
- (id)restrictions;
- (void)setDowntimeEndTime:(id)arg1;
- (void)setDowntimeStartTime:(id)arg1;
- (void)setPasscode:(id)arg1;
- (void)setRestrictions:(id)arg1;

@end
