/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreODIEssentials.framework/CoreODIEssentials
 */

@interface CoreODIEssentials.DIPECIESSessionV3SecKey : _TtCs12_SwiftObject {
    void ePrivateKey;
    void ePublicKeyData;
}

@end
