/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreODIEssentials.framework/CoreODIEssentials
 */

@interface CoreODIEssentials.DIPWebService : NSObject {
    void conversation;
    void httpSession;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end
