/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemindersUICore.framework/RemindersUICore
 */

@interface RemindersUICore.TTRReminderTitleAttributesNoOpInteractor : _TtCs12_SwiftObject {
    void passthroughSubject;
}

@end
