/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemindersUICore.framework/RemindersUICore
 */

@interface RemindersUICore.TTRIHashtagCollectionViewAdaptor : _TtCs12_SwiftObject {
    void addTagButtonAction;
    void buttonFocusDelegate;
    void containerView;
    void hashtagButtonAction;
    void target;
}

@end
