/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemindersUICore.framework/RemindersUICore
 */

@interface RemindersUICore.TTRMainActorDeferredAction : _TtCs12_SwiftObject {
    void delegate;
    void l_scheduled;
    void lock;
}

@end
