/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemindersUICore.framework/RemindersUICore
 */

@interface RemindersUICore.TTRInlineHashtagEditProcessor : _TtCs12_SwiftObject {
    void changeDetailAdjuster;
    void maxTokenTextCharacterCount;
}

@end
