/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHNumberFieldResultReorderingStep : CHPostprocessingStepModifyingOriginalTokens {
    NSCharacterSet * _allowedCharacters;
    NSDictionary * _characterReplacements;
}

@property (nonatomic, retain) NSCharacterSet *allowedCharacters;
@property (nonatomic, retain) NSDictionary *characterReplacements;

+ (id)tokenRowAsString:(id)arg1;

- (void).cxx_destruct;
- (id)allowedCharacters;
- (id)characterReplacements;
- (long long)compareStringForPhoneNumberCompatibility:(id)arg1 with:(id)arg2;
- (long long)countUnallowedCharactersInString:(id)arg1;
- (id)initForDigitFields;
- (id)initForPhoneNumberFields;
- (id)process:(id)arg1 options:(id)arg2;
- (void)setAllowedCharacters:(id)arg1;
- (void)setCharacterReplacements:(id)arg1;

@end
