/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ShareArticleViewerFeatureProvider : _TtCs12_SwiftObject {
    void menuProvider;
    void sceneProvider;
    void sharingActivityProviderFactory;
    void toolbarManager;
}

@end
