/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.EndOfArticleDataManager : NSObject {
    void accessQueue;
    void articleRecirculationService;
    void delegate;
    void feedContextFactory;
    void feedService;
    void feedServiceConfigFetcher;
}

- (void).cxx_destruct;
- (id)init;

@end
