/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/VFX
 */

@interface VFX.VFXRemoteEditionEndpoint : NSObject {
    void effect;
    void multipeerAdvertiser;
    void name;
    void ownedByClient;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  urlToReloadFrom;
}

@property (nonatomic) _TtC3VFX9VFXEffect *effect;
@property (nonatomic, copy) NSString *name;

- (void).cxx_destruct;
- (void)dealloc;
- (id)effect;
- (id)init;
- (id)initWithName:(id)arg1;
- (id)name;
- (void)setEffect:(id)arg1;
- (void)setName:(id)arg1;
- (bool)startAndReturnError:(id*)arg1;
- (void)stop;

@end
