/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AirTrafficDevice.framework/AirTrafficDevice
 */

@interface ATStoreDownloadPrepareOperation : ATStoreDownloadOperation

- (void)execute;

@end
