/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriPrivateLearningInference.framework/SiriPrivateLearningInference
 */

@interface SiriPrivateLearningInference.EntityUtteranceComparison : SiriPrivateLearningInference.ThresholdedTurnComparison

@end
