/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriPrivateLearningInference.framework/SiriPrivateLearningInference
 */

@interface SiriPrivateLearningInference.SendMessageEventCoalescer : SiriPrivateLearningInference.CoreDuetEventCoalescing {
    void state;
}

@end
