/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreIDVShared.framework/CoreIDVShared
 */

@interface CoreIDVShared.CertUsageMapper : _TtCs12_SwiftObject {
    void mapping;
    void semaphore;
}

@end
