/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriAppLaunchIntents.framework/SiriAppLaunchIntents
 */

@interface SiriAppLaunchIntents.LaunchAppDeviceResolutionStrategy : _TtCs12_SwiftObject {
    void analyticsService;
    void deviceState;
    void historicalDeviceInteractionProvider;
    void remembersStoreProvider;
}

@end
