/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager
 */

@interface DOCUISession : NSObject

+ (id)anyWindowPreferingKeyWindow;
+ (id)defaultContentSizeCategory;
+ (id)keyWindow;
+ (void)performAfterCATransactionCommits:(id /* block */)arg1;
+ (id)shared;
+ (id)windowWithRootViewController:(id)arg1;

@end
