/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.HideMyEmailSignupBlueprintModifierFactory : _TtCs12_SwiftObject {
    void blueprintFactory;
}

@end
