/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.PaywallShownEntriesManager : _TtCs12_SwiftObject {
    void accessLock;
    void lazyStore;
    void shownEntries;
}

@end
