/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.PurchasingSpinnerAssembly : _TtCs12_SwiftObject

@end
