/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ProximityReader.framework/ProximityReader
 */

@interface ProximityReader.PaymentCardReader : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  events;
    void id;
    void options;
    void uuid;
}

@end
