/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ProximityReader.framework/ProximityReader
 */

@interface ProximityReader.DaemonPreference : _TtCs12_SwiftObject {
    void daemonPreference;
}

@end
