/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ProximityReader.framework/ProximityReader
 */

@interface ProximityReader.PaymentCardReaderForegroundObserver : _TtCs12_SwiftObject {
    void id;
}

@end
