/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeRecommendationEngine.framework/HomeRecommendationEngine
 */

@interface HRELockWhenDoorClosedTemplate : HRECharacteristicTriggerTemplate

- (id)_lazy_actionMap;
- (id)init;

@end
