/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeRecommendationEngine.framework/HomeRecommendationEngine
 */

@interface HRELightsAllOffContextActionTemplate : HREContextActionTemplate

- (id)_lazy_actionMap;
- (id)extraInvolvedTypes;
- (id)init;

@end
