/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Email.framework/Email
 */

@interface EMMessageFollowUpAction : EMMessageChangeAction {
    EMFollowUp * _followUp;
}

@property (nonatomic, readonly) EMFollowUp *followUp;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)followUp;
- (id)initWithCoder:(id)arg1;
- (id)initWithMessageListItems:(id)arg1 followUp:(id)arg2;
- (long long)signpostType;

@end
