/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthMedicationsUI.framework/HealthMedicationsUI
 */

@interface HealthMedicationsUI.NicknameNotesStepViewController : _TtGC19HealthMedicationsUI31SpecificationStepViewControllerCS_26NicknameAndNotesDataSource_

- (id)initWithCoder:(id)arg1;

@end
