/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthMedicationsUI.framework/HealthMedicationsUI
 */

@interface HealthMedicationsUI.MedicationSourceListViewController : HealthExperienceUI.CompoundDataSourceCollectionViewController {
    void medication;
    void sourceListDataSource;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)viewDidLoad;

@end
