/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthMedicationsUI.framework/HealthMedicationsUI
 */

@interface HealthMedicationsUI.MedicationDetailEditViewController : HealthExperienceUI.CompoundDataSourceCollectionViewController {
    void $__lazy_storage_$_userDomainConceptStore;
    void healthStore;
    void medication;
    void medmojiPreviewDataSource;
    void nameNotesPublisher;
}

- (void).cxx_destruct;
- (void)didTapCancel;
- (void)didTapDone;
- (id)initWithCoder:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)viewDidLoad;

@end
