/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthMedicationsUI.framework/HealthMedicationsUI
 */

@interface HealthMedicationsUI.InteractionNoneFoundItem : _TtCs12_SwiftObject {
    void reuseIdentifier;
}

@end
