/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthMedicationsUI.framework/HealthMedicationsUI
 */

@interface HealthMedicationsUI.MedicationChartDataSource : HKHealthQueryChartCacheDataSource {
    void decoder;
    void encoder;
    void medication;
    void sortDescriptors;
}

- (void).cxx_destruct;
- (id)chartPointsFromQueryData:(id)arg1 dataIsFromRemoteSource:(bool)arg2;
- (id)init;
- (id)initWithDisplayType:(id)arg1 healthStore:(id)arg2;
- (id)queriesForStartDate:(id)arg1 endDate:(id)arg2 statisticsInterval:(id)arg3 completionHandler:(id /* block */)arg4;
- (id /* block */)queryDataForStartDate:(id)arg1 endDate:(id)arg2 statisticsInterval:(id)arg3 healthStore:(id)arg4 completionHandler:(id /* block */)arg5;
- (id)queryDescription;
- (bool)supportsChartQueryDataGeneration;

@end
