/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/Frameworks/libVFXCore.dylib
 */

@interface _TtCV7VFXCore16ParticleSubSpawn6System : _TtCs12_SwiftObject

@end
