/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/Frameworks/libVFXCore.dylib
 */

@interface VFXCore.SmoothMotionSystem : _TtCs12_SwiftObject {
    void patchQuery;
    void query;
}

@end
