/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/Frameworks/libVFXCore.dylib
 */

@interface VFXCore.AudioSystem : _TtCs12_SwiftObject {
    void setupPlayersQuery;
    void updateAudioControllers;
    void updateFFT;
}

@end
