/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/Frameworks/libVFXCore.dylib
 */

@interface VFXCore.MDLImporter : _TtCs12_SwiftObject {
    void animations;
    void entityManager;
    void meshes;
    void options;
    void skeletons;
}

@end
