/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/Frameworks/libVFXCore.dylib
 */

@interface VFXCore.CurveCache : _TtCs12_SwiftObject {
    void device;
    void textures;
}

@end
