/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUIPrivate.framework/PhotosUIPrivate
 */

@interface _PUOneUpView : UIView

- (bool)canBecomeFocused;
- (id)focusEffect;

@end
