/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUIPrivate.framework/PhotosUIPrivate
 */

@interface PUCurationActionAssetBrowserViewController : PUPhotosAlbumViewController {
    NSMutableArray * _assetContainers;
    PHPhotoLibrary * _photoLibrary;
    PUCurationTraitContainer * _traitContainer;
}

@property (nonatomic, retain) NSMutableArray *assetContainers;
@property (nonatomic, retain) PHPhotoLibrary *photoLibrary;
@property (nonatomic, retain) PUCurationTraitContainer *traitContainer;

- (void).cxx_destruct;
- (id)_globalHeaderTitle;
- (void)_update;
- (id)assetContainers;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)configureGlobalHeaderView:(id)arg1;
- (double)globalHeaderHeight;
- (id)photoLibrary;
- (void)setAssetContainers:(id)arg1;
- (void)setPhotoLibrary:(id)arg1;
- (void)setTraitContainer:(id)arg1;
- (void)setTraitContainer:(id)arg1 withFaces:(id)arg2 detectionTraitsByFaceLocalIdentifier:(id)arg3;
- (id)traitContainer;
- (void)viewDidLoad;

@end
