/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/AltruisticBodyPoseKit
 */

@interface ABPKMultiPerson2DTracking : NSObject {
    ABPK2DDetectionConfiguration * _config2D;
    unsigned long long  _lastTrackingId;
    ABPK2DPoseEstimation * _poseEstimation2D;
    NSMutableArray * _previousMultiPerson2DResult;
}

- (void).cxx_destruct;
- (void)_endInitABPKSignpost;
- (void)_endMultiPerson2DTracking2DDetectionMLSignpostWithTimestamp:(double)arg1;
- (void)_endMultiPerson2DTracking2DDetectionPostProcessingSignpostWithTimestamp:(double)arg1;
- (void)_endMultiPerson2DTrackingImagePreProcessingSignpostWithTimestamp:(double)arg1;
- (void)_endMultiPerson2DTrackingPersonTrackingSignpostWithTimestamp:(double)arg1;
- (void)_endMultiPerson2DTrackingRunWithInputSignpostWithTimestamp:(double)arg1;
- (void)_startInitABPKSignpost;
- (void)_startMultiPerson2DTracking2DDetectionMLSignpostWithTimestamp:(double)arg1;
- (void)_startMultiPerson2DTracking2DDetectionPostProcessingSignpostWithTimestamp:(double)arg1;
- (void)_startMultiPerson2DTrackingImagePreProcessingSignpostWithTimestamp:(double)arg1;
- (void)_startMultiPerson2DTrackingPersonTrackingSignpostWithTimestamp:(double)arg1;
- (void)_startMultiPerson2DTrackingRunWithInputSignpostWithTimestamp:(double)arg1;
- (id)init;
- (bool)overlayResult:(id)arg1 OnImage:(struct __CVBuffer { }*)arg2 andGenerateOverlayImage:(struct __CVBuffer { }*)arg3;
- (int)runPoseEstimationWithInput:(struct __CVBuffer { }*)arg1 abpkDeviceOrientation:(long long)arg2 atTimeStamp:(double)arg3 andOutput:(id)arg4;
- (int)runPoseEstimationWithInput:(struct __CVBuffer { }*)arg1 deviceOrientation:(long long)arg2 atTimeStamp:(double)arg3 andOutput:(id)arg4;
- (int)runWithInput:(struct __CVBuffer { }*)arg1 abpkDeviceOrientation:(long long)arg2 atTimeStamp:(double)arg3 andOutput:(id)arg4;
- (int)runWithInput:(struct __CVBuffer { }*)arg1 deviceOrientation:(long long)arg2 atTimeStamp:(double)arg3 andOutput:(id)arg4;

@end
