/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOCoordinatePath : NSObject <NSSecureCoding> {
    struct vector<GEOLocationCoordinate3D, std::allocator<GEOLocationCoordinate3D>> { 
        struct { /* ? */ } *__begin_; 
        struct { /* ? */ } *__end_; 
        struct __compressed_pair<GEOLocationCoordinate3D *, std::allocator<GEOLocationCoordinate3D>> { 
            struct { /* ? */ } *__value_; 
        } __end_cap_; 
    }  _basicCoordinates;
    unsigned long long  _pathStartIndex;
    double  _pathStartOffset;
    struct vector<double, std::allocator<double>> { 
        double *__begin_; 
        double *__end_; 
        struct __compressed_pair<double *, std::allocator<double>> { 
            double *__value_; 
        } __end_cap_; 
    }  _pointLengths;
    NSArray * _supportPoints;
    struct vector<zilch::ControlPoint, std::allocator<zilch::ControlPoint>> { 
        struct ControlPoint {} *__begin_; 
        struct ControlPoint {} *__end_; 
        struct __compressed_pair<zilch::ControlPoint *, std::allocator<zilch::ControlPoint>> { 
            struct ControlPoint {} *__value_; 
        } __end_cap_; 
    }  _zilchPoints;
}

@property (nonatomic, readonly) unsigned long long count;
@property (nonatomic, readonly) double length;
@property (nonatomic) unsigned long long pathStartIndex;
@property (nonatomic) double pathStartOffset;
@property (nonatomic, readonly) double*pointLengths;
@property (nonatomic, readonly) struct ControlPoint { int x1; struct GeoCoordinates { struct Longitude { unsigned int x_1_2_1; } x_2_1_1; struct Latitude { unsigned int x_2_2_1; } x_2_1_2; int x_2_1_3; } x2; struct Angle { unsigned short x_3_1_1; } x3; struct FormOfWay { int x_4_1_1; } x4; struct FunctionalClass { int x_5_1_1; } x5; int x6; }*zilchControlPoints;

+ (bool)supportsSecureCoding;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)calibratePointLengths:(void*)arg1 startIndex:(unsigned long long)arg2 endIndex:(unsigned long long)arg3 rangeLength:(double)arg4;
- (struct { double x1; double x2; double x3; })coordinateAt:(unsigned long long)arg1;
- (unsigned long long)count;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithGeoRoutingPathData:(id)arg1 pathStartIndex:(unsigned long long)arg2;
- (double)length;
- (unsigned long long)pathStartIndex;
- (double)pathStartOffset;
- (double*)pointLengths;
- (void)setBasicCoordinates:(void*)arg1;
- (void)setPathStartIndex:(unsigned long long)arg1;
- (void)setPathStartOffset:(double)arg1;
- (void)setPointLengths:(void*)arg1;
- (void)setZilchPoints:(void*)arg1;
- (struct ControlPoint { int x1; struct GeoCoordinates { struct Longitude { unsigned int x_1_2_1; } x_2_1_1; struct Latitude { unsigned int x_2_2_1; } x_2_1_2; int x_2_1_3; } x2; struct Angle { unsigned short x_3_1_1; } x3; struct FormOfWay { int x_4_1_1; } x4; struct FunctionalClass { int x_5_1_1; } x5; int x6; }*)zilchControlPoints;

@end
