/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DVTInstrumentsUtilities.framework/DVTInstrumentsUtilities
 */

@interface XRSecureUnarchiveFromDataTransformer : NSValueTransformer

+ (void)addWhitelistedClass:(Class)arg1;
+ (id)whitelistedClassesForTransforming;

- (id)reverseTransformedValue:(id)arg1;
- (id)transformedValue:(id)arg1;

@end
