/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeFlexibleStorage.framework/BiomeFlexibleStorage
 */

@interface BMRegistrar : BMSQLStore {
    <BMStreamsAccessClientMethods> * _accessClient;
}

@property (nonatomic, readonly) NSDictionary *registeredClientsByStream;
@property (nonatomic, readonly) NSDictionary *streamRegistrationCounts;

+ (id)centralRegistrar;
+ (id)migrations;

- (void).cxx_destruct;
- (id)init;
- (id)initWithURL:(id)arg1;
- (bool)propagateDeletionOfEvents:(id)arg1;
- (bool)propagateDeletionOfEventsInStream:(id)arg1 withIdentifiers:(id)arg2;
- (bool)registerClientWithBundleID:(id)arg1 databaseURL:(id)arg2 source:(id)arg3;
- (id)registeredClientsByStream;
- (id)registrationsForStream:(id)arg1;
- (id)streamRegistrationCounts;

@end
