/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafari.framework/MobileSafari
 */

@interface SFStartPageSectionHeaderTitleView : UIView {
    UIButton * _button;
    NSArray * _currentConstraints;
    UIView * _currentConstraintsSubview;
    UIFont * _font;
    UILabel * _label;
    UIMenu * _menu;
    NSString * _title;
}

@property (nonatomic, copy) UIMenu *menu;
@property (nonatomic, copy) NSString *title;

// Image: /System/Library/PrivateFrameworks/MobileSafari.framework/MobileSafari

- (void).cxx_destruct;
- (void)buttonShapesEnabledStatusDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)menu;
- (void)setMenu:(id)arg1;
- (void)setModel:(id)arg1 visualStyleProvider:(id)arg2;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)traitCollectionDidChange:(id)arg1;

// Image: /System/Library/AccessibilityBundles/MobileSafariFramework.axbundle/MobileSafariFramework

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

@end
