/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafari.framework/MobileSafari
 */

@interface SFStartPageFooterCell : UICollectionViewCell {
    UIAction * _action;
    UIButton * _button;
}

@property (nonatomic, retain) UIAction *action;

+ (id)reuseIdentifier;

- (void).cxx_destruct;
- (id)action;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)primaryActionTriggered:(id)arg1;
- (void)setAction:(id)arg1;

@end
