/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInputCore.framework/TextInputCore
 */

@interface TIKeyboardQuickTypeSpecialization : TIKeyboardFeatureSpecialization

- (void*)createInputManager;
- (bool)doesComposeText;

@end
