/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextRecognition.framework/TextRecognition
 */

@interface CRRecognizerConfiguration : NSObject {
    double  _angleThresholdForRotatedCrops;
    <CRTextFeaturesFiltering> * _cachedTextFeatureFilter;
    <CRTextFeatureOrdering> * _cachedTextFeatureOrder;
    bool  _cpuOnly;
    bool  _falsePositiveFilteringDisabled;
    NSObject<MTLDevice> * _metalDevice;
    long long  _numTopStringCandidates;
    bool  _optimizeGroupsForStability;
    unsigned long long  _revision;
    bool  _scriptDetectionDisabled;
    bool  _skipRecognition;
}

@property (readonly) double angleThresholdForRotatedCrops;
@property (retain) <CRTextFeaturesFiltering> *cachedTextFeatureFilter;
@property (retain) <CRTextFeatureOrdering> *cachedTextFeatureOrder;
@property (readonly) bool cpuOnly;
@property (readonly) bool falsePositiveFilteringDisabled;
@property (readonly) NSObject<MTLDevice> *metalDevice;
@property (readonly) long long numTopStringCandidates;
@property bool optimizeGroupsForStability;
@property (readonly) unsigned long long revision;
@property (readonly) bool scriptDetectionDisabled;
@property (readonly) bool skipRecognition;
@property (readonly) <CRTextFeaturesFiltering> *textFeatureFilter;
@property (readonly) <CRTextFeatureOrdering> *textFeatureOrder;

+ (id)languageSetFromInputLanguages:(id)arg1 supportedLanguages:(id)arg2;
+ (id)supportedLanguagesForVersion:(long long)arg1;

- (void).cxx_destruct;
- (double)angleThresholdForRotatedCrops;
- (id)cachedTextFeatureFilter;
- (id)cachedTextFeatureOrder;
- (bool)cpuOnly;
- (bool)falsePositiveFilteringDisabled;
- (id)initV1DefaultConfigWithOptions:(id)arg1;
- (id)initV2DefaultConfigWithOptions:(id)arg1;
- (id)initV3DefaultConfigWithOptions:(id)arg1;
- (id)initWithImageReaderOptions:(id)arg1 error:(id*)arg2;
- (id)metalDevice;
- (long long)numTopStringCandidates;
- (bool)optimizeGroupsForStability;
- (unsigned long long)revision;
- (bool)scriptDetectionDisabled;
- (void)setCachedTextFeatureFilter:(id)arg1;
- (void)setCachedTextFeatureOrder:(id)arg1;
- (void)setOptimizeGroupsForStability:(bool)arg1;
- (bool)skipRecognition;
- (id)textFeatureFilter;
- (id)textFeatureOrder;

@end
