/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextRecognition.framework/TextRecognition
 */

@interface CRTextOrientationModelV1 : CRTextSequenceRecognizerModelEspresso

+ (id)defaultURLOfModelInThisBundle;

@end
