/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreML.framework/CoreML
 */

@interface MLClassifier : MLModel <MLClassifier>

@property (readonly) MLModelMetadata *metadata;
@property (nonatomic, retain) MLModelDescription *modelDescription;

+ (id)predictionFromFeatures:(id)arg1 classifier:(id)arg2 options:(id)arg3 error:(id*)arg4;

- (id)classLabels;
- (id)classifierResultFromOutputFeatures:(id)arg1 error:(id*)arg2;
- (id)classify:(id)arg1 options:(id)arg2 error:(id*)arg3;
- (id)initDescriptionOnlyWithSpecification:(void*)arg1 configuration:(id)arg2 error:(id*)arg3;
- (id)initWithDescription:(id)arg1 configuration:(id)arg2 error:(id*)arg3;
- (id)predictionFromFeatures:(id)arg1 options:(id)arg2 error:(id*)arg3;

@end
