/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreIDVPAD.framework/CoreIDVPAD
 */

@interface _PADModelLoader : NSObject <PADModelLoader> {
    PADVNFacePoseModel * _facePoseModel;
    PADVNPrintReplayS2Model * _printReplayS2Model;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) PADVNFacePoseModel *facePoseModel;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) PADVNPrintReplayS2Model *printReplayS2Model;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)dealloc;
- (id)facePoseModel;
- (id)init;
- (id)printReplayS2Model;

@end
