/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.OutputPublisherAsyncAdapter : _TtCs12_SwiftObject {
    void wrappedPublisher;
}

@end
