/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.DefaultSharingPolicyCheckFlowStrategySync : _TtCs12_SwiftObject

@end
