/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInputTestingKit.framework/TextInputTestingKit
 */

@interface HitTestFailure : NSObject <AutocorrectionResultClassifier>

- (bool)doesMatchResult:(id)arg1;

@end
